// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Batch update VM exclusion status
	// (POST /vms/batch-update-exclusion)
	BatchUpdateVMExclusion(c *gin.Context)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// BatchUpdateVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateVMExclusion(c)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.POST(options.BaseURL+"/vms/batch-update-exclusion", wrapper.BatchUpdateVMExclusion)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x923LcOJbgryByp6OkGGbqYrm67Qk/yJLtUnSlrdWtNrbsdSNJZCZGJMEGwJSzax0x",
	"/7AbMR80fzJfsoEDgARJ8JKplF092y/dLiUIHBwcnBvO5bdRyJKMpSSVYvTyt5EIlyTB8M/TBUnllEXk",
	"ivw1J0Kqv2WcZYRLSmBEwiKi/p+keTJ6+esoZGlKQkmiUTCKqCj/81MwkuuMjF6OhOQ0XYyC0Zcxwxkd",
	"hywiC5KOyRfJ8VjiBUw8o2mkhr0ccfLXnHISBSwlbP6qmBJV5v/69WtQDFWQAGTlqmz2rySUo6+B3tS1",
	"xDIXzf2ELBUsJp/NxJSl6q8RESGnmf7P0VnOOUklMmNRORYJPW1Q4KMCYzDqwMfXYEQ4Z9yzXjk/jEDu",
	"z55p7JlUZ7nBfEEkUj+iOeNILgnCChUOtJudnvpqvMI8xYlC3q8uZhXRnDmz1X46r0zuPbrAdxbe88yy",
	"mIZY/f4zFfKKiIylgjTPFpcD4b+pJAn84584mY9ejv7bQXkRDswtOHBm/7AifEXJg1rUQIE5x+tRHf7K",
	"Qj0gF5M2wK0c32/NY1Zo9/6wSs5YnkrnN5pKsiBc/7jV3u+mvbsGeIJRlTgtLHrhHlzcTZtYoNEmm6+B",
	"RBXpwVDfyq+xDJe3WYQlefMljHNBWdrO6OiCA5AwNCJR84YVkwAbIEgyJIiEy4bjGN1NRXlbZ4zFBKf6",
	"RC6i5oGP7qbo4lyoSXIAcRSUh9a88jS90D8e1U5pczab0PTVURDRFQkKXDa4qwY68KDFi2mShssE8/ur",
	"PPXwXE6wJNEpYH3OeILl6OVI7XksKdBUY78RFffX9G/k3cxP5VGuobomYXVSls9iZ8Y0T2b6ixbe+wYY",
	"bkKEwAuC6BzJJRWISqLnR3NMY2BwDRA14RYr01T+eFKOc2AtJvNvJSFyyTzUVuAU6REoFyRCe2SymARo",
	"lXxOsaQrsu8DLcOUv2/jHhkn2XkVfTVBQhOCRKYkIEuVEL5HcIIKHTiNEMdpxBI0p3GM9kpMHSGWxmsF",
	"z4DTEESoi3QxFIeC5Twk51hiIRn3b0yCAOwZs+QsXyyzXE5nmRhEOj6WU4LvILsJZRMmlxoqVF4l6Qag",
	"gXOJfBfwDGd4RmMq162Kjx1h/ruuFsUxCaW+IV0i40NmwC9XVOvPGSchFpJsOwFNRbY9ALUzKnfjTlyB",
	"sonE+hwuvrwoj3M101uCZc59OI24eJPiWWxFyRznsRy9nONYkKB2535ZErkkHJ1fXaO9c6oIdpYrHfiK",
	"aKJC1+GSRHlM+D6iAhE9sVH0qEChhsYrgCIOOlkFitF7ltal+cuRWh7nkiX6Sld0yXIFq02+zeN4jU71",
	"eGCSl5hLiut/neI0x/Eo0Gv6FGN1OfCCnG+BsWv9KWBuM8R8bT/UW0lj+reCaTdMiDmNSBp6lHB101HI",
	"VgRgKkeijPCQpFL9de9wfHR4uB+gEMdhHiskISzQ6uzydvxA6GKp/mDn8LLTBH+hiTqDo8ND0A30fx16",
	"GG2Y5Z/xatGE9NTAeHZ5i/Jyux5AdwFCgr80QZjqOb4RCNmL500QXjyXS7sejb8FNhKSdB9IQhLG198A",
	"is4z+WZQDDqWbwBNnf2be1PSTknI5SGWWyhRGrgMwis4rHS6lphLxyCp4gB+RUaUUZZO0BknkUIIjgXC",
	"nCAGQ3Gs1NaMkxVluYjXCDSNCK0oRpe3N+ggLD+bKH2lphaEhHtWv3wzHZNU2RQROjtFahCdKzOOoFme",
	"RjHx651CPDDuUWZXZySVhKNihHNWzt+aguGeZjexx3q6vqcZuvn5ugLZinD9z4rjxJGEOY/bYbu9+tkF",
	"K+fUB1EuCLfGqX+eYkTgsV47qcGruA0yXB6WxDqnQArCN15BaxexQpwTHK1Lz5X2/Viqg//IMBeVP4NQ",
	"10sM8xvV9qj/98os7P3xzIWmZYQDonfEZQF31wSwGe+AN3qHdc5gUOi92aCjv+Msz1r9DDWvT/VQP9gb",
	"vVBz1PyACf7yM0kXcjl6+fzwcGt3K0uoJEkm10GCv7x6fngIdDmnsVHeqxC9hb8j8iXj2uZBew/K8JsR",
	"tMIxVUZ8tF8F7ujw+ETz2uIvj/cNa6eFghimB5j91/CdRh0VWYzXyFzECnhPCtxh05diYDAobiEcw6Lb",
	"uEAf59IquiMgZiRm6QJJtmsmFozg4JufWo08rIkpI4+sHcGJzHlKIgX1xK+Wu8hTG3cAtqv7sFgx/Wu3",
	"jor7C7+ncc4JUbZkSOX63Wu/j2aJefSAOTkNQxIr+5NEU7ZyXQyOkFkyIS88+LkArMwp4YjNARVqpGLd",
	"nGhbJbIbUDwcS4mVzTcKRmkex8qsGb2UPCctLwJxi7eHSRay+AZ+8HlEmMRx3/5l29crkkZaOnU7auHX",
	"5mIN7BczBvbI2pFf25zFQidlnBOJadzvHamdXKp2JWiI2HweMxwhd7w+zcrxzbAgEWIp0rtBIs8yxqXr",
	"4i2fZLL12EyrWI/671Ew4lGikLFisddgrjrqA4AfUDgb6A5VeB88OMX4nKxo6MPN+9NTFMGPiBYELorb",
	"XuDkB4FmOLyn6QL9fPtedHq767trfQkxfoNTNdB35c4JpyvFezhLkAPpxblSmOf0ywRd4wREWa6sDJwK",
	"JNQfsuVa0BDHyKyAAJYJOp0JkmqX//u31+AOjZkaV+xTTEbtDo5p6z01A+6K+1RTd8+uLwpigo+sJ/j9",
	"m5vTy8sAXd5evQnQ+bszr0fYXuCmt0ITrPod7d1N314HamMBurtjcYA+3Pz05mrfq8h6BJy55A4tFnTW",
	"eSkvMeXNK6mYY4eG9Ob6f1DNQNXqSDKU0RRIblY4ziWboIs5UhqPJFGAsP4gZEnCUvXJjMmlc3SK7Qqi",
	"tcLCDxbiOF57D9UvQW8F4eOIzKmScQBb4YvK1EZ91NH0bteOX/sASwbTJpo9PnDvK3HfTP4D7vdve8+Z",
	"xESSn/GMxO9iNlPo7HjDnc+1Ut5kNMCOFLO9mwokl1iiJY7gxGM1N+IkYSv3rcYRYDDCg43iY5jvAYvm",
	"LC0oKQC1k/u2/kZImmBJrnC6IC0vLcSM0TzTvLelC3R081ptVp1Uw2qfESHPsPBdafOKUOMSH0fHz5OT",
	"Q/Fx5GUP5EvWgvX2+X5MTl60zffA+OYAvkiOjv0T+uzmt8aXrxRm34MGffH8Z/ZAuH3nqUIBP6EZy9NI",
	"IfnF8z+4zlpFOHwFLusB0lEtdZtlbUvBTztaytLKJeFHN6/7nkqq1PcVrKDBz17BSInDjYZHdLMP6Caj",
	"O980BU6ymHRERQgZRWS17Zuf+8TnrPSpgywJL5iiaPUFOJZS31nehWCXOS7A7mtBuJKq7VFQaheSRFd5",
	"KrpYbTGwfBIXXgY73EulkGkCKLo8VX7xX0p9eA23WmYp8veUpTgWGQmVIhohxkGQj61Y3+69/PVaEnGj",
	"jBcPE1d/RjM1QgdzgIEQ5cDd1MfYMLy9jBPQHiu/qX8BNir+6/aX8AKcW1jIx7PhZwMIiZBgaI65B6Jh",
	"Cw55eocNeJzIhI+d436gcklThJ3j4nnqPChmRLtW9C6x8cbwPE2t/9FQY+F/VNpmqszCoSFsvvuh/pdc",
	"Fmu3D3GAah10VUDbOuTM2UbroDdmf+2zFBsfGvugCNV/4TUNl1ccZTFOU68u1cEaB0Q/aEIJagzIha2b",
	"qdafTBovsyHEboZr78sWUpQfxyQGJiTQnnliRkcBEmpS4Kz73mvwSF5dD2mqKUVU3CNB/6b0AfTuNfA1",
	"h6cVYB7ud0cYdfLyckL3oOFRhvJykef+NQBjgyMLq7ZdZwCbj6IGkIFXrhVAtvChjLMFJ0KUvJil8VrL",
	"JcNm9l3PRNcWvZLW47xo4Y3XhK9oSMYxWZFYM8gJ+qCgkQ9M/7dA5AsVEv3nv/1fBM80aI9GMdlXQs1A",
	"i/acU02L/e1P0C9qTy6rndOUiiUR6msqkOWbAQhQoaExzlkQZLDixOHO9qXI8uNNGa7LJM1U/h/t/L6X",
	"F7+JCT7/nsDDpuklJE4yffgKB/rNRdmA5ruKTt4Zrbj1m07TGz38HSa7Xxzo4ej8+mdFt+QLaKejlyPz",
	"YP4xPzx8Rl6hP717Db4qEwyDXqEfMs6iH9rjGms2TEr/mlsMlW4+tHd7e3FeUVzynEbDfSXet5rmawXE",
	"x25+jDFWeqL+eOBZtsYXdz7fwDa6Y9MBquH8UxO0h5tk2OdIsBkL6ldkjBg/E1+UVpJPBUgLaaGG+lV9",
	"2aUHlxOYHfdqEOU4mNds0YW1FeU96B6MZJquSCoZX/d9cVEM/Ls6irupQAmW4VJJjOKO/CCQoengkXkE",
	"d5TLHMdTrFYgvYkE+nD0Epseu1L83hP5wPi9721dCTGPDoQTYt/cUv1x8WaRChoRjRQ1N/pw7WWKmedV",
	"6BLhKAJ1AgtBFymJlNzUAeRKAZzj0MvPEuyJup6enjnTIUFIimbrXsDSEhe1PZt9ggca/JoZ48qQHzCp",
	"fhuxD+RtM+tRKIZhaE/ks5RIlGABqsjZxfkVSpkEPbNu2z479vOFxnn/RIVkC44TDUam1AXwU+qH0Nrx",
	"Y4krNNv2kFmy04SmdzjOSZvXiGS+X+rpTHYS80WgIfHR70/Ma7dk+RnjpFN7P7u8RSEMan0Pdq2VLL9m",
	"4T2RvXMKM2zIrB2qgaMUFM8d4MLx0T8oJ9PXzckUemywH03R9LXPRdEPZ/tz+ND36uIVuv1N+SKdc+w5",
	"S61iiUvtAdSm4IZUGWb5hxXhZyxJqEyIT0aoo1NjwmIMulJXbYLOKlHFwF3RaRwzuDgQZSzQAdIi4tI+",
	"c54ZyhrgiC2fyza3Bn2bVVRyyR60CWAegaKIaqX5soLbVsyVp6JmGw4YXMcWmNQJmnBwP/PZhM0ASfed",
	"6dXp1BL/NkdrPrVna/4TrzDV12XQ6Rp5MhyFVhh7dq2jPcx98OOwRaUpb04bgtWon+xZe7WXnR1fPZSl",
	"XLpJvA4CKzfFz0BMZkqbN6PFc1B8h6w37XEWeg2OioHu/a2wz4PRKopA98Bx/GE+evlrj54YRffOjf66",
	"gYV/4arofo7bxTkGKfWK6hrm/GiKM3gJMaYzoE3reYRyVJgO9qG2AfmqFAEbQWG+++wTuhfnVp018Xre",
	"MD0zwYpw4fVM3OkfalMhnNEJess4Mu4E9HH0p8nh5Nnk8OOo12J2oA7Kk+k80XOjtnlP1U2v6kJfPRvr",
	"a7F6LZdnwCTuF2AdGkHffXxq0PDjvjPnVlpanaOnoolpsJ40cF78CpET8ZoTfB+xB08eE45WVJgb1RVq",
	"8UDlEmGJYoKFRCwl6NR8iahao8VdTiF0ZvPJz8yXHZO3PDb2zawfI9unpakWkN7L0jf5RflxxxIPmAPv",
	"3Hj6X/SHrVPX01cs+sslq/sLyuNvxvKXRDS16d9ATR4aEoIIYdWZBgsK21/kW/L+i0CdbjajhwXu+nY1",
	"3zbaPQYr8UBluNysAIONprNyV0icRpibqho2d1P9l50+GOWpCQJtqQ2yinHaEqG8SkRraIM/zra1JIIv",
	"e7aZceLmYPoivE1EtxvovcQrgkQ+n9OQgvuL0xWNScVx5cRIJ1QImi4uy1HNBxL9hh+i1XUGIdLllDpa",
	"C3OCzDwbRJPWEGb36kPWJaa8C0/dQcNvCRZ0FpMiZlin8YvSPtYPpmP9SmqDA58oQLg7fGYn2fWPexnu",
	"zbeunsZTxdT8Lh46r+hiKQX9G00XRiXpflxwNeBBUDcXqOk8dfLR3kOvLnoDOR3qZ3RxXgbCwwsMXiw4",
	"WYB1Oucs6dUey2V6lMfmBnqx82icfD8cDERBd9a6HuMF33LYKbsic2sOmEnPWJLlyiA0dQggXhN9HEUs",
	"wTQdh0fHzz6O9r3x0XZJ/9vfufPqZ9e0RlbNX20tE7t2xlmUQ1Ls2HzRCkJHrv717XRPu8P+49+dkMw/",
	"7KMDVPy2P6kl5keVDP+9w//8t/9zdHiI/rA/QRcKyIwTWUlUDnEuTWYuvFHG7GHyMR0YWtqWvV+FXY+q",
	"AQ5hAwXYuCXdf+8P+8NB8WaM/2KXEHmSYL6GFyvCx3dTlOAvOrVCoD1BCDKp1ChltXC37mW9KeIVDKwg",
	"Cbtxch2gKTAMaApPKZMII8nzggbHDzQiMGzvYUnDJXpgeRwhc1ORpAkZ41i/+uigULE/+FwjKu79W8o4",
	"W1FllZPoz6/V1tTQYmOVX1tOGAr2bHXEraUJaktPATAz2gfbtA02Tx7/RtBtTIB6vR3QYWupgv7VHVLb",
	"dnXwOX52MPw5zHKfzpwnav2VfizKUykQDjkTwhYoQyZHplEVpe5brSymSOrz/ax1PWesJr89RZ19K2+1",
	"b43Tz8kwYK5Op2hvOgAWnwf5c+h/nveY6i5Bg4CABXzVZ1oN9lI81wSnA0rwqLIUwHQqIrGVsLox30Ui",
	"fZqKTrRv1d5nWIbLz4L+rVqt6MeToPMQMsLRf88JX18SPkec5Wk0lpxmftdUhyakNSCdDsjmCLdpQZIh",
	"EbKM6BqlK8LXRjlx1CJvqPkuwkhhwc/GbdhdJeliDkItKOAEdMV0RXROpNH8IE0OJijiQPcDlAsdGKE+",
	"wbGOQDSmv7lAOvex8IFr+de09m2SS4FyA/Ifjw8PgxZddEnVUtoRaD5XujVNkSAhSyOB9p4dHr6K8DpA",
	"R386PHz1QMh9gNSUrxKWyqU/jDVm7H6Gw/vPS5ZzUYcmaKQJ6dHogaYRe1Crw3dltOwfjw/RK/TsEEV4",
	"LfxLqlv8uSeuT6F4ZnRhkc+K55puU8Elpp6LNyWS07AlWcqI54GZODGW5u4OkZtaYg9J8NHSddDIFwNH",
	"asXsczjQe1YZHhRo0bDpdfWOCiT0YP0KjJjNjLEhRhjwHrfIWVElCO1BbQ/0CmSdtaHbWJGySj/jDepy",
	"2kTBz3XMNuxhxol245sKTFZJLnJ2zJXaszcSHRQXvSXK3Rd9cls+hWmL0Ru9VeU/HmFfPtq0V9hwMo4q",
	"KPe+vSVbOWPupoZiPC4Yja/PJI2GH5f5RkjMBx+yLwTW4ieo6imV6SsQVnHeRjc2BNChxEEXqtsbpunA",
	"l/RJhVTEYjw1WmGnREzQrSDo3ZsbdMDLpQ5+o9FXOO95DmojSoCHQoL/pger4b7WJkJrrER/JKcRv3aL",
	"vWqlMxAWGIReC2YzQKUcaZGYEIm1q4vKJculi6cOtEJ+geSUrLSKASg2U9I0jPNIreEg/B/88/8r/vlf",
	"ktkNZ3OFHGiWKddXYttYlxaN0BdJl7DNSrMXL82+kFOWjvW9KtI07qbgHf9rTjglEZrlupxDylzN3+wW",
	"bOrJ9o98tggYg+OxKHQA9h2HLhz/j2Juuyvm5gD7O6zm5ofOlHNroY6OqDRovVGrb96WHLVN/kmdcxW/",
	"BMXS7VQNxVjupu2VCXAU+ToWQOAbjtyqK1BgbuC93OIs6m0K1K4TU3rNC53+2QHQPLp9OxB95GLDvYa1",
	"v2hKJd9R3k3Pi3yX6qT3NPU9Uq4zcGqtdLaOzYAxBVjCiLMkQPOYZdk6QLmYBUgQTnEcFGnTA0uz3E3P",
	"zftGzbnnc1m/zoWpPqXhEKGgAaIRCZDAEgcoXSX+Lge2zlRLOrX9GdFUV2cYVu5gTmNfJQMslyboE91N",
	"z/+M1DDrBYvcwIY6lPdk3Zo0cU/WNnFirVOzqNAOdFMqAZarJlcNSKRp6xAEaIGa7gbXGeGCCklSGSCa",
	"RiQjqYLmc9vfU5aWP3nPhEdJe9iQzowSCKMr/IA08aIpzjJIZI4oJ6FEP9++RzgMiXCVbseXKJaYd8Um",
	"lTikAunBaEbkAyEpSvJY0iwmLa1a/LSshaYW5mJ486EG6iVNQ4kiIk15sXK8jineqCJeWImq965UCVje",
	"bHKWhoSnZ1iSBePe4KZyFT0WheXgLZYCeTRkmVgP3GSJqJpL0HYuxaiNEeZ/ybEJAHbp+l59aA76O0vd",
	"TVsiMc0BrH2VBlaEK0Zoh1iDD2JJJ+g2vU/Zg3uEOrQOZ5nOaPzhg7pZP7i1AM7K+NJfivjSi0p86WkZ",
	"X2prmcA8A7MSzEYNdtbOgrVfyvVrP1TBqf3oQFf7xQJb+7OBvS/bXxcYJZGr7lfwbWJ7C9tNkbYkX6Ru",
	"rUNCliQkjeqVljwBsrVDXjIujcajf5nZZN9ayHBPRG1BR9WN+mlR03JH6BW8QQ96QiU4XBr496AEJ+OR",
	"jgTSd15X4KxUOfj1efAsOP7k3FRPff+OrKy4j+uYlXVNGRmDKpELUoHBCUbS9W0WplaRJdgKfJ2GS4al",
	"JFxB8PHj9SjYkO/EJV8BpPtP7P3FmUcJTSPyxZdoFJEvlnjfX5x1aiUef1O2OjnVGc2+5OnVSZHvbAvo",
	"qjVqoV930wfFjG4Yi4U/MXv1Y9ciP+5ikd6EbZtBYzRrheRNcrWvyJxwKAdoVEybpF4ADA4z2xfTV9Pb",
	"r7tYh2dHFsjSzbDuzJUsBrru6pbwkbeM69QBnag7bNwvVC5/cXxI7d+8Z7J7el/O3sgLWy8gbav671dr",
	"sb0vVK6Lxk5GdGzjwbNlpG4o4c57QpOD2YUsl52tUdHMD5UwIShAFCCSchouSaS5sc4tjYqyVBnheuAE",
	"XefKBiARATW7WOb1+qyYc+LLg3OT3LtznZpUa0LmyhXU7r85Bk0Qkfp+7CBQQsFr8G6b2gqmTCc0dE0X",
	"NDUtam7o6wAdHY6P9b+OD8fP9b+eH/7zDX29XwmfKBGnd27eCbbE3LvXj/jYImvHCPdu9GadEfGYhdQE",
	"PYt4aXazvPNmOvEjLyDaO3x1W6YIBejo1Rss1gE6fjUlEc2TAD179RPmUYBOXv2ypJK8i1ml/WPrFrO8",
	"7/B8+xt4Gc4ub+ECoFkOdSTKer6H45OPI/WP5+M/6X+8GB/9qP919Mfxs2P9z2fH/1yp+du2jSmEnz3h",
	"TvQC/Zvx7eHZ+Efz+4/Px0fHZr9Hxy/Gx8/N8OPnPw7b6HsaFrd9l9ucrUGTAO3Q2ZgB1QBp9qP/76QN",
	"YNpMLe30WteGf3XayrryftCjei0j0dctwEHgFhwvdaX8FcFik27S/dAx8VhO0zgOJpSpuy3TNF/7eGW2",
	"s7IcHCdbi6A+XXOQormxlqmGXYP78JyKezGwHv2KVNN2jQPShN5uoqVWVNRCd7KYLKS6qx5UD6yFkn13",
	"z6vKNqNPPT6nLZvHQRgAdGtbWy+FjRSo9XSboGmubKp4jYhuv70yLhTTGq6Z9rP5Ew6chNu8zteb7gla",
	"RsG6rS3uoIKnjt7tanQHfu57mmUkUsgSEpJZZgR6kyt7kucE4ZilC6h0ps8M0jOAZkOWzGiqZ7LVP08O",
	"D00BUdM64yWic/slFQjrLigQQl/07gcgBIBaAW9vhsP7B8wjAUoPllRncO7/S3VSiCZXFFObVk9G9My5",
	"0PSiAHfwoXZj8IhSQqISBamcPEknwM1PXK34tdZ762loqq+DVkHUn9Q9r9ZkaT7araXvAaA8LcxnOI43",
	"eWJLIk8eTRI9R0JncCgCKKqXm/m9QZZthU1ulqSsd2gDys9iSEy3H/UWMinGKXC9HFKPsLK3VoCSSl3q",
	"yRPSQHULGirR9U+n2nCUDM1yGmvih/d7byFU+m7wtAaPtxebLNCK0dOFgzuT6rA6nhxODvc3wGSJlOpe",
	"vNitOhi7snprldGcdy9vsd5KVbZmQyTnFcj7uTFm22I1I7eUt7+AXfNGlNVhm4UrRVlMVfsDIbFShssN",
	"n9p84X9VJJv8io6SQqaZOmXpmXm86kuRKr+wb3gCXjl45LRv0MH0xXN05H7Fichj2VKvxY4qK2h16pfJ",
	"Rf0La8z07wNsGDSHNi5FEOMAL3jbI0OlTZR5aCjnnY6e6NVg2/iWekyUrWnn8YtrO3rTK5BUtPjazVIq",
	"DDU+9kQpC+VoQNr05m6C3kL+EpNLwh+oIC11R4zu+0Ypk9Emjebt3aNCa6KR7StXzOld0R/WVrt4re28",
	"SJLF3iJwTZRgZEcPQ4WTs/h5QEv7omMR6FpOYCs6QN6AV/Qf/44UrQxK9KwA05ZpXs9dxxIye/f+sP8v",
	"ViWF8NKUNRIyt4PCm/DrgQKyxJ8ECn+i+LknxfsJFm9vEt9M437Ss2hNvvYDstvjMOLw2l+M0ZoMusON",
	"jatSZjiJPqTlP+fzAIlcQCRVNLijoo5HdwEoa4JUNBlHLyk4c0W09atYra1R2xSt957CHSFLJaapNerb",
	"5GOlQEdaSmTibYMvy2VKs9DGdBVVC9PIs+QPugox2iteT00qbPFfjGdLnOp/IZrq0DM6i1tiDhkn4pJw",
	"XVx5UL1meDuzL8O62vKwIL4wy0/nc5p6QxxtLlPRqFStd3EuPDgA45qmpjy5EpdKIYryuFY4awBInkLF",
	"A2vYWwRAxQ5c1Ky1IZVbxDh26fEuaTqRXRtTZ9TW9daiH0RsLaK2bN3cur1hVfVtfK8vqM3vk7RgFQCp",
	"YbsDRwkjDzCgPd2wmHCchuRNX/U4E23xFvKni89Ar9KfBkhXXEkwhfNSug2krIsljthDnbzncHGFxKlE",
	"c0xjtnKNF0fjmVOeqKV9iRH6Fx2J7D7l1tbam1EGHXTInHoZxJzFkY8iGyEeZeFY/cnmxAkV/C+8cfqw",
	"l0ZJ9rLofyXimi9J/KfPP55Ab4X91pXeexXZt3kcV0o46SWYrjOYLpBYC0mSTSNuFk6fB9HeggDU0oXt",
	"KOrp5dCz7rBeLG7PiZZi4QMOvGxdaDu++xh12ezO2xHRfwg/MSGbZ9C7+01a/3iIqQ78QM/BJlb6FRj/",
	"2kzPWsO8LjmFyjtOQ47HIgKs/Xb+arwBugdwEbm/LV9tfSv8L+478HWAOE3AdmTzon59t66gyC4hC+xz",
	"P7clR3R4Gkpjv7FQiJXSaax9EqE9aUzwlKGwUrO4JXPh9+J78BXe65c2KRGSRD/d9Yp3PdCqINbecqW7",
	"OtIHdWuW64xwiMPWqVt5hYe3weRu0KTCdmtBNpqyaMqDQniO2pVe9P7izFtytXiM7egSBX2ohWvj1DWO",
	"FmNSqfEd9mQwEpJxvCC3wndYWj03Q5DIACksFXnSqvpslkbV7rnquGIVLxbi2IzDKcKIk0UeYz6EKqRi",
	"66ZLQekZ7lRGQRJAlG0R6207LJqA565+SbBg20oXSjWNY9v0XA3SQQPOwnsww3smzWBoy2j+ZDZi/vAh",
	"tj99uPceez683P1d4lQM1eY/iFpIU/UpAivCBTzF5w2loOiAVZbr3Ki7nnNZmk4Bx9BsmOCOMLFmkeEL",
	"/S6P7joif8f93b5PX7ct+rlVV9DJya1JyZuoQ3ucZDEObQ9VhRj9y35H9saT52xsq0GlTM5inN77VCm/",
	"VuHluMxqD4VC0VAiCtRUYs0sc90qtMabmuAo+eYp0WdCmS692qslJM9DmXOdxJyMC7DHOqmSrgiK6Yxj",
	"aB7WeHZsFpFxMua2SbOqZu4Su5C/4xk0wO9P9bYDK3lYGpZPPWi0tlLvI2/9bdWDGYuywYzCc5w+btG5",
	"gbY2SC3dPnQ3D4Mw7ePXepRSNU0OX9dB+NzMkRGCvszmNvR68dnYqOjWAx16rTd1Kpvi+xvhFw3wm308",
	"OvMrG5ivtcFvGVD2t28Z4Ha3bxtSgtwyQidhtvSHKo/Rfyc8Wo2vVfz3ffFsLe3deF+0pcY3qdS9UY1G",
	"58F1s4rcW1e6Pt99jWrfU+CmmFOTb1bdsnwh3ayG9JDRbfWX+stAl69QukK6WxK56ify6K1D6j5f+go+",
	"D8PxwGLOl54qzm11mlsKUtVFq67+ZMd78NgGnB8pfcWYnWvYV5nZoTtfmeZPLblS9ZyqBpMDVRxGvR4U",
	"rnbzuiQPSYcW6V4lZ0MKZduS2GbiIbHwBvRyiU8dWWNPggX4wTRV2h0qWpIFYDGbpmwW7UGTXTCo7PJT",
	"Z5KIJ0W/pf2xzkazOVe16mbXyPyuU6YywtEVidBPWKI/n10jzCUNY4JOjp+dPH9x5Cg0JnAbxL/us/u5",
	"bI0Fuk2Sp1SuK39VOgLF8eclTqPY29uyBJi4fNONeMoWHEfkqlJkwWd2mN9JhD5cI/OVjTNDTiMveEmD",
	"WHTtGzZDwaGIkTusv5SzOUZfkzB7iF9NjzrYHZXKShudChMyWWQeIR2re3p5MXICekerI6CCjKQ4o6OX",
	"o2eTw8kzsM/lEgjhQEcFv/xttNCRDcz2CruIRi9H74iEiY2WDgoxOE7g4+PDQ6NVSTOJU8nk4F+FxrM2",
	"F/qMCXcZ2LMvFFkU8ZvP9dJ1pVxZ5ThGgvAV4cYggHQLyybUjnQktDNZZt7yqnu/NnufsoiM9LkRIV+z",
	"aL3bTav5rfejFsavzPGv3w/pCjIULnG6IJHC04kf6VBFEHG7BTXuhUfDZek8ppotbX16ZwCMOUCod6V+",
	"P6iXYWqlZXfcU+K1/LLibfTg2D5buFvQqU6Fbw/6gD4CabCErwRV8fCMWIpst9EDW8ro4LeyEurXg5qH",
	"uQ3DnqZUittwnBBdi+nX7jZU/kZTiHG0ICnRb3A27OzivBhu2/fgZ/M/zo7Do+iE/OnF4dGxTmWlkLuC",
	"5dJ6nl9Wi7xWL1zgHHLp6Ptfexakjx+jf/7fdsFfD8cv8Hj+6bejH7/u/5OH4X96QjLr6IfmoTSbItFo",
	"WwLuQCciv/AzIN4o/dzLBkrEIqM6wRcnvvKwnSvpqHt48iqKmjHzV6WwlfA8ShbYPXuQM1s7pGbuhq5f",
	"bD1TCnaP4JAsOysGNs7/xMcbi0rUQrIs0+x2630pANxSy1+D9vtq4Xx6CV9fykeidsiuJH3ombBF2kvM",
	"ZfXUdi/vXRRwuZHQP/4O52Ack6CYPl78F1ParjI0RRlnCwjveRy5Yyggb0PrXMqHS1vNZi6vbd0CSNiK",
	"6HZRpuK+DTN2e94W3FLxzhkWZDIKarR0Diu4SdSDmICziIbxcVxAQ+Fp2+vwgzoGdCZw45Oy4P/e7dXP",
	"iKXxen+C3pOVrivNBIFSOFwHl3Bkc00n6GYJMSBRxmgqUcSIAC7OiS09XcEtXmCaClk0KGpgVnGsLrTu",
	"kFsVy3RckxJBJXtplXXOPjWCH83dmufkcLncc8B3BumiC+sBImnI15k0eihUPlKEHqF7sg4g5h5WFtWG",
	"UPY+IKxf7rB+nHOhI3KCTqHVkeIWqUSXtzeIrQh/4FQS/VnGycp0zmySbpMiLvMGReyeb/uacn1bS20z",
	"chRlZffyuIDejg+PvhtMphNCDaJubdL5nHGUp5zgcAkZgDbe5JGKEic+Lt8QHAf1tt9eBnq2JOG98PUu",
	"nzMOgqUgXoH2CuUksC+B6p9zxkmIlda5bwofeK4BuqbpIiY6QN4uF6rVA4hMhFffRQ//PHO39JS0W/Tv",
	"7qCTYoyNlsoIL7H1DRkrnGGB0wICVCEAIA8l+bhsJYY38LNAgsTa8gYBCk1ohOKRZ9d3UFBcoAyH93ih",
	"G+xh9D8vLhHm4ZKuCNTd07PMY/IFGsvrDoR6UgWXoiw2n8c0JQinOF4LCoz5zZeQxGA95UIqlYUxH//U",
	"UF44jQQ6rfUzliR4LIgapPYUG/eF2RYEm4D1ZnvlvQT+vqLkYX+CTleYxrjYhSh/DCBIXgRF852gLLAu",
	"ArRKRGAjOgPXSAtsOOPY3pug4uEITBJ94Dy2uwEvowIAvb6OZgKHwV9zAvgwHgOAeOQ6Bx5n6v+NZtUr",
	"VLw0zGiKYeX6Ao1b45CKm0lSUpYiDiMQSWSQ7jDdwde7JTajRCM1DBuWeIlyXV16SMXS5q4u3Ll0lnR5",
	"oR8L8lbw9HMNfY0gWruwQ5ScK2v/ZTHWvjZIQgUGUrL6LrtEWfNaNbLeuhlJw2WC+f0EnWpbaux4UvJU",
	"l/KGMCq+Kvt2thssaom3JTBPaHyWq7TLgtd2e8hGuUBTCmgcoIsV6ccW2HmXZCjw5ObYPEo2ADzlvL2W",
	"lAksLsDXsUqgVmeEjzNMeWED2zgkr9Ru4O0J5fWQM7IhTCUJF7ZHBWOXLI59g0o3TCMiS0k7LNZpWOJZ",
	"ET3IuRTMy0RpbYV4QAqLYoIqqqZ+mlN2KNA/SEc1ga5shejctTOKskZK/qaIYB5TUjBO33XBXNbuy+6N",
	"jsoxfDdv0WYXdqi3yNHZAmurQOFcdekC7UKgHMU0oRKRLyEhkZ3V41s6TXVGbuW+Wy/TLu699jA5177K",
	"vRvGgZ+2TT9CYRJdldLGcIQSIpcs0jx7TjCkoeuE7YyEdE5DpMsjjiXmCyLrhI+0aQ4109IIEkT0A701",
	"s/CC6DL6SLKMxWyxRhHhdGWziSB0nPH7mM7l2NgkcBdsf2f0npU2hus34ARZQvQY5kw4d+QSU96wN3Z/",
	"ZyrLrJ/wVXVQgGwVGk9sbLsZRE0JAXXErbfpvKCE4mXkceJNE6i+e017xyX4WoHIbmdTYWCbDI+VMvMU",
	"eRZV/qD4myAcLY3zyJ5Wmy3tiBTXpC7vBrRqSnCKFySBlkZ30zIiDjJrIPAmjOG/9ifozi1fyNJ4DRGg",
	"dXpXiBZ45SX43KH337lPqsdxBIeDoTmrOQYH/QoNC45TuTP/zcnhs11bIyKfz2moa/81KChACRWCpouX",
	"6NfiDk1OTc7pNeTFVePnJ4WBPDkDL9Ynb5y5nvWyWKgC1a+jlrVG9YyYxmqV1JT+BiG9Fs1pLpfqWAy1",
	"izzUEhYacsI9jHF4L3zH/ygGA3ds7X1WURSXEQ4oZGmT45TegHYBa7XucuwwCWdKyxpZacSoAigsvVK0",
	"7CtUFZ/vT09tU70yM05sKTQrmv55ueWn1jDLpRyZ+U1kZLGyqUQ0QEjakBmHJB4dHoMLz5Q7a40GQd86",
	"+C3FCfnaZbFrM1ELslInBRdwqdSBkJ3phOwJutEkamWawjFNc1JG6FBbdkYrfYqMhKRxbJ5Z+mx6pYr0",
	"+fbUGJ0fjoWFs/QegGpfPPN6g2pMiHV7OE2/x+z4EYJAYeZ9W5viIhWnCEi16SiftnJSXWodycwxyAnB",
	"bU6vNW/KeJaDwlyZ05SK5WN92NpPgZHQzwRai6xRM8/T9pcMy0ppGtEVjXIcu9aVtBrXBNl+x/Ha5J/q",
	"bODM0lIPj7vKdY5eF12aBsbg2HKnbnHUFmSwO1/tlrytsIuv8nQTxlYhmR0wt/p8HkKABv1dQU06mqBy",
	"cH3ndpWn6OLczyp64u56aw14DtBz/RQETihFdwCLhrbtJqupdmNlmbgMXD2WxqkI6NHedz9DbbJF4Fij",
	"QtLQvDXW3AQ/CHc5nbE4QbaGThGgYav83F4gyYoG3KUTW9KkaHREhngqxXChIxlaEFnbSP8df4y02b3P",
	"1HTWb97tmyVn+WKZ5e4OW4lyqi0JZPeJChw+OmhE+gFR1FcWpPaGCype8k4PGcaxTf1qo+SgvRALMqap",
	"IKmgEBsi8pk+HR3svN9y2rN1Lz8PmnRVVGpAe0djaHaoa6b46WlRnb+o0HMUlP0lj3yZOe1JP2b72o2z",
	"IB1LmxKenuWPD6HxvVnfVCJoh+YpSRyOfmg4uyGlPqarVQZEvmScgOG3A00+jp3V/cGe2qqGDT1VpGe5",
	"wkZeyKPdHpfviOAHG4wzNK7Tlg2k1YMT61TiL/uPU1YBEoRRSh70ybncaKBiYs+yky3pnT9WJYFCOUMC",
	"/T1ahIZgh9GdBl/tAd7fHzENDnkN0f2UxFERYchNMEvRoUwt/RKL8ONIWUtFgsdLNVNQ/rg/QXeGHmE6",
	"cNHihATIrZ9cRJVop6/itoGpNBeY4m0BCrP8VuAF0WPMPzlOzL/CLD9dLeCz0xVEVjmOPQsdFqFBGwCq",
	"TEvyJYuhL79GmzeyhHFZ4f7D2zsIuQaHpzqDUbcQnIPVuTBdf76lHITtbCUGv6+s65Jz9iLDi72mYpOm",
	"ddJ+73djPyglDq69UqwuzvXiVAoLQKZUqSYv0GWWfid8cvcC19ned0qm7BG4OQC4Q4H75ISmUeqK5CJM",
	"tS/96cINtnsyjF9YcNpDE+6mAnFI7DDu+r/mRJdd9R7CaZmaon17Ov4WS9KK8QIIndiwk2gDlpURwYik",
	"knISr7ukfB0TPRf8Ym5azNFUVwYrGm/dnZ//2cn2+ItJJf9LgP6SRM//sq9LLpkKXRM3nga+fMACpZAW",
	"YmectPB7s/JdFN37BY4pjVpP6H9Stj+AoMrj3lGKGvVM2JGiVrtZ2zFST8xVtfuSdfLXqkZUX/03fZ0O",
	"RqvkIhKbaDiNwhfqe3+NhG8XEjWcSnaZQFcS3u4jm5yzV2pikQpe0GYj4MNLoDbiowD17zYKwghr/TIu",
	"xDyP43XrCb7GEaoR+vYv5DYtzpt6qHseGBFcO6GV4qQdmfnFoSiW+/RBpLUOk547Yl3YUEXR1lctvmi0",
	"hDSlc0HMSMwnH9MLUzpZ/cWkUED8kG4DStLi2wBhdHJ4guxmIRzYBBJPPrYnl6g97FBpB0AbGXqNIKLK",
	"QXVemySPJc0wlwdK6R5DYHnH++ic+oqfW4Safpv9WQhVlgyTbseRvyWx3QIpOPe58zZvUsvk5OiZr7VI",
	"TEzcqkA/nkxf61DWR6rjsIXKeRkeYJN3Oq//wAyfhm5Y9A69KGIBiou0d2aa+8bEFi1Jcxw7oTX6Du63",
	"qYHqo1M9+WZqYNDy5lCuLFm9RDIV2pj5QXgcz374YLyuEvJ0D0ssJR/mcBTdaoc9QbX5flvYGf+pPcff",
	"jYPqsHEsUhU3LGJldlWeoQqDImmnHEjnc5RTAeUK6oE8qUxrrDb0NaRZ3UTs5qGjZWK/enbD6WJBuFs1",
	"pqyU8DTqWXOt75TG0Dg6Wziwu/qF1Cgj0b8UbdIH1sFxRMjWx2wOrHLKCZGchqJR5MIZc/CbhvGzeTlp",
	"EwkNnPQGdOjCPLe3ba7BYt3fzbt8c48+TbSlzNGJtzq5QsHulEInItBTAwlkqrI+oP+zPvrO8y6qd23G",
	"Ns/sV30U0ARx19TQJtjPr392xHW98tdnGqFX6AenbNgP8Dr0IaFS5wqq2ws802Jo0hpt8MbVCpzXCLcn",
	"wPHJ4fcu9tUnfXwFv/BiwckCSyK+HYnbWmkxWZG4BZp6dKy9hkNIvVKobiOGd1Z0Vf3dUf0/yuJ957J4",
	"g+/Hk5eocyGrXRO7LDxttFyfohps+8W4M0Oe0kTXS0A5Yt87jf7ZTbNoLdy6ahl7YLrctO5yOjRwbbau",
	"iBowIQk8sGqJrOsUmaThcmSly8yIfMmOdi9i/hFN8Y9oir+3aIqO/lsdRnMRTzHgsdy51I8uCFoub9Rv",
	"4AlK9kOOWnnolucczBR/GOs3gzE0W7IM12+Iv1bjtZPmbvqmGP80JrizWLHU5hES9WfyGPCz0TOJ96HL",
	"I18/OEUe1CK7UUQBDQZgZUwVx+TWrYDT1Oc9ZllvOem7qdAC40P25CWl76aVpboukBFidgOPvRARdFIL",
	"pfWZ6nnRCse50duL90KFvrJfWzvaftZjnhRdeo0hjKbYoAH90SZ9HNfnVNpgLgjCIWdC+BB28Bv8/4BQ",
	"V9jYu5jNsLptPQrNDZR1npFYG8EJWxGjLOor7DcDdO+xLgvgUf3xnlTYeJDUSQSAHBsitLBo7WNiGqe7",
	"ycowobx6ysrh9EXzAfAD1NoKFSQsovP1dzz4pwr+s9h4rHTTJOFU/itqa7lyDu3hmhTEkiU0VOSz/3RC",
	"EO2lzPRkECjBEXlc8P0UiMEQB/gYlZ4pljRDeziKDgzLsMRzAOR5NxX7Jf/6rcfrAi2nOsmz3hA42irw",
	"9FsymSrENnXdY9ZWdxaV7Xb9AQfV4btzwdlAZTxjuUQYrZJe3vJdj+0JAoU6es5uyyjupk+jAd9NdxvB",
	"q0vflNERzsU9cMpidmgeujb63fQtZ0klArFGIL/zW9vsO/r4kGFv/K/i3bXrEeJUByb1Vw1oYwPILGKi",
	"MAq4tqYPfax1SGHTTkigWadCNgPbwdxNN+gEUwNDe763zEL4tmTl66juI6yqk7lHGLxnnlYtQAZuN8dd",
	"OpdnnOD7iD003MxqHfgU5tJnl/N49HJ0gDN6sDoaff309f8FAAD//4pNxDByHgEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
