// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List detected applications running on VMs
	// (GET /applications)
	GetApplications(c *gin.Context)
	// Get cluster-level utilization aggregates for the latest completed report
	// (GET /cluster_rightsizing)
	GetLatestRightsizingClusters(c *gin.Context, params GetLatestRightsizingClustersParams)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /cluster_rightsizing/{report_id})
	GetRightsizingReportClusters(c *gin.Context, reportId string, params GetRightsizingReportClustersParams)
	// Get latest cluster utilization by cluster ID
	// (GET /clusters/{cluster_id}/utilization)
	GetClusterUtilization(c *gin.Context, clusterId string)
	// Stop collection
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start inventory collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Export VM inventory and migration planning data
	// (GET /export)
	ExportInventory(c *gin.Context, params ExportInventoryParams)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// Verify vCenter credentials and permissions
	// (PUT /forecaster/credentials)
	PutForecasterCredentials(c *gin.Context)
	// List available datastores
	// (POST /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List all groups
	// (GET /groups)
	ListGroups(c *gin.Context, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(c *gin.Context)
	// Delete group
	// (DELETE /groups/{id})
	DeleteGroup(c *gin.Context, id openapi_types.UUID)
	// Get group by ID with its VMs
	// (GET /groups/{id})
	GetGroup(c *gin.Context, id openapi_types.UUID, params GetGroupParams)
	// Update group
	// (PATCH /groups/{id})
	UpdateGroup(c *gin.Context, id openapi_types.UUID)
	// Stop inspector entirely
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Validate vCenter credentials for inspector
	// (POST /inspector/credentials)
	ValidateInspectorCredentials(c *gin.Context)
	// Get VDDK status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get collected inventory
	// (GET /inventory)
	GetInventory(c *gin.Context, params GetInventoryParams)
	// List all rightsizing reports
	// (GET /rightsizing)
	ListRightsizingReports(c *gin.Context)
	// Trigger rightsizing metrics collection
	// (POST /rightsizing)
	TriggerRightsizingCollection(c *gin.Context)
	// Get a specific rightsizing report with full VM metrics
	// (GET /rightsizing/{report_id})
	GetRightsizingReport(c *gin.Context, reportId string)
	// Get cluster-level utilization aggregates for a specific report
	// (GET /rightsizing/{report_id}/clusters)
	ListRightsizingReportClusters(c *gin.Context, reportId string, params ListRightsizingReportClustersParams)
	// Get utilization for a specific cluster from a specific report
	// (GET /rightsizing/{report_id}/clusters/{cluster_id})
	GetRightsizingReportCluster(c *gin.Context, reportId string, clusterId string)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// Get list of VMs with filtering and pagination
	// (GET /vms)
	GetVMs(c *gin.Context, params GetVMsParams)
	// Get distinct filter option values for VMs
	// (GET /vms/filter-options)
	GetVMsFilterOptions(c *gin.Context)
	// Get all distinct labels in use across VMs
	// (GET /vms/labels)
	GetVMLabels(c *gin.Context)
	// Delete label from all VMs
	// (DELETE /vms/labels/{label})
	DeleteLabelGlobally(c *gin.Context, label string)
	// Modify label VM membership (add/remove label to/from VMs)
	// (PATCH /vms/labels/{label})
	UpdateLabelVMs(c *gin.Context, label string)
	// Get details about a vm
	// (GET /vms/{id})
	GetVM(c *gin.Context, id string)
	// Update VM properties
	// (PATCH /vms/{id})
	UpdateVM(c *gin.Context, id string)
	// Remove VirtualMachine from inspection queue
	// (DELETE /vms/{id}/inspection)
	RemoveVMFromInspection(c *gin.Context, id string)
	// Get utilization breakdown for a specific VM
	// (GET /vms/{id}/utilization)
	GetVMUtilization(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// GetApplications operation middleware
func (siw *ServerInterfaceWrapper) GetApplications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApplications(c)
}

// GetLatestRightsizingClusters operation middleware
func (siw *ServerInterfaceWrapper) GetLatestRightsizingClusters(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestRightsizingClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestRightsizingClusters(c, params)
}

// GetRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportClusters(c, reportId, params)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, clusterId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ExportInventory operation middleware
func (siw *ServerInterfaceWrapper) ExportInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportInventoryParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportInventory(c, params)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// PutForecasterCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutForecasterCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutForecasterCredentials(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, params)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, params)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// ValidateInspectorCredentials operation middleware
func (siw *ServerInterfaceWrapper) ValidateInspectorCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateInspectorCredentials(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInventoryParams

	// ------------- Optional query parameter "withAgentId" -------------

	err = runtime.BindQueryParameter("form", true, false, "withAgentId", c.Request.URL.Query(), &params.WithAgentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter withAgentId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", c.Request.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter group_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, params)
}

// ListRightsizingReports operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReports(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReports(c)
}

// TriggerRightsizingCollection operation middleware
func (siw *ServerInterfaceWrapper) TriggerRightsizingCollection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TriggerRightsizingCollection(c)
}

// GetRightsizingReport operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReport(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReport(c, reportId)
}

// ListRightsizingReportClusters operation middleware
func (siw *ServerInterfaceWrapper) ListRightsizingReportClusters(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRightsizingReportClustersParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRightsizingReportClusters(c, reportId, params)
}

// GetRightsizingReportCluster operation middleware
func (siw *ServerInterfaceWrapper) GetRightsizingReportCluster(c *gin.Context) {

	var err error

	// ------------- Path parameter "report_id" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "cluster_id" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_id", c.Param("cluster_id"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cluster_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRightsizingReportCluster(c, reportId, clusterId)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GetVMs operation middleware
func (siw *ServerInterfaceWrapper) GetVMs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVMsParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMs(c, params)
}

// GetVMsFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMsFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMsFilterOptions(c)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c)
}

// DeleteLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLabelGlobally(c, label)
}

// UpdateLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLabelVMs(c, label)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVM(c, id)
}

// UpdateVM operation middleware
func (siw *ServerInterfaceWrapper) UpdateVM(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVM(c, id)
}

// RemoveVMFromInspection operation middleware
func (siw *ServerInterfaceWrapper) RemoveVMFromInspection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveVMFromInspection(c, id)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/applications", wrapper.GetApplications)
	router.GET(options.BaseURL+"/cluster_rightsizing", wrapper.GetLatestRightsizingClusters)
	router.GET(options.BaseURL+"/cluster_rightsizing/:report_id", wrapper.GetRightsizingReportClusters)
	router.GET(options.BaseURL+"/clusters/:cluster_id/utilization", wrapper.GetClusterUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/export", wrapper.ExportInventory)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.PUT(options.BaseURL+"/forecaster/credentials", wrapper.PutForecasterCredentials)
	router.POST(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/groups/:id", wrapper.GetGroup)
	router.PATCH(options.BaseURL+"/groups/:id", wrapper.UpdateGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.POST(options.BaseURL+"/inspector/credentials", wrapper.ValidateInspectorCredentials)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/rightsizing", wrapper.ListRightsizingReports)
	router.POST(options.BaseURL+"/rightsizing", wrapper.TriggerRightsizingCollection)
	router.GET(options.BaseURL+"/rightsizing/:report_id", wrapper.GetRightsizingReport)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters", wrapper.ListRightsizingReportClusters)
	router.GET(options.BaseURL+"/rightsizing/:report_id/clusters/:cluster_id", wrapper.GetRightsizingReportCluster)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/vms", wrapper.GetVMs)
	router.GET(options.BaseURL+"/vms/filter-options", wrapper.GetVMsFilterOptions)
	router.GET(options.BaseURL+"/vms/labels", wrapper.GetVMLabels)
	router.DELETE(options.BaseURL+"/vms/labels/:label", wrapper.DeleteLabelGlobally)
	router.PATCH(options.BaseURL+"/vms/labels/:label", wrapper.UpdateLabelVMs)
	router.GET(options.BaseURL+"/vms/:id", wrapper.GetVM)
	router.PATCH(options.BaseURL+"/vms/:id", wrapper.UpdateVM)
	router.DELETE(options.BaseURL+"/vms/:id/inspection", wrapper.RemoveVMFromInspection)
	router.GET(options.BaseURL+"/vms/:id/utilization", wrapper.GetVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y963LcOJIo/CqI+naipVjq5kvPtDf8Q5Zst2Jdtj7d+ouv7eNBkagqrEiAA4Al1/Rx",
	"xL7DORH7QPsm+yQnkABIkAQvJZXs3jn9p9t2gchEIpHITOTlt0nMs5wzwpScvPhtIuMlyTD88XhBmJry",
	"hFyQvxVEKv1vueA5EYoSGJHxhOj/E1Zkkxe/TmLOGIkVSSbRJKGy+uunaKLWOZm8mEglKFtMosmXPY5z",
	"uhfzhCwI2yNflMB7Ci9g4hlliR72YiLI3woqSBJxRvj8ZTklqs3/9evXqByqMQHMKqh89m8kVpOvkVnU",
	"pcKqkO31xJxJnpLPdmLKmf7XhMhY0Nz8dXJSCEGYQnYsqsYiaaaNSnrUcIwmPfT4Gk2IEFwE4FXzwwjk",
	"/xyYxu1JfZYrLBZEIf0jmnOB1JIgrEnhYbvZ7umv9lZYMJxp4v3qU1YzzYk3W+On09rkwa2LQnsR3M88",
	"T2mM9e/vqFQXROacSdLeW1wNhL9TRTL4wz8JMp+8mPw/B9VBOLCn4MCb/cOKiBUldxqoxQILgdeTJv41",
	"QAMol5O20K1t32/tbdZkD/6wyk54wZT3G2WKLIgwP95r7TfTwVUDPtGkzpwOFwN4gBY30zYVaLLJ4hso",
	"Uc16MDQE+RVh8TLD4vaiYAFJIAhWJDkGOs65yLCavJgkWJE9RWGlLaQSKm8v6d/J21mY9kkhYJ2XJK5P",
	"yotZ6s3IimxmvuiQCK9BDGRESrwgiM6RWlKJqCJmfjTHNIVj10LRkLOETJn68Vk1zsO1nCy8lIyoJU/a",
	"mJU0RWYEKiRJ0A7ZX+xHaJV9ZljRFdkNoZZjKt538XQuSH5aJ19DvNGMIJlrucyZvhpuEeygJgdmCRKY",
	"JTxDc5qmaKei1BHiLF1rfEbshiRSUs7OxtJQ8kLE5BQrLBUX4YUpEMsDY5aCF4tlXqjpLJejWCd0ECr0",
	"PWK3sWzj5HNDjcvrLN1CNPIOUegAnuAcz2hK1brzOnYj7N+bl3WakliZE9InyD7kFv0KooY/54LEWCpy",
	"3wkok/n9EWjsUbUaf+Ialm0iNufw6RUkeVromd4QrAoRomki5GuGZ1p8wBmb4yJVkxdznEoSNc7cL0ui",
	"lkSg04tLtHNKNcPOCq2ZXRDDVOgyXpKkSInYRVQiYia26geVKDbYVOw74zwlmIGwFKAp1LCYvOesece8",
	"mGjwuFA8M0e6puFUEJyO86ZI0zU6NuNBSJ5joShu/usUswKnk8jADKlr+nDgBTm9B8UuzadAuc0I87V7",
	"U68VTenfS6HdUmznNCEsDqiG+qSjmK8I4FSNRDkRMWFK/+vO4d7R4eFuhGKcxkWqiYSwRKuT8+u9O0IX",
	"S/0Pbo6gOM3wF5rpPTg6PIwmGWXmb4cBQRvnxWe8WrQxPbY4npxfo6JabgDRbaCQ4S9tFKZmjm+EQv7T",
	"8zYKPz1XSwePpt+CGhnJ+jckIxkX62+ARe+efDMsRm3LN8CmKf7tual4p2LkahOrJVQkjXwBEbw43O10",
	"qbBQnj8Ap+mH+eTFr/0X4I1eNhEngiSaOjiVk6+fGtMGNYBRGvDdkjjbG8QpfBOU2A6Iuw0Ewcm6MsyN",
	"aWtvYvOXHAtZ+2e4HQyIcWZxY43mvxcWcPDHEx+bjhEeisER5yXefRPAYoIDXpsVNlnMkjDIIqDsvRW8",
	"yDv9RQ2jtr6pH+APOEULPUfDzZHhL+8IW6jl5MXzw8N7e5N4pk3fXK2jDH95+fzwEA7RnKZWC6xj9Ab+",
	"HZEvuTDKM9q50xbEjKAVTqm2BpPdOnJHh0+emUNb/svDXV8ZZS+PAGOYHnB2JnAd47eGdFTmKV4ja5PX",
	"0HtU5A7bjjiLgyVxB+NYqdAlBQqRtpe6OgGZgq4v3hldrxIuaEZSzhZI8ZAYKCQRYeq5KcsRga9h49uf",
	"OtXOxwILgsCESkqFVBBVCEYSjfV+WL/ziacX7iHsoIeoWLMhG6eOytuzsCNlLgjRRklM1frtq7Cxv8Qi",
	"ucOCHMcxSbUhQ5IpX/m2qqe3L7lUZwH6nAFV5pQIxOdACj1Si25BjNKbuAVoGY6Vwtp4mEQTVqSp1o8n",
	"L5QoSIfDM+1wG3DFY55ewQ8h05ornA6tX3V9vSIsMbdTvx8Kfm0Da1G/nDFyW9ZN/MbiHBV6OeOUKEzT",
	"YTO7sXNMr0rSGPH5POU4Qf54s5u17ZthSRLEGTKrQbLIcy6U8SNksv5ekK/37LRa9Oi/T6KJSDJNjBVP",
	"g5ZX3Q8ZAf5AwtlIv5qm++jBDONTsqJxiDbvj49RAj8iWjK4LE97SZMfJJrh+JayBXp3/V76pBhcXaej",
	"1xqgx3pg6MidEkFXWvYIniEP07NTlAsyp1/20SXO4CortLqKmURS/0O+XEsa4xRZCAhw2UfHM0mYgtW9",
	"f3MJfrWU63HlOuX+pNtSnnaeUzvgpjxP9YVcnlyelcwEHzmX4vvXV8fn5xE6v754HaHTtydB16I7wG2z",
	"1zCs/h3t3EzfXEZ6YRG6ueFphD5c/fz6IjBh+IKzh9zjxZLPeg/lOaaifSS1cOzRkF5f/n/UCFANHSmO",
	"csqA5WalB1bxfXQ2R1rjUSSJEDYfxDzLONOfzLhaelunxa4kRissHSoxTtN1cFPDN+i1JGIvIXOq7zjA",
	"rXRq5HqhIe5ou0kb22+cSZWA6bqaA87U4CPY0EzhDR52lAb3maREkXd4RtK3KZ9pcvY8Uc3nRilvCxoQ",
	"R1rY3kwlUkus0BInsOOpnhsJkvGV7/T3LjAYEaBG+THMd4dle5YOkpSIuslDS38tFc2wIheYLUiHy57Y",
	"MUZmZnQhsLZq0NHVK71YvVPmqvOoNCNSnWAZOtLWHd2QEh8nT55nzw7lx0lQPJAveQfVu+f7MXv2U9d8",
	"d1xsjuBP2dGT8IQhl98b6xTWCnPIM05/ev6O3xHhHgzqWMBPaMYLlmgi//T8T77XTzOOWIHvc8TtqEFd",
	"53kXKPhpS6Acr5wTcXT1asjnXue+r2AFjX4/iSb6OtxoeEI3+4BuMrr3cUziLE9Jz6OvVElCVvd9PPLf",
	"ijxIn3rYkohSKMpOX4BnKQ3tZch99LUXvr5Vu4M89CoUSS4KJvtEbTmweluVQQE73kuliQmuKtLrqQpf",
	"/9WtD8+qTsusrvwdbSnuyZzEWhFNEBdwke+5a/1+D6+v1orIK228BIS4/mc00yO0SlHkYCAkBUg3/TG2",
	"Am8nFwS0x9pv+k9AjZojtPtJtUTnGgCFZDb8bBEhCZIczbEIYDQO4Jg3XFhAG5FzIva87b6jakkZwt52",
	"iYJ5L1M5Ma4Vs0psvTGiYMz5Hy03lv5HrW0ybRaOjdAJnQ/9X3Jewu4e4iHVOeiixLZzyIm3jM5Br+36",
	"umcpFz72EV0zavjAGx6ujjjKU8xYUJfqEY0jntENo0QNAeTj1i9Um7731hNfDKFp8Tr4RII056cpSUEI",
	"SbRj3yrRUYSknhQk627wGDxQVjdjYxpKEZW3SNK/a30AvX0Fcs2TaSWah7v9oSq9srya0N9oIoxELoE8",
	"D8MAio0OnKrbduayPzMfHg1EURlAg2wQvNdKJDvkUC74QhApK1nMWbo295IVM7u+Z6JvicGbNuC86JCN",
	"l0SsaEz2UrIiqRGQ++iDxkbdcfN3icgXKhX6r3//3wieadAOTVKyqy81iy3a8XaVlevb3Ue/6DX5onZO",
	"GZVLIvXXVCInNyO4QKXBxjpn4SIDiPuedHYvRU4ebypwfSFppwr/6OYPvbyETUzw+Q9EsLVNL6lwlpvN",
	"1zQwby7aBrTf1XTy3rC3e7/ptL3R499h8tvFgRmOTi/fab4lX0A7nbyY2JfXj8Xh4VPyEv3l7SvwVdmo",
	"CvQS/ZALnvzQHSDXsGEY/VvhKFS5+dDO9fXZaU1xKQqajPeVBN9q2q8VeXKvbUyx1hPNxyP3sjN8svf5",
	"BpbRH3oLWI2Xn4ahA9IkxyFHggvI1r8ia8SEhfiispJCKgArbws9NKzqqz49uJrArnhQg6jGwbx2iT6u",
	"nSQfIPdoIlO2IkxxsR764qwc+N9qK26mEmVYxUt9Y5Rn5AeJLE9HDwyTvqFCFTidYg2BDMZJm80xIDbd",
	"dq34vSfqjovb0Nu6vsQCOhDOiHtzY+bj8s2CSZoQQxQ9N/pwGRSKeeBV6BzhJAF1AktJF4wk+t40kcha",
	"AZzjOCjPMhwI350en3jTIUkIQ7P1IGKsokVjzXad4IEGv2bOhTbkR0xq3kbcA3nXzGYUSmEY2pHFjBGF",
	"MixBFTk5O71AjCvQM5u27dMnYbnQ2u+fqVR8IXBm0Mi1ugB+SvMQ2th+rHCNZ7seMitxmlF2g9OCdHmN",
	"SB76pZmt4SaxX0QGkxD//syDdktenHBBerX3k/NrFMOgzvdg31rJi0se3xI1OKe0w8bM2qMaeEpB+dwB",
	"LpwQ/4NyMn3VnkyTx0WNUYamr0IuimE8u5/Dx75Xl6/Q3W/KZ2wucGAvjYolz40H0JiCG3JlnBcfVkSc",
	"8CyjKiOhO0JvnR4Tl2PQhT5q++ikFp4K0hUdpymHgwPhqhIdIHNFnLtnzhPLWSMcsdVz2ebWYGixmkvO",
	"+Z0xAewjUJJQozSf12jbSblqV/Rs4xGD49iBk95BG1ccFj6biBlg6aE9vTieOua/z9baT93e2r/iFabm",
	"uIzaXXufjCehu4wDqzbRHvY8hGnYodJUJ6eLwHrUz26vg9rL1ravGcpSgW4zr0fA2kkJCxCb4tDlzejw",
	"HJTfIedNe5iF3sCjZqAHfyvt82iySpLbDWJgk+TWO9FfN7Dwz3wVPSxx+yTHKKVec13LnJ9McQ4vIdZ0",
	"BrIZPY9QgUrTwT3UtjBfVVfARljY7z6HLt2zU6fO2ni9YJienWBFhAx6Jm7MD42pEM7pPnrDBbLuBPRx",
	"8pf9w/2n+4cfJ4MWs4d1VO1M746eWrUtuKt+nk4f+ZppPV9L6I2kkBGT+F+AdWgv+v7t04PGb/eN3bfK",
	"0uodPZVtSoP1ZJAL0XdqIgk4O5OyCEVaSEmkdDdRi3vi7sfUjozUMsain0PMsMiH76CFltFt7K3kHVXx",
	"crPUYBcI5USmVJglWNh8b5e/pf/mpo8mBbPxex1Z66sUs47g0lUmO1+lwyGSncm6oQy6drKAn4cVCs61",
	"wbh+jO4SrwiSxXxOYwqeC0FXNCU1n4MX3ppRKSlbnFej2r5t8/wao9VlDtGt1ZQm0AYLguw8GwQCNgjm",
	"1hoi1jmmoo9O/fGebwiWdJaSMtzTpPLKyrQxb1175oHLxXU9Umxnf+TDVjJsH/aoN5hzWd+NxwqH+F28",
	"UV3QxVJJ+nfKFvY26fcL+8rLKKzbABrXVZN9jOMnqEZcQTi+/hmdnVYxzOA8x4uFIAswLOaCZ4MXfwVm",
	"4N5vL2CQOg+myfejwUgS9GeumjFB9J2EnfILMneanJ30hGd5oXV5m4sMoXbo4yThGaZsLz568vTjZDcY",
	"2upAhp9tTr0HGwfT6ccNV6NTKh3sXPCkgFIme/aLThR68nUvr6c7xpPxn//hRdP9aRcdoPK33f1Gcm5S",
	"y/LdOfyvf/9fR4eH6E+7++hMI5kLomrJijEuFOWFdE/EKb/b/8hGRgV2ZfDWcTejGojDi2+JNu5I+d35",
	"0+54VIJZo784ELLIMizW8NhAxN7NFGX4i4mKl2hHEoJsOiVivBGp1A82mCZao8AKEjFbO9eDmkbDoqbp",
	"xLhCGGmb3vHg3h1NCAzbuVvSeInueJEmyJ5UpGhG9nBqHPYmnk/ujt7XhMrb8JJywVdUG1Qk+ddXeml6",
	"aLmw2q8dOwxFO+61xZ3pyQ3QU0DMjg7hNu3CLZDLuxF2GzOggbcFPuxMVx6G7rHafaGDu+izR+HPcV6E",
	"dOYi0/BXxs9fMCURjgWXEuE0hRc8m97QqozQdIvVgGmW+nw764TnjTXst6O5cwjyvdZtaPo5G4fMxfEU",
	"7UxH4BJy/n2Owy+r9RyCO6qWNYaGCwIAhCpQdBlu3vXcuDg9VKIHpaaD0KldiZ2M1U/5PhYZ0lRMjnSn",
	"9j7DKl5+lvTv9YolPz6LejchJwL9vwUR63Mi5kjwgiV7StA8HITXowkZDchkcvE5wl1akOJIxjwnpnre",
	"ioi1VU48tSgYJbyNCEAA+Nl6fPorpZzN4VKLSjyBXCldEZPOZjU/yHCCCcoQvt0IFdK8aetPcGqCx6zp",
	"bw+QSVsr3Zfm/mtb+y4/oSS5RfnPTw4Pow5ddEk1KGrmN59r3ZoyJEnMWSLRztPDw5cJXkfo6C+Hhy/v",
	"CLmNkJ7yZcaZWoYjEFPOb2c4vv285IWQTWyiVoaHGY3uKEv4nYYO31WBjn9+coheoqeHKMFrGQapT/Hn",
	"gZAsTeKZ1YVlMSs97f2mgs9MAwdvSpSgcUeei72eRyZRpFjZszvm3jQ39pjcDHO7jhr508iRRjH7HI/0",
	"ntWGRyVZDG4GrllRSYQBql+AEbOZMTbGCAPZ4xc6snUstD4FZRnQS7jrnA3dJYq0VfoZb1Cbz+V4fW5S",
	"tmUPc0Eg7RHZKixOSS7TLeyR2nEnEh2UB70jQDkUOHBdvWIYizEYeFOXP4HLvvK3dxdH8JJFaiQPPptk",
	"93LG3EwtxwRcMIZenwlLxm+X/UYqLEZvcih60dEnqusptelrGNZp3sU3LnrL48RRB6rfG2b4IJSvR6XS",
	"zGI9NUZhp0Tuo2tJ0NvXV+hAVKAOfqPJV9jveQFqI8pAhkJu9qYba/C+NCZC5zP3cBCevX7dEgfVSm8g",
	"ABhFXodmO7agGumImBGFjauLqiUvlE+nHrJCaLgSlKyMigEktlNSFqdFomF4BP9Dfv5fJT//IYXdeDFX",
	"3gPtSuHmSNw3TKFDIwwFQWV8s6LB0eQOC0bZIhQtyNmeOVdlhP3NFLzjfyuIoCRBs8Jk4jPua/52tWBT",
	"79//kc/Vb+KwPY6EHsKh7biGmP8/6nBtrw6Xh+zvsBBXGDtbiauDO3oCiqAofKPGcVdey31SB5qSq/wl",
	"KkF3czXU0biZdieV4yRwWUDJDI5w4hfMgNpgI8/lPfYioSsSlQs1q85s1awgduZnD0H76PbtUAyxi4vU",
	"GVeYvX0rhbbyZnpapirUJ72lLPRIuc7BqbUyiRYuecHWzogTwbMIzVOe5+sIFXIWIUkExWlUZryOrKpx",
	"Mz217xsN517IZf2qkLZwkMFDxpJGiCYkQhIrHCG2ysKVzl2JoI5MWPczoswk1o/LVJ/TNJSEjtXSxuuh",
	"m+npvyI9zHnBEj+woYnlLVl3xrvfkrWLeV+brBoqjQPdZrkDuHpezIgciK7eFUAWqOtsaZ0TIalUhKkI",
	"UZaQnDCNzeeuf2ecVT8F90QkWXfYkElqkQijC3yHDPOiKc5zyEFNqCCxQu+u3yMcx0T6SrfnS5RLLPpi",
	"kyoaUonMYDQj6o4QhrIiVTRPwaM5sij0zdRcmuYyl+PbYrRIryiLFUqIspWhqvEmHHSjYmZxLSA6CKkW",
	"a7rZ5JzFRLATrMiCi2BwUwXFjEVxNfgeoOA+GgMmNQM3AZHUw8C79qUctTHBwi85LnbbgW6uNUTmaLjn",
	"yc20IxLTbsA6lCS+IkILQjfEGXxUz7SPrtkt43f+FprQOpznJhnthw/6ZP3gp3GfCArW6SSa/GKUaIjz",
	"NqLJaLjHyYpKo5C4MhQwz8iAcrtQS521B7DxSwW/8UMdncaPHnaNXxyyjX+2uA8lapvakCTx1f0avc2D",
	"YWW7adZW5Isy7TVIzLOMsKRZJCcQINvY5CUXymo85peZy9MEsIOmr4uoLfmovtAwLxpe7gm9gjfoUU+o",
	"BMdLi/8OVE/kIjGRQObMm+KJtQT1X59HT6Mnn7yTGqjx3ZNQkw5JHQvZlANRKagShSQ1HLxgJFOaZGHL",
	"zDiGreHXa7jkWCkiNAYfP15Oog3lTlrJFSB6eMfen50ElFCWkC+hHJGEfHHM+/7spFcrCfib8tWzY5OM",
	"Gsp7XT0rU1Vd7VMNoxH6dTO908LoivNUhnNqVz/2AflxG0AGc21d8oPVrDWRN0mzvSBzIqCSm1UxXX5x",
	"iTA4zFzHtlA55rDu4hyerwTBtwm/C8QFLv3k2N40t3Kg767uCB95w4VJHTA5luPG/ULV8hfPh9T9zXuu",
	"+qcPpVtNgrgNItIFNXy+OuukfaFqXTZ3sVfHfTx4rgLQFSXCe09oSzAHyEnZ2drVheQMVTghqB0TIcIE",
	"jZckMdLYpAUmZUWhnAgzcB9dFtoGIAkBNbsE82p9Us65H0ph8vOT+9NU2lxrQ+YqCHr135yCNohIf7/n",
	"EVBBrWLwbtu0eFthEVoNsgVltk3FFX0VoaPDvSfmT08O956bPz0//Ocr+mq3Fj5REc6s3L4T3JNyb189",
	"4GNHrC0TPLjQq3VO5EMA6QkGgAR5drOU4XYm6AMPINo5fHldpQhF6OjlayzXEXryckoSWmQRevryZyyS",
	"CD17+cuSKvI25bUWcJ1LzIuhzQutb+RhODm/hgOAZgWUAKhKsR7uPfs40X94vvcX84ef9o5+NH86+vPe",
	"0yfmj0+f/HOtXGvXMqYQfvaIKzEAhhcTWsPTvR/t7z8+3zt6Ytd79OSnvSfP7fAnz38ct9D3NC5P+zaX",
	"OVuDJgHaobcwi6pF0q7H/O9ZF8IlG/u39agn8UY+YahMu7f8e8gr5t/RFwTLTbqUDmPH5UPlRIuYXGpD",
	"9b4iz34dknT51uohCJzd+wIZ0hRHqYkb64h62CU4/06pvJUjC4GvCMIKpQRLhTgjzn1oA2c30TFrCmap",
	"+ThKlneyf7nXN6yDk0NnL6iItmNHAx6jmIhA8MH56+keYTFPSIJOjpEeROdUMzGaFSxJTS36FRGl17pK",
	"+756d+l/sI+mhbaI0jUiX+K0kHRlHSDyluZXaaDPweYPMLATOZbyjov6e1v5j4/Sqwfg2nUE/dHMxt42",
	"iGJI53y/VAItcpJoYkkFqSgzgiRRYA2KgiCccraAElNmzyC5Ang25tmMMjOTK7v47PDQVm60PQteIDp3",
	"X1KJsGk/AQHwXs/tW5pLQLWG3s4Mx7d3WCQSVBasqMm/3P2X+qQQC645pjGtmYyYmQtp+EUj7tFDr8bS",
	"ETFCkooETO0HHwGGGhnVigkKOnn4jmuIXxtNjx6Hp4ZaF5VM/Umf83oxjPaT21qF3PfVbmExw2m6yQNZ",
	"lgSyYLLkOZIm/0IzQFk22s4fDJHsqihxtSRVoTkXDn6SQlq5+2iwgkQ5TqMblJBmhLt7G5X/qDI1dgIB",
	"CdT0/qAKXf58bMw+xdGsoGlS6wbfrkBJ346e1tLx+mwTAJ0UhbbxjnY2UWH1ZP9w/3B3A0pWRKmvJUjd",
	"unuwLye3UZLKe7UKVkmtlcNqd6Lx3nD6eot3RVomfg3lcOWw9omoynK2KwbKqoql8eZBWqSKlxs+lIWC",
	"9+pEttkRPbVcbDtkytmJfXoaSnCqvnAvcBLeKETi1c03ofDlY3LifyWILFIVdg+Xo6rSRb36ZXbW/ELP",
	"Am80g+vQoySaQ/+MMgRxhA+764mg1p/HPhNU804nj+Tzv290SjOiyRUTC3i1jRW86RHIalp842RpFYZa",
	"D3mmlYVqNBBtenWzj95A9hFXSyLuqCQdVUOs7vtaK5PJJq2i3dmj0miiiWvoVc4ZhBgOSmscvM4+SiTL",
	"02D1rTZJMHKjx5HCyzj8PKIpddkqBnQtLywVHaBguCr6z/9AmldGpWnWkOnKE29mnmMFebk7f9r9F6eS",
	"QnAo4610yvthEUzXDWABOd6PgkU4zfs0kKD9CMC72zy3k7AfdS86U6fDiGx3O+x1eBmugudMBtNaxEVF",
	"aTOcJB9Y9cf5PEKykBAHFe7+ssqmvKsyCBd0QRlOS2V2+uHs1L8u9tGlkYbWFVnFxpvqBCYRk0J8Y8yF",
	"IFpOmJL7tT6DN9My1Cmhc3hTVH5ug2Q4l0uuQu0FwyHTJiDep2FVlKSmjHmqVXm51G7nYS2xs61ml674",
	"PlA5JOZMYcqcX6Lriq9VCGGVUhEqEwK84cBUlq2jdFnxjiUBkD+YCrZop3y+tbm45d+4yJeYmT8hykzs",
	"G52lHUGPXBB5ToQpzDuq1i883rmnaVOpd1wUYZwXx/M5ZcEYS5dMVTKfhnd2KgM0AP8AZba0teZ7rdMl",
	"Rdqo3DUCpUCR25H1zx0BoGQILuudupjOewRZ9pkiPmt6oWUbc2fS1THVkR+0hEZIb9X2t3N54yqyuwDj",
	"UFRd2K3q0CoR0sO2h46+TwPIgAJ4xVMiMIvJ66HydTbc4w0kcJefgWpoPo2QKfmSYQr7pdUzyJmXS5zw",
	"uyZ7z+HgSoWZQnNMU77y7S9PaZtTkWnQocwM84sJhfbfkhuwdmaUQ/cVMqdBATHnaRLiyFaMSVV01Hyy",
	"OXNC9fezYKIArKVVzrsqGF8L+RZLkv7l84/PoC7/biek90Fd/E2RprUaUgYEN4UO2QLJtVQk2zTkZ+H1",
	"CJDd5etBs164bpSBPgADcMf18fD7FXQUmh6x4VXbO9ctPCSoq0ZpwW564U34mUvV3oPB1W/SNibATE3k",
	"Rzo/NnE0XID/wnga8s44s3NBofSP18zhoYQAh0W3fLUODdM/tkwduK9c7Xzu/Ad3f4S6BxxnYP7yeVn7",
	"vF9X0GyXkQUOedC7sjN6nCWVv6IFKMZa6bQOC5KgHWW9CIwjF21qGWP3d+0+CVX+G75tGJGKJD/fDF7v",
	"ZqBTQZzJ6N/uekvv9KlZrnMiIBDc5I4VNRnehZO/QJuL268FuXDOsqELiuFFbVt60fuzk2DN1/I9uafD",
	"EPQwlr6N09Q4Ouxhrcb3msS2G/21DG2WUc9dY3yZA1E4k0XWqfpslsfV7XzrOWI1RxwS2I7DDGEkyKJI",
	"sRjDFUqLdVvhvnJu9yqjcBNAmG8ZbO6689mI675eOwCwC9KZVk3T1DXM1oNM3IMHeAdmeM+VHQwt/ew/",
	"2YXYf/iQup8+3Aa3vRhfKv0m80qWGvMfrlrIkw0pAisiJEQTFC2loOyeVNUL3agzm3dY2k4Bz9BsmeDe",
	"ZeLMIisXhl0e/YVM/hv3Bvs+PcHu0QusDsFkR3dmRW+iDu0Ikqc4dv03NWHML7s96SOPnjRyXw2KcTVL",
	"MbsNqVJhrSIocbnTHkqFoqVElKSphcs54Xqv6KBgboSn5NvX0JAJZTu8Gq+WVKKIVSFMFnW2V6K9Z7I6",
	"6YqglM4EhsZTrZfTdhUbL2XvPnle9dRh4gCFu2VB8/ThXHM3sJYIZnD5NEBGZysNvlM3n4cDlHEkGy0o",
	"AtsZkha9C+hqoTO+Lf1wR3pvI0Ju5sRegqHU6i7yBunZWqjs1wM9fm02BKoaqoebqJfN010/9ZEJni3K",
	"N1qodwyoeqN3DPA7o3cNqVDuGGGyQDt6C1XbGD4TAa0m1Gb8+z7adtYWbz2Rulrnm5QK36hIpPdmvFlJ",
	"8HuX2j7dfpHs0GvmppTTk29WXrN65N2siPWY0V0FoIbrUFevUKZEu1+Tue4nCuitYwpPn4cqTo+j8chq",
	"0ueBMtJdhaI7KmI1r1ZTfsqND9CxC7kwUYaqQXvHcKg0tMd3oTrRnzqStZpJXS0hB6o4jHo1KuLu6lXF",
	"HoqOrRK+yk7GVOp2NbntxGPC+S3qFYhPPWlrj0IF+MF2ddoeKTryHQCYy5O2QAfI5ABGtVV+6s1zCdQI",
	"6GidW3bMqn72Y6DyhcAJuagVTQhp8fZ3kqAPl8h+5SLPkNeYCx6mIDrduFrtUPDPYeQPGy7NbKkSavrl",
	"aPLV9IUDmiiqoOf+sbRBlGUuEjLRu8fnZxMvxHeyOgKi5oThnE5eTJ7uH+4/BXNXLYGuByZO+MVvk4UJ",
	"FOCu99dZMnkxeUsUTGyVXtAvwQ8BHz85PLRKirKTeJVJDv5NGjob7XtIN/fBwJpDwcmyjOh8bkA3dVxt",
	"5OIUSSJWRFj9GhIw3KnTKzKx0d5kuX0aq6/90q59yhMyMftGpHrFk/V2F63nd86ERmC/tm6/fj+ia8xQ",
	"vMRsQRJNp2dhokNVQCTcEvS4nwIKI2fzlJpTfu/dOwFk7AZC/Sr9+0GzrFInL/vjHpOu1Zc1512Axu4V",
	"wF+CSX4qXWXQkvEBRAMQoZJS5Tsu4gy5xo8Hrp6pV47Xo2k7V7FF5XegI7Q7T4HqggXOiCmz9GtH5cnT",
	"y3e16pO2n1NVZxW9RD94LRR++DjZ3UcfMqpsxeBCsFphXigKqgH8rSDgqjCq2GS2fl2C0VK43Nt2acum",
	"HP/0iNwz0NgtwEQuH6JmVriOYtIcyWehgquoNNGRaJdthkj4B0tb1yrJZLCHUWymCXho2VLnHZx58FvZ",
	"Ce3rZlzaKmg9lksD9a2vr89OHY/pq7ViMb9PW12u+/zW0hL+OBnf92QYjoAUw298CDCSrqVpgPXlwW/V",
	"Zn89aLyidV17gc5/Azxe7/UX7uaHuEALwoiJM3ChtWenTbbcw0/nf549iY+SZ+QvPx0ePTH1AgKHpVZJ",
	"u/u0VI8Z/2PHofTxY/LP/9MB/PVw7ye8N//029GPX3f/afK9eXRT/oRK+fDkEZaILfkzqJt5AsKahw+6",
	"EuBZv6wc6c6INkorfB50WtyaA8SZrT1Ws2fDxK4777vGPaDNK56flANb+/8spLBWIfGK5zl5mBTQCPj1",
	"7L9G3efV4fn4ZlcTVIhF3ZBtmV9xYMIOE0xhoeq7tn0jzCeBUBtZYk++wz7YxxfwFjzcJiundK27KEO5",
	"4AsIYXwYu2Po0uHCh33Oh0NbLzpRHdvmRZzxFTE9+WxbE5dK4TcWL6Wllp0zLIlWbOq8dAoQ/FoXo4SA",
	"B8Tg+DApYLAI9Eb35EGTAqZgQ+uTqqvKzvXFO8RZut7dR+/JyhTv55JAvTFhAugEciUB9tHVEuLckpxT",
	"plDCiQQpLoir71+jLV5gyqQqu8BNAsp0L1m3KK1KMD3HpCJQJV467zpvnYbAD5Zu7X3ypFwR2OAbS3TZ",
	"R/UIERaLda6scwDKy2lGT9AtWUeQVwSQZb3rnjsPCJvoBGwCEHzsiNpHx9BPTksLptD59RXiKyLuBFXE",
	"fJYLsrLtidus2+aI86LFEduX26HOh9/WfbYZO8qqfUa1XcBvTw6PvhtOtt1MA6N+bdL7nAtUMEFwvITU",
	"RBdT90BFSZCQlG9dHAex6/TvKnKEBOjJksS3skyrzAVd0ZQsnL2VpqhkXol2SuUkctEO+o9zLkiMtda5",
	"a+vTBI4BuqRskRKTBOTAxRp6BNHXENmyGJCfJ/6SHpN3HZx1D5+UY1xEaE5ERa1vKFhhD0ualhigGgMA",
	"e+ibT6hOZngNP0skSWrcoXCBQqcvqWXkyeUNdG2QKMfxLV6YLqYY/f9n5wiLeElXBIqbmlnmKflCNd+b",
	"Nq9mUo2X5iw+n6eUEYQZTteSgmB+/SUmKVhPhVRaZeE8JD8Nlmdet5Zea/2EZxnek0QP0mtKrU/ZLgsC",
	"6sB6cw1JX4B8X1Fyt7uPjleYprhchax+jCARSEaluyiquljICK0yGbmo9cg30iIXsr3nzk1UcztHttZJ",
	"5AUU+UF9kxIBA99EbIb8VIDxpM+Vtpmp/3ea149Q+Zo6owwD5CaA1qnxWMXPlqs4SzOHvRBJYonuCd3R",
	"x7sj/qwiI7UCG0C8QIUp4T+mLHR7VWf+XKaYRXWgH4ryvfAZlhrmGEFGSmmH6HuuKrCap9g8gECtABAg",
	"lajvs0u0NW9UI/eEMiMsXmZY3O6jY2NL7XmelIKZfgkQKipWVXPkboNFg3hTIfOIxmcFpfsueOWWh1wk",
	"H3T+ge4sxrFsXsBh5X03Q0knP4/wQXcD4FPNO2hJ2eSJEn0TjwlqdU7EXo6pKG1gF2sZvLVbdHvE+3rM",
	"HrkwzYqFS9ujRrFznqahQZUbphV1qm87LNcsruismR7uOQbmZaa1tvJ6QJqKch/VVE0TL6HtUOB/uB31",
	"BKYAIaJz384oq8/p+5chgkVKSSk4Q8cFC9U4L9s3Omrb8N28RZsd2LHeIk9ni5ytAtXJ9aGLjAuBCpTS",
	"jCpEvsSEJG7WgG/pmJmqA7Xz7rxM2zj3xsPkHfu69G4ZB2Hetk1fpU3m10obxwnKiFryxMjsOcFQasMU",
	"pXCvM6aK7Z7CYkFUk/GRMc2htCVLIAkOVMbSzMILYnqVIMVznvLFGiVE0JXLmIT0GC5uUzpXe9YmgbPg",
	"muij97yyMXy/gSDIMWLAMOfSOyPnmIqWvbH9M1MDs37EUJdRSQB1bALx/91mELVlUvQWd56m05ITtvN6",
	"aBnUnL22veMzfKOOb7+zqTSwbRbbSpt5mj3LYqxQo1MSgZbWeeR2q8uW9q4U36Suzgb0w8swwwuSQd+4",
	"m2kV9QvZgxBcGKfwt919dONXmeUsXUOUe5PfNaElXgUZvvD4/XfukxpwHMHmYOiAbbfBI78mw0Jgprbm",
	"v3l2+HTb1ogs5nMamxKtLQ6KUEalpGzxAv1anqH9Y5tXfwm5v/Ucof3SQN4/AS/Wp2AujZn1vARUw+rX",
	"SQesSTPrrwWtln433IVp0KI5LtRSb4vldlnE5oaFrsdwDlMc38rQ9j9IwMAZWwefVTTH5UQACTlrS5zK",
	"G9B9wTqtuxo77oazFcDtXWmvUY1QXHmlaNW8rX59vj8+dp1Lq+xfec9Ls6bpn1ZLfmwNswLl3Znf5I4s",
	"IdtqayMuSRfH6LHEg2MWcemZ8mdt8CDoWwe/MZyRr30WuzETzUVW6aSNkBu4ZGem6MQ+ujIs6u40TWPK",
	"ClKFTVJXWssofZqNpKJpap9Zhmx6rYoM+fb0GFMDA0uHZ+U9ANW+fOYNBtXYNJLxwWefHmi4NNPTqXjf",
	"1Qu+TDd0WYRlluCnezmpzo2OZOcY5YQQrm6BM2+qeJaD0lyZU0bl8qE+bOOnwEiaZwKjRTa4WRSs+yXD",
	"iVLKErqiSYFT37pSTuPaR66pfLq2Ofam4kHueGlAxl0UbGysLji2/Kk7HLUlG2zPV3tP2VbaxRcF20Sw",
	"1VhmC8KtOV+AEQ5+s1GtXUFNJpqgtnGD0asFQ13BqgNxd4P1VAIbGIqtLJgfStEfwGKw7QzTLNiWrCwb",
	"l4Hr29LaFS2whs9nbEy2BBxrVCoau9jOupvgB+mDM1nZ+8jVCSsDNFxs9PUZUlxbSFAXqXJiK5qV3eTI",
	"GE+lHH/pKI4WRDUWMnzGH3LbbN9natYcONtXS8GLxTIv/BV2MuXUWBLIrROVNHxw0IgKI6K5r+obEAwX",
	"1LLkrRkyTmLbNgNWyUE7MZZkjzJJmKQQGyKLmdkdk4Gy2xkiPijPozZfldVo0M7RHnSUNXWhwvy0qM9f",
	"ViE7iqomvkeh7MPuxEa7fOPGWZAe0LZMcQD8k8NokuEvFr6tttKNzWOyOGz92Bwjy0pDQteoDF6iwRY0",
	"+TT1oIeDPY1VDQt6rEjPCsJGXsij7W5XaIvgBxeMMzau05VGpfWNk2um8JfdhymrgAnCiJE7s3O+NBqp",
	"mLi97BVLZuUPVUmgGNiYQP+AFmEw2GJ0p6VXd4D39ydMS0JeQnQ/JWlSRhgKG8xStoHUoF9gGX+caGup",
	"TPB4oWeKqh9399GN5UeYDly0OCMR8mvEl1ElxumrpW1kq2lGtkBlhOK8uJZ4QcwY+0eBM/unOC+OVwv4",
	"7HgFkVWeY89hh2VsyQaIatOSfMlTnpTlo4KRJVyomvQf34VHqjU4PPUeTPovwTlYnQvbnO1b3oOwnHtd",
	"g9/3ruu759xBhhd7w8U2d/ZZ97nfXo4XHHutWJ2dGuBUSYdArlWptiwwpeR+J3Jy+xeut7zvlOE+cOEW",
	"gOAWL9xHZzRDUv9KLsNUh9Kfzvxgu0ej+JlDpzs04WYqkYDEDuuu/1tBTGnp4CYcV6kpxrdn4m+xIp0U",
	"L5EwiQ1biTbgeRURjAhTVJB03XfLNykxcMDP5rYTKGWm+mHZH/Hm9PRfvWyPv9r6Hn+N0F+z5Plfd01Z",
	"OVuFcN+Pp4Ev77BEDNJC3Ixdab8W8k2S3IYvHFv+uVll5VHF/giGqrZ7SylqNDBhT4pa42TdT5AGYq7q",
	"TfKck79RGaf+6r/p63Q0WWVnidxEw2kV99HfhwvXfLuQqPFcss0Euorxth/Z5O29VhPL+hwlb7YCPoIM",
	"6iI+SlT/20ZB2MvavIxLOS/SdN25g69wghqMfv8XcpcWF0w9NH1d7BXc2KGVlqQ9mfnlpmiR+/hBpI1G",
	"wIEz4lzYUCnW1ZAuv2h17rXlweGaUVjsf2Rntjy8/hebQgHxQ6ZbM2HltxHC6NnhM+QWC+HANpB4/2N3",
	"colewxaVdkC0laHXCiKqbVTvscmKVNEcC3Wgle49CCzveR+d01CDB0dQ2xZ5OAuhLpJh0vtJ5G/JbNfA",
	"Ct557j3NmxSYenb0NNQ+KSU2blWiH59NX5lQ1geq47CE2n5ZGeCSd3qP/8gMn5ZuWLZ4PitjAcqDtHNi",
	"e7CnxFWSYgVOvdAacwZ3u9RA/dGxmXwzNbCrbk0FWfFmGXgqjTHzgww4nsP4wXhTJeTxHpY4Ix/msBX9",
	"aofbQb34YVvYG/+pO8ffj4PqsXEcUbU0LGNltlWeoY6DZulwQbD2c1SrstKj3mktaGNfQ9rVTeR2Hjo6",
	"Jg6rZ1eCLhZE+FVjqkoJj6OetWF9pzSG1ta54qj91S+UIRlJ/sUqDHJsHRzvCrn3NtsNq+1yRpSgsWwV",
	"uRguVDZclmwwoONxSpB9+pZHNqiJdpQ5+hbVuvwiXO0aSHCnausD2vSbre/d77J612Zi84+CdH8UpPvd",
	"FqQbYvVaobqNBN5J2Tn6d8f1f5TF+85l8Uafj0cvUedj1jgmDiw8bXQcn7JEd/fBuLFDHtNENyCg5Hro",
	"ncb87KdZdFbTXnWMPbCdvDpXOR0buDZb164aMCEJPLCaG9nUKbJJw9XIWietCfmSH23/ivlHjKaI0Cqb",
	"cpr8EVXxjx1V0dNrsMd4LuMqRjyae4f7wYVBK/BWDQfZoHUAyFWrNt3JngMzYo/ng9Xhb6bSiJoP+aNX",
	"iL+Z1kD1kdyKP7eAh5IwgT6DsXLeNjMvWuG0sBpf+dKkyVd1M+wm2zsz5lHJZWCMYc1ygRb1BxuDadqc",
	"U+sRhSQIx4JLGSLYwW/w/xFBkrCwtymf4TQd9ANfQUHgGUmN+ZTxFbFqBlijMqxAms58fbrjg7pHPqp4",
	"ChCplwmAOC64ZOHIOiSqDE23E89vg0DNlLXNGYoDA+RHKEQ1Lsh4Qufr77jxjxU25qixeeRYiCW8mnFl",
	"VSb/IRnt2F0qn5mx4hmNNfvsbhYnEDBPPng1cjSMyiLZYdy2WJEowwl5WNj2FJjBMgd4p7RmIpc0Rzs4",
	"SQ6syHDMcwDseTOVu5X8+m3AXoeGbL3s2WyXndwrZPFbCpk6xi7pOWAQ1VeWVM2ow0/V9eHbc964EFc8",
	"44VCGK2yQdnyXbftEUJMejoy31dQ3Ew3CzEZe/hvptuN/TRFU6p3de/gHngFFXs0D1NV+2b6RvCsFrvW",
	"YJDf+altd+V9eLBpMHJUy+7G8YgxMyEtw/nmXWIAWSD2/b7E6978Yba1iSks2gsms3BqbDOykcjNdIMe",
	"Ig00jM/0nvHr35atAp15g4xVd08OXAbveaDJB7CB3+t0m27JmSD4NuF3LQelhgOfwlxm7wqRTl5MDnBO",
	"D1ZHk6+fvv6fAAAA//9+95VlqxwBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
