// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbuNLgq6C039Zn16F8SzL7JV/lhyNnMq4TJa74Mlt7kk1BZEvCMW8DgHI02VTt",
	"Q+wT7pNs4UaCJEBSsuzkzObPjGLi0jc0Go3uxtdRmCV5lkLK2ejF1xELl5Bg+fN0ASmfZhF8gD8KYFz8",
	"LadZDpQTkC2SLALxf0iLZPTiH6MwS1MIOUSjYBQRVv3zUzDi6xxGL0aMU5IuRsHoyzjDORmHWQQLSMfw",
	"hVM85nghB56RNBLNXowo/FEQClGQpZDNX5ZDotr43759C8qmAhIJWTVrNvsnhHz0LVBIXXLMC9bGJ8xS",
	"lsUwUeOSLG03AUozKn5EwEJKctVqVHVBsgWyPzeR/xaMWAlBY5yCUkg50pCgsBpXdwm2pLboNV5hmuJE",
	"YPIPAXIdWUWViTWqp8lZbbIm6TWcLuIbeanjfIXpAjgSH9E8o4gvAWHBpt3hanFdCLSNY+NTN24SgcAh",
	"J05Ry/OYhFh8f0sY/wAsz1IGbZnCVUP5b8IhkT/+jcJ89GL0Xw6rNXqoF+ihNfr7FdAVgTsxqYYCU4rX",
	"oyb4tYl6QC4HbYFb416TmdYIfWtAcKd7ANnC0XOVTLIi5e3O74pkBhRlc3QzZYgWaUrSBeJLwpCFezUk",
	"STksgKoxt6L9zbSX6hqLOjUMCmriHl7cTNtcIFEb/ZspOj8bTuqbqYfCDQSIWCeypQvOV5iHy+s8whxe",
	"fwnjgpEs9e8YZEElSrJpBA4kykGkxgPEM8SAS82A41gwtgJ4lmUx4FTx7zxiHpIwMUghQRwFFYtbZKqx",
	"cfMtKiHpy+MgIisISvK1diYFZ+CghIu4E5zjGYkJX3v3LNNC/7u5o8UxhFxtWV0i/T4HBU41o5h/nlEI",
	"MeOw7QAkZfn2ADRoV2FjD1yDsk3E5hg2vZwkjwsx0q+AeUFdNI0oe53iWWyEd46LmI9ezHHMIGiI3+9L",
	"4Eug6OzDJdo7I0LUZoUwXz4AywoaAroMlxAVMdB9RBgCNbDeBwlDoYLGKfIRlVtWDYrRuyxtapsXIzE9",
	"LniWKL1a22qrGcxm+2sRx2t0qtrLTfICU05w869TnBY4HgVqzk9OMyejeAFnW1DsUnWVlNuMMN/8TL3m",
	"JCZ/YrdpF2bpnESQhg5VeYY5RmG2AglT1RLlQENIufjr3tH4+OhoP0AhjsMiFkRCmKHV5OJ6fAdksRR/",
	"MGMoqU2wYFmUFbNY/CXBX0gieHB8dCQ0RKr+dVQilMr9TSAU5sVnvFo49k8N4+TiGhUVug5AdwFCgr+0",
	"QZiqMR4JhPz5szYIz5/xpZmPxI9BjQSSboYkkGR0/QhQdPLk0aAYxJZHgKap/vW6qWSnEuSKiRUKFUkD",
	"W0E4Nw61O7l1CwWhD04dNuvvS0iVIi77ozvMkO5Swx5zGHPiNopdBmEFEhKAczIntsrsMxCt7hsaioGF",
	"cTetuo9GFU2GW+cWH/pMc3v4DjAz6rO+PO6A19IHkABjQo7vBIfVsVhuZbJPp1PA7MQUcLRWkidPmvJ8",
	"a4Bu/AMlwCkJhW2ZY8pqn6UYqXmHOgdqiKv/ftDQOD9ObBA9LSy4Gy2mCvauJuq/FyVqXXNo74WjwWtF",
	"hA2cFhMpyG9oVuTeY03jSJzgL28hXfDl6MWzo6OtfV9ZIuQ95+sgwV9ePjs6kvI7J7E2xxOSmmmO7+9g",
	"k6cXOYNRBhYaRsvuej6J2bHEzH1q1th6GCN1Go59q7OgcXttriaQcqDo+sNbpXbLYRiaQZylC8Qz1/Is",
	"GFC3njRDli1cPgscuzS0MXdtKDAFJCzn0twFRIEXNIVIQH3gtnlt4gnELYDN7C4qCstWTuaQasJuzyPn",
	"SXlOAcRBLSR8/eaV1cTyqCwxje4whdMwhFgc7iCaZiuwGltnmWXG+LmDPufltoWyuSSFaClUKgV1EIgM",
	"AkK3Ys6xOFCJfaiIY3FmGL3gtAAHR8QpKHZil9OMZ2EWX8kPX73nmvNsIkyCRUHLI0XXxnTp7iU2qYzj",
	"uI+e3AfNCtJI7ULd27P82p6sxc1yxMCIgJ+ZDWIZqjolDWLg8BbPIH4TZzNxnOzwic7nSo/3+Pj4EnO0",
	"xJEUjViMjSgk2UqKQJuGsoXDBV12luMJ86s1ioeoasSgAtiFutw9eqzCYVZep/P1vfyBY7QQ8/X5X6uN",
	"pD7Kr/LvCL7kFJh0xO3lt4tD1RydXb4VFjl8wUkuFtdI2/Afi6OjJ/AS/cebVwinkTmfo5fo33OaRf8+",
	"1GS9TskfBWgMtjFa3yjcCctjvPa6kJU3cAPSd5i6HXuUBKbbxJWYDrdulSi1DFth9C3ArTjEl9Jh7tAr",
	"Qh+4PjVQ1oCaDnpGe3gvBXqwH4wzSVeQ8oyu+3qclw0fhDKbXRfcEMoLHE9xuCQp9B5KFEnUFJsSW5in",
	"74DfZfTWZaWuiMu5pTsg9V0uGURSRiKQWnUhbV7X8s0d+/UFwlEkFIerR4JDh2vidGL6IMwQA0jRbN09",
	"dVrh6MZFIjGnWdI9Tk5hTkor1zeYaoVi2QztTc7PPtS8EiTlT04c+43LE/kbYTxbUJyo6XIKoTzmayul",
	"wTHMcU3MfFZBpQYSkt7guPAIPOOQD1jq5SC6R6AgcYncb5nrQBTmxSSjjsORtX1PLq5RKBt5jTUL8jAv",
	"LrPwFnjvmEw3GzJqxw5U7T2V01nYnk65lnvg9FV7MEEe4+YiKZq+asjNL08Hwem3VYcaf6VJ5zfQztM5",
	"xQ5eqp2cXQAVh4VQnnU2lMowL96vgE6yJCE8AdfdrWCdaBOWbdAHYSAfoEnNny4VIjqN40wuHOlfZ+gQ",
	"Xcm/XyzXjIQ4RhMtWW3XYctdWZ4ghqv06tTkQFZIyUV2B9LxoM3ZKCLKNruo0dZLuYorYrThgMnl6IFJ",
	"cFBfhLiVzyZqRop0H08/nE6N8G/DWt3V8Fb/E68wUctlEHf1VjGchGb/dGCtjk56Pbhp6LEiqpXDOmyN",
	"3wyvnQbHztjXPBdWU7eF1yJgbaW4FYi8ky0Dhe7rL4Vedyn4Q6hICYway7rgzEF5o4KRDhGRnlJxnlGe",
	"wxCn4pS7qdO0ib6k4EU5l/PzhxIA5+eJBZW7QQWq83uHvxO6eOh3eXvIXvZrUds4sQ2tNyKm7b0F44B2",
	"fjOji7USRbe9RnkU3Vq6eBMCWWeQRkzO0OOJCpexDinN02X5pROCM20eOvdrO4Ch87qk0Vzs1s7b8gGD",
	"2D3kcU0bFN1HNdFIcK2yLDoZp5yt1iGss/W0zVt1sFLAOenLWAHsFQV8G2V3jts8HK0I02zuck7dEb5E",
	"mKMYMOMoSwGd6p6IiDmcLqqQEi4smM0Hn+ieHYN79G/fyEo/+4clqdqInV6pvsHPq84dU9xhKtf3xsP/",
	"rjp6h25eCRryV1PW8Qsq9re3h0qIpia+S0qTQ4YYA8aM2dTa3EK/V4K4XfKla3Ogv7Ka38zmQsPvTFix",
	"O8LDpRMW45nzRNhVF5yM4zTCVIf1mugo8S8zfDAqUlbkeUad4b5CC8Q49VxTrBLmde+4nePeMEdXfFrb",
	"vLGjnFzXPPpax77tWeIVIFbM5yQkwm7JKVmRGBbgjnNMCGMkXVxUrVqTXeYQkjkJ0eoyl/ck1ZDKv40p",
	"ID3O8HjIJsEMri5iXdAsBOYwHtwu23c4AXO9k+uuLkYDZU4Nc6M+9A7humJ0gf+BLJackT9JutAbW0eE",
	"QmWRd+1D7SEbeyUFIeKfnYu7AXfVtNyqB6LRHf+m2nz26Bfz2bu26/FzA05mVgzbwNY6tGlgax2CNMQD",
	"QNjtwKZWnNfA1sOBtuKmBrSWx7bPOc1WREg/RJ/DvOg6XdbaCpQ/3862nksdxj8nM99x9XM4UPNacteQ",
	"MmuY4F6RW5K/NQn1kq8b1y5KupbgJceUVwczbwCJP3p9mn2AuYlh12faHySI3Y2w72a8FWy7ACa+XS0p",
	"sGUW12ODnxw1A4PfYg5puEbctEckRQmJY8IgzNKIoRmsszRCd0sSLuVGoK/pkaQFIkymVZEI5BasAJDG",
	"hieY8JnTPG8D3g7CNrHWYSsSe2pCr6txLIxM5LCyM42RZI+WqJhrlx0E24ZYnx++R5Ms5TSLnaHWpdfH",
	"aZDogM338wvAt1dLmhWLZV7wGhjPW9y8UL3Elp0DvhU0MB0HBHd23rCow3UzYCshqe16PQ7+OiFc1iSP",
	"E8PVmLAexOXhR4fbRCb7KQu+3IqKgkTOO8ctboC9zpWgnPqTF24Zr3IzZV7VjSNnJpbU1ziyA1NkWNmu",
	"FXfFi6bOFlgnOuDKCZ36bAE4p1nyqCC6xMX4dzwZb71hGS5W3kxVUIsKkGHDUzEbWSCEcZKGHEXAVRYy",
	"bmQrsg3OU6Wx0zWTCaPZYvAsDYGmE8xhkVGXlrNmUW1RWDXeYiq5VIZME6uGm0wR1e9PfHwpW21MMLdR",
	"ai49zNRNXF1kDvrzbG+mqn9X4HuRdl91l94uwOFSL+A9Jk/SNAKKMNN0VubP/mij+724j5d67FDdtsTy",
	"drtgsD3F44qiEnU33UzeXId3dmlHWHTelZYNu2N95KdfM6pceuqifli73wlfav8j6+7zLuPdw7vu7EZO",
	"2HoB8c3qprgzqzTJY/hC+LpMadRmk++eu4sN4vx0Sf6EKwL0skgSrKK22nJnJjLSP1ujMosWVTChGFYQ",
	"BwhSSsIlRGqVqLtlMRdi5E+ZuKcaHqDLIgfKIAKGImuaV+tJOaYVc13Rxg5y6b6DaEutdjpUMwjsH52C",
	"OKQZk1jfji0CcgKUidUcmUAscVLRLnpIFyTVyVlX5FWAjo/GJ+rXydH4mfr17OhvV+TV/sHH1EU4hbn2",
	"DmxJORUlvWVnQ6wdE9yJ6NU6744B6ZtIDNAziVNmN4s7aYcT3HMBor2jl9eV6z5Axy9fY7YO0MnLKUSk",
	"SAL05OVvmEYBevry9yXh8CbOVrA/6kcxL/qY58Jv4GKYXFzLBYBmhYwjQ3twsDgI0MfR0fjpx5H48Wz8",
	"H+rH8/HxL+rX8X8bPzlRP5+c/O3jaAAaU+lVekBM1AT9yLhweDL+RX//5dn4+ETje3zyfHzyTDc/efbL",
	"METfkbBc7btEc7ZG784nSNoLFmIaVA2kxkf976kPYNK+8u08XDaaf7PqOdj7/aB4o8ZNocMYSy0CbqHx",
	"UnuX/wCYbZJN2Q9dxu6raVrsyNh5Os+2VZq6t0tX5jsLy6M42XoL6rM1BxmaG1uZotnlElOIzgi7ZQMz",
	"a1ZQv05ncgSkPeqbWKk1E7W0nQwly13dNg/qDPNIsmvtOU1ZdYir0gad1VRCoI5AxovX0zGkYRZBhCan",
	"SDQic3HEAzQr0ihWPt0VUDJfq5JDgExW4NXbS7vDAZoWvJDFNECVulmBMlHZLcmvYnYwur9jTnIix4zd",
	"ZbTuWCv/GDxY/qjGw5fqLpZ8kyiKdMaTQpikRQ6RIBbjKM04moGsA8QzOQLCcZYuZI6C4hn6v//7/yiZ",
	"DbNkRlI1ksqbZOjp0dEBktMLEnGIXiAyNz0JQ3jGIOU6Db8quXZLciZBrYG3N8Ph7R2mEZNGD+ZExQPs",
	"/2d9UHlJJCSmMawaDNTIBVPyIgC36CGw0XREKUBUkSDlB04/fF+yqx0tW1Ayuj/HxYzfGomxDyNTfemt",
	"pVB/Euu8HtnXWuOztdb+rTh8R9x95KhikUTPECsSE25Q5HGGJZsxneE43ih04WoJKME8XAopMPEak1hG",
	"gphOQW9ov2knwHWqPtXCbKqNFCzCVQy3I5eOyOWUEI4ufzt15tGRN/7u1+do0TuClzSyMt8WRKjwqYPn",
	"JEw9NasruqMRZWz5ZZ15mrVMiXYxIctL6eyuD5gOgWn4MbxJJW1hrjIN2+E3TEizaqAu/W6mSi43dAU7",
	"y9LViIzOzwTQWjO573jMfflEO1f7qv1Zsd7aH8vK1PlY2A4c5UI+GIcIUWBFzD1xjO0A9u5LpkZ7c5To",
	"h1ieINA8K1LrprUhjt4MZgcTrxnQcQRzkkJknLPVuFObid13gjnmHKgY8uPHSxd7dnIJ1Lw4NBkljvRA",
	"dYrdVNiTmg3dWEPCgCBKezeEkzBU9ZQEnF7deALxnKUMh1y8mwVGmDIBxeYhcxXLMZ0zeqo41hHwaRRB",
	"/NgZud9NDYzKnk6ro4oo+zyggFpZN208RkxmkKv4HnSI4Esu79Q+1/7+BQn5GJToUwPFV5usWQgMc5Tg",
	"L2jvv+7/pzECZfpJmtWayfTHraBw1sFyQJE/f/ZAUJjgtpZD5bY2+MNM7i9I1i799aC88NYkcwOyW3bo",
	"ze78bEiBE2OzO3YEXaCGeSrU6J6X7gwdM67KrNL+Mnm+huh9Wv2czwPECpZDGkG0PyyKNlAFESo8G8BU",
	"gao108gydMoNoLaD9ttsZ8AxiXdouYW1atfQWetbk7KsGB3UypIHKKP5EqfiF0lxGAJjZBbDvntaCuwC",
	"qEpydqsM2UbeXK0UDXSu85BcdOlyOZ3PSaqvBhoOjjJv9uJaRRs6d4OcpMK+qEeyDJjbkQ/sMZGUfWvw",
	"m1xcs2HY3dfglrUPtq3pcKYqK7jiFoyrbZtRheJ2jClNjKssBorTEF735Rz8Kpqjsr0V4ufc0eeEJneY",
	"gqswjPqCRCe0NyMZQxlFMCdOiZ5nceTiRhmZhVQLRGEO1ETlNkeRpRvOnSFWEhb5Hb2/7KkVI5u9cxeM",
	"MSPMizj2CsjCKq2xQbUWuyCHJy3bkQ57+d+JqnPVSRrRogsl8d2HziaFD9qKYODxbTNxt8OkxQlNnaby",
	"U11OxINkTkmC6Rp1Fx5Rx60t16H35uMvfhZz1bOYlqUsElhg5UobpJ+7zmPVuaglaiFO0Qz0wcijsX6U",
	"k9iZVXPKGHO+E71dyoZxiH676dXjqqHZGo0R2qPNUxJuK/bvzifOOlPljYw/9162MdbRFiamDM4W5pIr",
	"avEtYSpu3DSpwjFlMH1rjXWhbDLVHIjq7IFr5mKKiZ0Ps5QVCchkBNdq8Hgn/KfxjrXQfxrnWRYznQl/",
	"6Xlixkyg988r0UUMXZVCaGsZ0cY3Xn2clHEcqwyG6sWattd4eGb5TWIlrSljX3JLBoi7trAVUCZv14rW",
	"doYZI4tURTV1bGCPclrrqCdnn6Ks1dY+mlh2dOsAYSlxY4VqbTDkTGUKhdXPVLckddBctdZGYRjRLAnQ",
	"PM7yfB2ggs0CxIASHAcoxxTHMcTuM2UfTNqL0bjLcUnkq4JpaFjISCAkIEAMcxygdJV4jl+6/KXHUWI+",
	"b7jM5yR2ht+f/R2JTyjHfCmGFILkyLKpwLuFtddek3cBt7CWl8h6sNa2M2SHdr7OJNGXD0bsGRd6ysV5",
	"NgKpvlP+2ff3NEurT06q0yjp0oCEKZ33Ad8hLWVTnOc1LWVpPxWa0K1SJbEIM2EMM+B3AClKipiTPG4S",
	"jg18XsJnyOr7C1ecgQwXX3dn8je2nGVGddy1UWplrIG+9XDXJpNVdfpzJ0zDoILOwPJpA5yN8d7jqGao",
	"6qKvZNgoaGcJysucbQ33FiNcQeh9mLnrN9gcNIl6k6p2xO9l7YjzWu2I06p2xGtd2Oi9EM6BVXEcoOnM",
	"g7U1eUerCq6ORnWQOxpa2HS0Moh2NNE06Ctwq/Z/iOzStip2JsxSDl+4LD1LIcySBNJIZ2AE2yyxwYV/",
	"rcViD9a/ZLrLwpqipR4DW9ie2r8c9BU2dTnY0vImUjRlo6Cr/Gn3AM11XYYzCMWkUx2dL641VO0DlVNd",
	"tTX6JiVV22ciR9mnCBw3HO/OJ3I7/NK5MTv24Z4iqVvVQ+1wJPWrQJUJ6c2A3MQNskchj3EI4rwtU4kW",
	"+sv+wycephmfxTi9dTk8+t+lK62IzLgKSu9Bn8dgq/g9J1tch6Geh6wepBCHCqr4q1fu2AjLhyz1kWSe",
	"oizDqn9sX/djs4ofntIwrUdU1V1hYop8OGpw+KpvuDDpKw1iyWtfnRCL6a6iIZ88KT7NVKDWipQ7jmz1",
	"alBE19Wryl/M1Y3GkFvmYc+ikrQ28JAQbg16NcWnjmSnB6GC/KBrdO2OFJ4YdzmZ9O8QZibtIVP1nquN",
	"5afO3AZHxq+nardKojKpQo1HHy6R/q4yfXKg6ANE6DfM0d8nlwhTTsIY0NOTJ0+fPT+2H1VW8cbSc6zK",
	"Q3+uKq3JiqhJkRK+rv1VnKgIjj8vcRrFznKeFcAQuR97KfIFxRF8qNnpjurB5jtE6P0l0r1MUBay6sKJ",
	"zyqEWl0X6KaRrMGA7Ga9Zr0pN+SqOVc+KapLHkrsCJfPYJwyHV5YJswgFcB6enE+sqJcR6sTKQU5pDgn",
	"oxejJwdHB0+kGcqXUhAO1ePXL76OFioQIDOl586j0YvRG+D2I+YCenWGkJ1Pjo60CcD1IFYy+uE/maKz",
	"MqV7nzm2ppE4u+JzWRn4+ExN3bzs5UBTHCMGdAVUV/OVWQJGTQiM1IPflsdYmkb64W55Lsz1TWmdGJea",
	"GFP1MDdVJuqrLFrvlgr2M/iNcHROC/j2/bggCwqFS5wuIBJceOrmgnwAClGDgmj33BnaMo+J0lNbs3Mi",
	"gdEc1S+mN/n5LRgdNt72cwq7OCNPrHYPSGfPk4QOkpsLKBuB+xBMjofjuDZgRTMb/xblDr+S6Nths2yJ",
	"l5andkP5UCBOQBXV+EfH64/yKoKkMn2IL81NxQt1a1FfCoFF7qam/fSQy8Tz2n4H/1xVXJhaG0+7H8PM",
	"uIrcvj/bnTAI4wdb0mAvoFppEbc0mNolh1/1r/Po22Hjys23tTgKRT66mAStyEWdF6Nq4cnIRfRxFGUJ",
	"Juk4PD558nG0jzKKFpCqp8nKsjk+iErCdAJWhV/8zz0z28eP0d/+l+4+/sfR+Dkezz99Pf7l2/6/OWyL",
	"h5T4jiqlDqE3YY/NANbqkRydKFEWwke0mgCpmqO9G0xVyxFpK32T5RSgNLPnl3MGgrNlGaSdrDxhcBhs",
	"HWSZrevyY9aeRXDf0oMvkky+BfZafp7YC/t7r61JliR4zEDAIYiuMEAszHKwygVkK6ArAnfBKmGByhP6",
	"ONo/QGcqzEbWE6tafRwdGGj/KED6xjW4ctzR7jaJP9UjVNVw5eFwRlIsZ25O0Foa/+P8AmEaLslKXqRx",
	"TGTB8MnljbylZb1Sr5B6tI1DSZH9XrRcyJhJkC1sNjMiqvQwr/nwxjwB972lVr9RqBPWZjrmai/EDMYk",
	"ZZAywomsqz1Tg6hbiX2PVM7W75QragMQLqorGLR3PJaefhXM5JpB3zVU45fxacdWhctjl5/B78LQ6IsT",
	"vx7fN7UOsXdMf3LkrbfpguYhN7T2Y4kdxpuW1r6lOW8+ZvnI9p0w6zWb/EadXlad6/Lwq/z/efSty3x7",
	"o98O/N7rUz3C6RtdY3K/KS6FDpwTiCNdBy8iVGNV7lpivheYhar6i97UX4hx5OZ1o0VEjoGpSp4LkJ25",
	"EhhTQKZ2SE9voB+iCnQSZ4DCvLhmeAGqjf5JcaJ/hXlxulrIbqerxYH9empZaFBAqQkk4Rt9Eq3yWMbk",
	"6OedXNupsDZssg3P1GV8LR1XYsMcdau3eSYVjC6q8JgaTqKzlYL7vlqsS4PpB2rV7Z0S3WbU0QAdlend",
	"b4cmsRpvtkbnZwoswpkrIGqQ1qoV6vWpq3OrFO9fyBdh1x5uH8QUKjJk2HqkdgC/y/Y75HnYhkYud89O",
	"ZTAj4GW8jrdIrLAOrz3ZFq4fxLCcrW2TwWc0vrab/Ny6fm5d/+JbV0d8Wocl7ty8+i8hkLXUH9cmbwas",
	"+Q3zJmrDVJ5+Kn+c5d0O+TfAG4XJ/1rboK/qukOWtNo1FHs0eZBXj+Y9WXNYVFCgFY6LmsGzpTRU4XF+",
	"KSjLif+l2N8ocu7SISoqUIfwyrrfj8v7WMac1Eqa28Dcm/lfV0nPkb0VEfq9TaBWuSb3NAKxH0fWXDUh",
	"HPLWwC2q8skG2N/NSjs7k0IPVDsSvqFXfzfTH+vWr0EV8xDWv4I0OnMWHdI4rV/HDZfGUvaEXDrK0tTS",
	"ze8rnrW7MVPHVp8SmXlrUqbcDpJX8wBtDCr/tRHRw7N8UjZsMclPFvnydJbncL/1KOZHoQVA4wYlU2kq",
	"3vtz0+rhw7OaU/l9DfpR7h2EaYXNAX308YRrcUx5B3dPvgNxdKayDPW7f/xUOSSO5bvn4nCR02xBdZL5",
	"PeQSU+47p9i0lyutXuO4WmvNAMskWwGTVpB+mdakM9sv1JYRAkKzzDCDg1HQYOyZnMEurTxo5VqTKBjv",
	"t3YVFI5Hdm1SWX+1FnKTMKpscGsklADHUsHuXX94i7I0Xu8foHewUndMGQP5bgZVJSDE0V8Vpj1AV0tZ",
	"qSHKM5JyFGXApBKnICULc6iRHC8wSRk3FWHbBBeqpovaO1Qz5TQdS6kiUKVonHvYu6yGpyLwvdVSm09t",
	"9dTge/lEYW1D1rxgXcwIEKQhXee8dN6x27FYFhG6hXUgUxAlQMykdsdZiONy9SCsqmvhUF5R20ADP0Cn",
	"8tJaKJqUo4vrK5StgN5RwoHp141hRbKCxWuHoLcF5aJoCcruY2QdpdUfOUp2MyllyKy6qGKXFMOTo+Pv",
	"BlNIwQFRd7yV1T2jqEgp4HApnRmmwMU9jSEKrj3Bu7Aau89haF5LJ7WrgAYRlhDeMtdz5dLIjGNUyjRD",
	"e6UNEpi6v+LnPKMQYsaB7uua6o7VgS5JuogBxWLhmelCMbsKPZP26qJH205slB5SpMuH5jvEp2yjNZ50",
	"OJfAP6IaljwsaVpCgMI6tfxSMyD86K2M2RsWhPQzQuhnhNCOI4TEoqlcLru6jdAsaofhdgUK+Q5YE7mF",
	"WOvkgTZ8NU/tjeVBG/7xbkXBH16h99LNTnSPwXNFOYRRCnc64sJYiUMYX2nKekCYz52ijkR1gejUm7uP",
	"3Po05ChogmLKQ+AQbuw4BkYfH9WQm65Hn0Pou5L+Z+TBz8iD/++D5h5WaTQD5zbex4XV2dYc5vH57623",
	"d286KMw2Nx2OHst0KCSAOzcddix3ioxbWhDlubnvJqaqoDZ60HhJDY7/oFs2sS95nGSvWkr/qq5qeu8r",
	"oYpkdjSk+VuXBdDErmchn6equNDN2dnfK3ez5rBhgUepE9X3JopuXUfVqobhpx+Hmzu5lyLNAX1M6riX",
	"asj67jVfY5aNtN/Jd2DPFjdjaC/N0M2USXeakGDlV6ucPfveu7NKJszV2W7WLqYcRQC5/UiYsM1upj4p",
	"qWnIw5VYTJ0x7LqlWHUPf+vbeN3QFVVgK46u3Uk2NK8X3j+IpRqtdxEWDlJeFHVSdi5CVa8VU34oLPGx",
	"xLRGwnptHVOHtz85tF4MRvZz1395PHNlIMdtRnYuVdHauwqvFQM9t9dPj5+4ngWJAfEsQzGmC0B7Cf6C",
	"fnk6fbV/T/tGAiJRsx7W9C7XAdkmypq2c05+/AyQthH5EFkgVu7HkONLOwvEesTTG15WPtD5cCvFeubU",
	"tUzUZ0Ss8ra+SkQrR1srvknjopHfIONFyeCGeS8/k1J+uoZ+JqX8KEkpD3MN1ExKGaSI3XGWzTDgGebh",
	"cqzcGmP95rzigPs09Eq0tx1QN9PXZa+HORpZU5ZTbe4daryiZQZ6KI/O/Tkv0dbgVQWEUckjqSmqtwmm",
	"bIinZ5hQDM9RMjLQzFT6F8ob2jnj+vOGdrmA+zOIDI/KPKJ/layeh+FMd1bP7llz+FX+f/BNrCTQmzgT",
	"p5re3HfZ2LxL6PDtm4cIfozcB4OmhWCvqCAqA5E3UtBbC4gKekZYv6QiZUEIzNbaddAdjsRTuZy+B7Mf",
	"6hrHoHXfvVqh/cPu06eRTLShDtF5mN25P23QdZDsE66fmX0dfpVHzu7bdhMapG1+ILF4gGDzjrdJttU/",
	"DRI83BXwg0iZvgtujF25wHetl4ZmlBqrdIO80p9Jn70i9IOkew5TYI2aqWIyObvifUHj0YvRIc7J4epk",
	"JNij+33tqDUv8yPki4QJTvECEpAF+7VMqArjrjqntWqZMhHH1X9SK+rtf7vcqr5ZJSe0hhEE9oFSq7lE",
	"gWUFDcEawvaye7OjkV6a6I8CREuEQ5oxldKn/a7WkG2vWM/6U+ElLjq9MdHVjjfaWhWtrYuOilH1otut",
	"FLxW8WHFeO3fPawvo2pYW+BcwEEu33uu7oJjModwHcYgh1eXpw58qxsnR33qVoKMW7Ts9KjALeLuewfD",
	"Pn3t8O3Tt/8XAAD//y6u2A+43wAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
