// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive or Excel workbook
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Start a collection from RVTools files
	// (POST /collector/rvtools)
	StartRvtoolsCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// Cancel benchmark
	// (DELETE /forecaster)
	StopForecaster(c *gin.Context)
	// Poll forecaster status
	// (GET /forecaster)
	GetForecasterStatus(c *gin.Context)
	// Start benchmark
	// (POST /forecaster)
	StartForecaster(c *gin.Context)
	// Compute pair capabilities
	// (POST /forecaster/capabilities)
	PostForecasterPairCapabilities(c *gin.Context)
	// List available datastores
	// (GET /forecaster/datastores)
	GetForecasterDatastores(c *gin.Context)
	// Cancel a single pair
	// (DELETE /forecaster/pairs/{name})
	StopForecasterPair(c *gin.Context, name string)
	// List benchmark runs
	// (GET /forecaster/runs)
	GetForecasterRuns(c *gin.Context, params GetForecasterRunsParams)
	// Delete a benchmark run
	// (DELETE /forecaster/runs/{id})
	DeleteForecasterRun(c *gin.Context, id int64)
	// Get throughput statistics
	// (GET /forecaster/stats)
	GetForecasterStats(c *gin.Context, params GetForecasterStatsParams)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// StartRvtoolsCollector operation middleware
func (siw *ServerInterfaceWrapper) StartRvtoolsCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartRvtoolsCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// StopForecaster operation middleware
func (siw *ServerInterfaceWrapper) StopForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecaster(c)
}

// GetForecasterStatus operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStatus(c)
}

// StartForecaster operation middleware
func (siw *ServerInterfaceWrapper) StartForecaster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartForecaster(c)
}

// PostForecasterPairCapabilities operation middleware
func (siw *ServerInterfaceWrapper) PostForecasterPairCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostForecasterPairCapabilities(c)
}

// GetForecasterDatastores operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterDatastores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterDatastores(c)
}

// StopForecasterPair operation middleware
func (siw *ServerInterfaceWrapper) StopForecasterPair(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopForecasterPair(c, name)
}

// GetForecasterRuns operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterRuns(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterRunsParams

	// ------------- Optional query parameter "pairName" -------------

	err = runtime.BindQueryParameter("form", true, false, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterRuns(c, params)
}

// DeleteForecasterRun operation middleware
func (siw *ServerInterfaceWrapper) DeleteForecasterRun(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteForecasterRun(c, id)
}

// GetForecasterStats operation middleware
func (siw *ServerInterfaceWrapper) GetForecasterStats(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForecasterStatsParams

	// ------------- Required query parameter "pairName" -------------

	if paramValue := c.Query("pairName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument pairName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "pairName", c.Request.URL.Query(), &params.PairName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pairName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecasterStats(c, params)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.POST(options.BaseURL+"/collector/rvtools", wrapper.StartRvtoolsCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.DELETE(options.BaseURL+"/forecaster", wrapper.StopForecaster)
	router.GET(options.BaseURL+"/forecaster", wrapper.GetForecasterStatus)
	router.POST(options.BaseURL+"/forecaster", wrapper.StartForecaster)
	router.POST(options.BaseURL+"/forecaster/capabilities", wrapper.PostForecasterPairCapabilities)
	router.GET(options.BaseURL+"/forecaster/datastores", wrapper.GetForecasterDatastores)
	router.DELETE(options.BaseURL+"/forecaster/pairs/:name", wrapper.StopForecasterPair)
	router.GET(options.BaseURL+"/forecaster/runs", wrapper.GetForecasterRuns)
	router.DELETE(options.BaseURL+"/forecaster/runs/:id", wrapper.DeleteForecasterRun)
	router.GET(options.BaseURL+"/forecaster/stats", wrapper.GetForecasterStats)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96XIbubIg/CoIfveLI8WhNi89t32jf0iU2604LVuh7UzMsccBViVJXFUBdQAUJbbH",
	"EfMQ84TzJBPYqlBVqIUUJfv09Z9uWoUlM5FIJHLDl1HE0oxRoFKM3nwZiWgBKdY/j+dA5TmL4RL+mYOQ",
	"6m8ZZxlwSUC3SFkM6v9A83T05h+jiFEKkYR4NB7FRJT//DQeyVUGozcjITmh89F49LDHcEb2IhbDHOge",
	"PEiO9ySe64GnhMaq2ZsRh3/mhEM8ZhTY7JdiSFQZ/+vXr+OiqYJEQ1bOyqb/CZEcfR0bpK4klrlo4hMx",
	"KlgCEzMuYbTZBDhnXP2IQUScZKbVqOyCdAvkf64j/3U8EgUEtXFyzoFKZCFBUTmu7TLekNqq194Sc4pT",
	"hck/FMhVZA1VJt6oLU1OK5PVSW/hDBHf8UsV52vM5yCR+ohmjCO5AITVMm0PV2/VFUP7ONY+1XAbj/hS",
	"Mpbob28pniYKyToGl7fXjCUGA7CNCrimjCWA6SjIouMAzwXZNssSEmH1/Xci5CWIjFEBTf7EZUP9byIh",
	"1T/+jcNs9Gb0/x2U+/3AbvYDb/QPS+BLAvdqUgsF5hyvGuBXJuoBuRi0AW6FjnWyeiP07Se10t0D6BaB",
	"nst0wnIqm53f5+kUOGIzdHsuEM8pJXSO5III5OFeDkmohDlwM+ZGtL8976W6xaJKDYeCmbhnLW7Pm6tA",
	"Ajx9e47OToeT+va8hcI1BIjaGbplCM4TLKPFTRZjCW8foiQXhNH204fMuUZJN41DG7MYREtPQJIhAVJL",
	"GZwkamED+1SR8SwWLSQRapBcgzgal0vcIFNlGdc/7lJCfzkax2QJ44J8jVPOwDkOUCJIXKDRIsX87jIP",
	"HGwRBywhPtaEnjGeYjl6M1Jo7kkS3joxEXdX5A94N/Uo4G2DODdQXUFUHZTl08QbkeqdpnoUp2tjLsOi",
	"xRCEyp9eBfcekWBmDcOUglywODhFhgl/b5m7+ZFDdro2PgKE4r6zocALlvMITrHEQjIehkTq47KnzYKz",
	"fL7Icnl+kolBwIb2aQm+R50mlE2Y/GWo8EmVKRqAFusz9vgxxMsTnOEpSYhctepyroX9d13TSxKIpGG2",
	"LvH8IbN4lDOq+WeMQ4SFhE0HIFRkmwNQW6wSG3/gCpRNItbH8OkVJHmSq5F+BSxzHqJpzEVFQ5rhPJGj",
	"NzOcCBjXROnfFyAXwNHp5RXaOSWKc6e5UusvwXAXuooWEOcJ8F1EhNOqrH5IBIoMNEHxHXOtrlWgGL1n",
	"tH5yvhmp6XEuWWp0hIoKWs7glNBf8yRZoWPTXqt4F5hLgut/Pcc0x8lobOb8FFT/GcdzON2AYlemq6bc",
	"eoT52r6oN5Ik5A8cvvJEjM5IDDQKHPtqy6OILUHDVLZEGfAIqFR/3TncOzo83B2jCCdRnigiISzQcnJx",
	"s3cPZL5Qf3BjGK6tiaoUP5BUrcHR4aE67aj512FA4kZZ/hkv5wFd0MI4ubhBeYluANBtgJDihyYI52aM",
	"ZwIh+/l1E4SfX8uFm48kz0GNFNLuBUkhZXz1DFB0rsmzQTFoWZ4Bmrr4t/um5J2SkctFLFEoSTr2BUTw",
	"4DCnU1i2+FpnQ+BRI4iL/ugeC2S7VLDv0lJDl5sSJKQAl2RGfJHZd9nxuq956enVa4qRj+dzDnN1y2gS",
	"zQht0XVnjYmQhEYSFY1D+ub3Tn5zsVEnXBeuZSt9Vd+hDE04kSTCiTqSIuBU7Abxp4yeD5qCMrpXnwZL",
	"lAAWEjEKjQnD80kmcaJunU0jmPqCaMXmQOoLEBgzxGnlqnozVohZx3xc8lQ3V05YmmFOBKOnZDYL6IAk",
	"BSqC1pzrBaDiM5oCoXMU6eE0NzklSwMcgNYjf1ClYjRZndHjPnW6isCF0jiKziebdK4tQEmAEqRy/KHE",
	"vcrTFPNV673FWfdqJ6oTGUKrg1MmFx7ziH10RmN4QIdKbzxGO1MsICEUdseI6A9H6sPJvm/W6KZGU1Z9",
	"1SfQmen+Qh9A5T+qli11LzQs1Nh0wEmE1Ffg6lQRaOcEpYTmAh3vonsiF0is0hSkaiZA7qmmKGI5lUKd",
	"kyWb7RfiDy2wQJQhuyYHdkUUsu3CdTgvvKWSr5oSa4MBGiJpgzF8MbN29xpDb0GAhG+rmoctE3Tvi26L",
	"d21LrMm6vRZXf/gOMBlvM0S0eIzeajdRCkIole5enbbGc6JvdbpPp9/IyUsOOF4ZJUw7ELQLxAFd+wcy",
	"e0Zocw4Xlc9GCOt5h/qPKoib/15aaIIfJz6ILS08uGstzg3sXU3Mfy8K1LrmsA6uQIO3hghr+LVC+yjg",
	"6kgkDtygCzHnS7l9dMEEkWSp7gKYCnSiBVjKOOwHNQvv+KvrWjmVTqMQWBIxWxWOjPI8JhQdo2kuEWVS",
	"/eOkY5aTx8xy4s9y3K/RGLL1U12fxg2iZ/avYS+r+mp1riC66nuLd6iur6mmol3nG6LwaeeC1vmIQAkR",
	"ssW31OWbYLa7AmcfvU0zuUJarhkJoxGGhwggNm00dvvDHRnB02FkKDXyCeYADS6c1k/fcZZnrc6dmmMw",
	"xQ+/A53LxejN68PDjaMJWKrwzORqnOKHX14fHmqEZiSxhtyUUDfN0eNDFrQPR8/grpEeGu5+vu35NGZH",
	"GrOw79Bi27Iw+jqGk7bDLOcBVl5OgErg6Obyd3NhKYYRaAoJU3KAhU6zXAAP37DdkEWLkOcWJ6HLpTOU",
	"+lBgDkh7JuLCvMtB5pxCrKDe7/fWK8Q9gN3sISpWXDP165G4Owt7n2YcYIIzHBG5encSdl4tMI/vMYfj",
	"KIIEuLrknbOl7wLyrOALJuRZgD5nxY1biR1FCtVSyQcOVl47BJQqgqXE0UKfljRPEqOVSp5D6LrOYkha",
	"3GdMsogl1/rDl1aL+BmbMDoj87z04XXpcVfhXk7q9tFTtkGzBBoHHZF18ae+NidrrGYx4tixQPti1ojl",
	"qNrJaacgMUn6nWBDpfxY99TATwe6OhXGgxtTjE9hSaJ1oaJt7lnLPseqYcsGs03OW3nUNrhtW/uSX+pH",
	"769XY/Re/ef2liVjxDj6cP3b28teu6Av2SokL8jZueoXmPDWA1Rt6iAS7TTcivM5jGK/yziIKSQg4Xc8",
	"heRdwqY4SVYdkU+zmVHreyJ55AJLtMCxFn2JGhtxSNnSj9nyZIRuEbZmmc56vHssmqO0kMSMOC4BDqH+",
	"VkiSYgmXmIb02ikIOcEi5JGzQhCZ2dEO7M/30cfR0eLlYfpxtBs6SeEhayFd22gvFkev20a7Z3xd4F4u",
	"XrUMV6NdgbcHtD9jiJS/Wi+42i7tkZ9ppngtvsypCB8W7bEprVutN6LkZCVBXLsLwoAAkaLTTZYwbGOe",
	"thRYokOkfNNCBkbFNNNiq5XaSDhtObBE08KLqmOsw4gwNHRFUaNtFQJXclg/NqW62P6UXeyjWCfEOeTn",
	"17+ze3N/GHD0qfY3WTa4PQh5Afzoutc4XZUYxhA7OPpnPEoB07Wax2S9DmSd1p07R2C1fsXFPMDtMj6F",
	"5aahTz43eTN5JKqgX6JWkrwCwtjjEX/9/bXtYjxolVoK0uFGz4AcDKhYDSngDIxu33/qk9H+rgxvKX31",
	"304IYlf88Af9AydorubrCyEurQDVUX7Vf0fwkHETDod2srv5gWmOTq9+39WHkeaU0ZuRdd1/zA8PX8Iv",
	"6N/fnSBMY+eHQL+gv2ScxX8Z6iq9oeSfOVgMNvFVvzO4E5EleNUaBW0CWtcgfYeHu8PAoIHpNudrTIcz",
	"tWGlAB87y1+PVa/DXtdz+FhAx+02sFYK9GA/GGdCl0AlM9bmrh5nRcMnocx6Ee+3hMscJ+c4WhAKvSZG",
	"QxIzxbrEVlej9yDvGb8LmRjVDTRwXTAdkPmutwwiVJAY9JVhru9boe2bBYwtFwjHsRIcwfAGHAUiko4n",
	"rg/CAgkAiqar7qlpiWMYF43EjLO0e5yMw4wUJsq2wUwrlOhmaGdydnpZCUYiVL58EbbsN5boNyIkm3Oc",
	"mukydUTpm4gxMdVWDBsPSt1g0DDplGIgJfQWJzm0KQqQDdjqxSC2x9hAEmK531joMh5l+YRx6IzYmVzc",
	"oEg3arW0+ZE7WX7FojuQvWMK22zIqB0nUHn2lLGm+uIT4mt9Bp4H/ESKPC66jVB0flLjG3196Ycz7TXi",
	"pEwHmedZxnjwZluPp12eMxOQJJBwvQp3iraQ7ijgr1ZCQrpfGNZW+27G8+qMu+HMknbj0nIwyBuDWp9i",
	"t9/uXdgt262QZ3TGcXuU2gVwdfmKtEF/zd0bZfmHJfAJS1MiUwg54hSLqzZR0QZdYknYPppUwo31wYGO",
	"k4RpAaPDjwU6QMYPd7FYCR2+NbE7cMAdpTCTDz/6yltoAFm1chfqlqCUc2vTimNidNiLCm1bKVeuihpt",
	"OGBabLXApFbQxomHhfQ64lhv/b41vTw+d0Jik6W1Xd3a2n/iJSaJDVYZYqI2h91wEjo9I4C18Q9Uojbr",
	"NGzRtsqdIzp0st/cWgcVs60tX8j3a6ZuMq9HwMpOCQsQnbJS5BeHVDWJSRI46n7LU0z31BVVx2XadghP",
	"WS6NL9K6+kkxB3L306YZdK1IHegN1OmIPAiA07S6bWppC4br1Ims1+mimCv4+bIAIPh54kEVblCCGvze",
	"EWkDXZzSHmzVQvaiX4PavdaNLmL6cUPgQp+C39zoakfG8V3vFSmO7zyJvw6BvBthLcl36GXR5N96V8b6",
	"Xb/40gnBqVXWg1qBn0XWGahXa/61CDSspSwNGMTvoS/PVm3pvjirRmrVSv2lc+FM3IJ3Je5sfd5cW3PN",
	"NcAF6StEDuKEA76L2X0gpQLHSyLsMnf5wXQcbSWG/dj2RETN0ZIwYMLc1x+8CJBvH7xF/vaNbORz+7CE",
	"muM+aCPsG/ys7NwxxT3men+vPfzfTcfWoevBqI785ZRV/Mbl8jePh5KJzl3CuOamAA8JAUI45axxuEXt",
	"NiISdr4XXtSBrtFyfjdbCI12085S3BMZLdZzgDv3vjsbhMQ0xtzWHHEpqupfbvjxKKfFFSzo8lommLYE",
	"JCxT0WpsC8eZtNZNCCUJNwOR28qXuHuljZDyA6cWeAlI5LMZiYiOmORkSRKoxDp619uUCEHo/KJs1Zjs",
	"KoOIzEiElleZDjkqhzSudMwB2XE2j0t0uIaIdYEJ76LT5kEz3V6rpwivWNfz2ZfkXaVNa3DJeo6nYMBK",
	"3wq2e48uOItABJS/sANEkcdFumW2a2ijAg/nLd2aD71DhAJfQuBfkvlCCvIHoXOrmHTkNpT3ti4CN4es",
	"6ToclIj6HBTONbjLpoWqNRCN7iRy0+Zzy/ngPrfK5moS+hA/e5kIPrC1zQ8e2Nrm8Q6xExFxN9irnq4B",
	"tJfUPLD1cKD15f5zxtmSKO6H+HOU5V02iEpbhfLnu+nGcxmTzed02mbU+BwNPDk9vqtxmTfM+FHpz3p9",
	"KxzaSr5uXLsoGdqCVxJzWUYJtErriFFjBolWLYV6egr5FMVcRJvfcBvHQZkreLTx2aBJUtoaWknSnkVx",
	"zi5h5uo8WTPNd1LoKYxwW9x0gwfmINS36wUHsWBJtebIy8N6wZHfsVQcg6RrjwhFKUkSIiBiNBZoCitG",
	"Y3S/INFCn43WFWIzTojQZQxJDFqrNABo/bmlSMHr4I2zCXizuIur4RI1Krycu5Iu5TgeRq4iibk6Ob3f",
	"Hy01tVxCqj1sWrrl7OADmjAqOUuCJVxiX4dr6Ni2EMSH2QXgu+uiflIFjJ8bq3lheulUJcB3qCy8NKRo",
	"RKcL19iL6uk8KaG+z+Jo/OdJ8PEmeZ4Mn9qE1RSflvXosATq4pq1mmR5TuJgUMMGISat9sJxMfWnVrh1",
	"tPftuWgV3TgOVivU8hrHfli3TjratuAu16IusxXWqU3HCUJnPnsAzjhLnxXEELs4k2VLVcjeuK/QUt6e",
	"m6g5E4EnhpcrrefG2iImMUhT9RfXKnqKNUwE447CKae1cimbDG4Kf0ywhDnjISnnzWLaoqhsvMFUeqsM",
	"mSYxDdeZIq46HtvWpWi1NsHCerrzFrqp67iGyDzur0V7e276d1URyGl3LE1hwAUcLewG3hHauMBj4AgL",
	"S2ej/uyO1nKMJ31race2/sxEh8/kAjaneFJSVKMeppurx9fhcFj4IVydQQZFw+5gQv3pV8ardTCGtPs7",
	"kQtrUhfdfd4z2T18S6JzALZeQNpmDVO8NTvlgchVUSrRqk1tASJdy+Bue9cEuCs083Uc4Ds3keP+6QoV",
	"lWZRCRNKYAnJGAHlJFpAbHaJCcpQcyFB/tAFAU3DfXSVZ8AFxCBQ7E1zspoUY3oZuSVt/Ci6brdak2vt",
	"LbecQWH/7BTEEWdCY3235xFQEuBC7ebYRXqCSebQ9eTpnFBb9O2anIzR0eHeC/PrxeHea/Pr9eFfr8nJ",
	"7v5HGiKcwdwaTDak3LuTR3R2xNoywYOIXq+y7uCpvonUAD2TBHl2vYCtZhzOIzcg2jn85ab0Ro3R0S9v",
	"sViN0YtfziEmeTpGL3/5DfN4jF798vcFkfAuYUvYHfWjmOV9ixfCb+BmmFzc6A2AprkOVDVJgWP0cXS4",
	"9+rjSP14vffv5sfPe0c/mV9H/23v5Qvz8+WLv1ZSB9vQONeGtifExEzQj0wIh5d7P9nvP73eO3ph8T16",
	"8fPei9e2+YvXPw1D9D2Jit2+TTSnK/T+bGIKbXmIWVAtkBYf879XbQCTZhRD5+Wy1vyrV/PcP+8H2R9r",
	"zu9QmrlHwA0kHvVP+UvAYp3SVP3QMfFYSdNYDibO6IxtKjRt75CszLYWz8pxuvER1KdrDlI019YyVbOr",
	"BeYQnxJxJwbmpS+hGiEi9AjIOhnW0VKr5dmc7uQoWZzqvnpQXbAWTg7tvaAqay5xZVGZYJX2CHggAvji",
	"7fke0IjFEKPJMVKNyExd8QBNcxonxqa7BE5cnSlArmbM9e9Xfod9dJ7LXBfpBvMcxBJsEcE7kl0nYn/0",
	"eMOcXokMC3HPeNWwVvxx/GTVhSwebTVc1ZavE8WQzllSiNC0yCBWxBKmPNcU9FsZkukREE4YneskKLNm",
	"6P/+7/9jeDZi6ZRQM5KpqiPQq8PDfaSnVySSEL9BZOZ6EoHwVAC1EbreE0d3JBMa1Ap4O1Mc3d1jHgtT",
	"MFQSE56w+x/VQbXfTHFMbVgzGJiRc2H4RQHu0UNhY+mIKEBcksDUx2ra4ftKIflh5jkno8evuJrxa61s",
	"0tPwVF/xo4KpP6l9Xg1WbdaqWFnpP6BOQRoHqmOn8Wsk8tRFYOS29AGSmE9xkqwVzXG9AJRiGS0UF7gQ",
	"pEmig5tcp77QjrKdAjco+kwLd6jWcjyJNMkPgWRdordTSiS6+u04mKhL3rV3vzlD894RWkmjX8LagAgl",
	"PlXwgoSp5n52BbzUAuc9u2wwEbySYtR8pMCzUnY9ZdNWp6+0Y7RmrTWZuUxlbkYkCcXNpoFx+t2eG75c",
	"0xQcfLqpQmR0dqqAtpIp7ONx/vKJNa72vYjlpS+4AttFYbVE6Q4SZYo/hIQYcRB5IltCc5uZH91Oplp7",
	"d5Xoh1jfINCM5dTztNbYsbX+T2ARbwTwvRhmhELsjLPluOf+Inb7BDMsJXA15MePV6Hl2YoTqO44dKlY",
	"gfxjc4tdl9m7SrVfKwWCGOldY04i/PLtioDn17ctsaXB576GON7dBiPCqIDq8NDJ0MWYwRlbXjqrItAm",
	"URTxk2AySjc1MCp6BrWOMsju84CHWYr3WPb2kClmYkKe0AFy9ZM+V/7+gBR/DMqQq4DS9uZJ/YERLFGK",
	"H9DO/7/7H04J1BlVlFWa6fzqjaAIvq8RgCL7+fUTQeHi/RoGlbvK4E8zeftDJ80nRZ50LVrfOgkDst3l",
	"sIfd2emQ8pdOZw+cCLZ8qWipX2p7XoWTzty4JlnQ2sv0/RriD7T8OZuNkchFBjSupGR3V9TT4RolnjVg",
	"ytjdimrkKTrFAVA5Qft1ttZSk5tqblHldVnofFvXkrJ4oXVceQZ4jBjPFpiqX4TiKAIhyDSB3fC0HMQF",
	"cFNFISwydBvtuVoaGthiCkOKXWiTy/FsRqh1DdQMHEXC+cWNiTYMngYZoUq/qEayDJg7kEjfWcja4Te5",
	"uBHDsHuswh0o/zm8aIwpHhqMW3Cmtk1GVYI7MKZWMa5ZAhzTqP0VYKdt/Kqao6K9F+IXPNFnhKf3mEOo",
	"8pT5glQntDMlTCDGEcxIkKNnLIlDq1FEZiHTAnGwFedDo+jaMGfBECsNi/6OPlz1FKPSzd6HK1K5EWZ5",
	"krQyyNyr3bNGOSi/4k9LPYNAhvfVfyemcEYnaVSLLpTU9zZ01qms0hQEA69v67G7Hyatbmhiazey7NjW",
	"PGohVMZJivkKdVdHMle2Dfdyq/fkT36fCxXdOS/q7aQwx8YcN0jGd93pyrtVg10jTNEU7OWqRep9L7e5",
	"U68wnlMI26wCfr0tISH+7bb3LDAN3fHqFNmeE4GSaFO2f382CSYmFl6djscwVBunYW2gpuoAb6VyhSIf",
	"fyfCxJ67JmVIpytcVN1jXSi7BMBg9UodYn8jQovi4u8jRkWegk5oCO2GFgtH+42+Yy/03+glY4mwBSJK",
	"mRuewJ7B16qLGrqsEBKoo8sS0TZedRwqJE4SXGjYeVAc58MLLtymXi7gqa3doobIW47BJXChPXR540jE",
	"QpA5NZFRHYfgs9z4Oope+jcxb7c1rzeeLt64hHhC3GmyVhoMuZe5aobVe9kdoaG63qa2oVEso5izdIxm",
	"Ccuy1RjlYjpGAjjByRhlmOMkgSR8L+2DyVpCav6gEEee5MJCIyJBxooDxkhgiceILtOWK5wtmN9ibHGf",
	"19zmM5IEQ/hP/4bUJ5RhuXBPMwYydUrw7mDVqvNpf8IdrLQj2g7WOHaGnNBFKlQDff2Y9Y4zw1NpXvnT",
	"4pvKz21/p4yWn4JU53HaJQGJMDLvEt8jy2XnOMsqUsqTfia8oVukamIR4UIhpiDvAShK80SSLKkTTgx8",
	"+rpNGbY+kFCsgg45X3UXuKgdOQvGbey2E2pFvIL1nIQLKOpiU/35F67huITOwfJpDZzdBaDH2C1Q2cW6",
	"dUTzAUXrENpUcW8sRCiQvQ+zcFkTfwVdst+kLKny96KkylmlpMpxWVLlra339UEx58BiUQHQbPbCypu8",
	"o1UJV0ejKsgdDT1sOlo5RDuaWBr0VeE25z/Efv1tE38TMSrhQer62BwilqZAY+wehtxgiw1+esPbLP5g",
	"/Vumu3b1v9Brc7V9XYREKMFk0yWDr8/VRO0T1XxeNiX6OnWfm3eiQDW0GAJekvdnE/sYbtfBHDiHeyo5",
	"b1S0ucMY1S8CTTZlaxblOmaQHQ5ZgiNQ922djjS3X3afPnmRMjlNML0LGTzCJoSgFsGcqaCwHvRZDDaK",
	"AQwuS+gyFMrPf+r6JiYw489eEGUtLJ+ygkrKWmrdDCuqsnk5lfUKqbRU3Knrmcz4G1NXOyVQ2qStqEkI",
	"k76KKx6/9pVf8RY9VIvlU0uaUD2dqLEj9YmjW50Migq7PintxdJ4RYZ4qtPe0KXb8/JZWEmCB3MoDNyC",
	"Xk7xqSNh6kmooD/Y0nXbI0VLnLyeTNt3iHCT9pDJTTiuYPmpMz8ikDXc8rSAScRy6Ua1l2muXOV2ky2U",
	"AUeXEKPfsER/m1whzCWJEkCvXrx89frnI682iY1Z1pZjU5v9c1mAUBcKTnNK5KryV3WjIjj5vMA0TsJv",
	"+BQAQxx+TjTP5hzHcFnR0wOlu913iNGHK2R7ucAu5JVLVJ9NGLZxF9imsa7jgPxmvWq9q+IUKsVYPEJv",
	"K4Fq7IjUb/UcCxuiWCTdIBMEe3xxNvIiZUfLF5oLMqA4I6M3o5f7h/svtRoqF5oRDnRhCx3da4IJmKvI",
	"eBaP3ozegdQDXznrKrd3CN35xeGhVQGkHcRLaD/4T2HobFTpPkXbn0bjHIrxFYWr7rWZuu4wlsApTpAA",
	"vgRui1zrTAMnJhRGCPuDjUdGNfqHmUPfCzPrba0S48oSQ5fxMQsJQp6weLVdKqjxi/JSVZaRPIev324V",
	"dFGiaIHpHGK1Cq/Cq6CfGEa8rJD16vDnYHjMLCFGTm28nBMNjF3R1CxMfT2/jkcHkX1932a0BZld3ZEn",
	"XrsnpHM5TeViHiC5c0D5CDyGYHo8nCSVAUua+fg3KKcxwRwOvuCz+OvBl+lZ/LWVmuaVe6gSNMMcp2CK",
	"c/yjYUrHAhLthy36IO2XIFTnI8mFc1u8GWH9FHF1Y4w94jfkbpP73CP8yJQbHTLrdM1ZPz0LC5WoFNnf",
	"TT7y8LXMYGxZGfA9D3M8n3OYK61UW7diMpsJs4NfBcJPiHmwvOxOmTSh6o/b1IZ1kLxnPpvqXCeXqBUE",
	"9BF8fPAlJilQdW6uw9OnZDb7r8fX42B2EkhOIqUFWfKG5yrI3DmjUxud+Sz1c0Ipo3tpqBxJO4AXpQ0T",
	"7RztTbGAeHcfHavtpx3qhScpWSkUGE1WZ/RY85b5fbLv8PlnDtoCaxGylr0S9iIa5MirSXcU0uq7Lgw6",
	"uFLp19r8qn4IEkMHDDY6toSjc+7nFk16owTk0gWeE6pfv7Eoa9VabWfghcdMLprCwIWczckSKCq5qk8t",
	"KVqipX4a7bmF2yknSYJidk+1POvCOoAxbuA7VOZ9IfHXg3rZslY96Nhv2CPfJv0Chnw/56aH2VDdK1TF",
	"rf1UnGybYzQYQRgQoQh7POIrv5XSYmFucLXLDr7YX+ocrIXLtF0LA7Wzn51NGvLT5cWaWrjukfaYpZjQ",
	"vejoxcuPo13EOJoDBR3iV5TNa4OoIEwnYGXo5P/ccbN9/Bj/9X/Z7nv/ONz7Ge/NPn05+unr7r8F7AJP",
	"yfEdhdtDiqKlSD2BpXyF0yZKFm87IV5OgEwZ9l4pXJa3RtbCts52GiPK/Pn1nGO1skUZxK3svHcgC2wD",
	"ZJmuqvzj9p5H8LatBw+aTG0b7K3+PPE39rfeWxOWpnhPgIJDEd1ggETEMvDKBbEl8CWB+/EyFWOTJ/xx",
	"tLuPTo1SpOuJlq0+jtq0Kj3uaC0IP+Qyy6XlpzfoD5KhncnVrY5+sqLyf5xdIMyjBVmCFgQPiXhAO28f",
	"IkjQPeN3U8buzL3IlDABkEb1UtDstoBqGTioAo7+IJlnBTX/UrOGtNb1hMCSxvssA/qQJgYCscdmMxJB",
	"zKI8BSr3RcYBxxqLNNnX/69KjcK4PSUUa5Sa9kp/yj/MU8HrDNCQL94S6EAKTPRDQuVCMY6qC9IrTAyv",
	"PNt5bDanrxlq+YiFRsLHr4nKWtpamYffqqe9c495f2vxYF+bt5UBpjYwfSfCAvYIFUpZlUS/yTM1g5jQ",
	"jbY9NV2512GGg1C74+lwCBPx/WzXNou+u7atc1srpn9x2FrY/Lkvcs1n7zu0ZMutfZvVBOmo44ODKG9s",
	"z6ZI4yRxy9SuPdtt1bkvD77o/3fZQN+B2aDfwf7UcLSObjF53BRXSirOCCSxLTgcE26xKtQDNd8bLCJT",
	"Zs9qT2/UOFpLuLUsosfA3FQpGCM/RXjsdC6dQ6vd4WP7VO7YVssYoyjLbwSeg2ljf3Kc2l9Rlh8v57rb",
	"8XKuVBB40MUEvIrOCkpLIA2fOrDhIUt04LJ9gDaktyi1zifb8JIoQq4Sp0+MusXbjGkBY6tXPaeE0+hs",
	"JOC+rRTrkmBmb7g3eDXr1kOzB8goZk+/Ld49zHjTFTo7NWARKUJR44OkVuVFhDZxdea9efAnMvr4jzwE",
	"XCMaFW0GLpoNWu+i/RbXPGpCYy1/wZPKYaYfxgsvvA1KTb3Y11Z9sslc34liOV35KkOb0vjWb/Lj6Ppx",
	"dP2LH10dQfwdmnjw8OqP1EDeVn9enbwe1d+umNdRGybyDsylY49l3Z6PdyBrL8D8uY7BtudtArxkxa6j",
	"2LPxg47PWmKSmLpqPhTGYScezw1lDkE7FxTvtvyplr/2mkxIhpjUCZvnpB9Yed61T3RgbuXtGB+YRy/+",
	"l2Xac2VvpM18axWoURczPI1C7PvhtVDxrQC/1XCLy6T7Afp3vaTh1riwBaotMd9QH+vt+fflXq1Rxb04",
	"+q/AjcHCDgFuPK/6PYdzY8F7ii8D9f8qNXkey54VJ6R7MMDeEoV7p17XJRnEr8xG+idgioTUwp4lyyZF",
	"w8YitZOF6Zf5swwetx/V/CjyAKh5UJjJ5W0NVHCtnj6GvT5Vu62B8W3Fskf1Advo0xLTLjGXHav74hsQ",
	"x5Zz0fkQjw8yL0NbEw441lU1Ms7m3FbieQRfYi7b7ik+7Ss77YAvdYUbHTbSviSXplV1ZdryDUxBCczl",
	"gbp/7+lyo5V1qSb/aDdr5X7f68btSXs2I4ZzV/qSF75XDnvPrD/avc7wTDymWh8F8pNuTdEjXR2FCH3e",
	"uFpcfXxpQnfcCGaxOli1+u5JeSzUE6ZStgShFXZdSiYuyhN5I5RRQ4orp1jA/mhcY/hTPYP/3MqgQ8ab",
	"xMD4yLhMPYZDJapAU5DK+6t35tQJYyLUGyOhFCTWusDOzeXvOqx4dx+9h6VxhzIB+i09bkq6ceQeq9hH",
	"1wtdeS3OGKESxQzM+nPQQhBLqJAczzGhQrpXIpoEV6diF7W3eCIW03TsyZJA5ZkYVLfeswqehsCPPkGb",
	"69Q8SWvrXjxbXtEd7VqIrsUYI6ARX2WysDOLOxONju5gNdbx5hog4Uo1JSzCSbF7EDYVd3Gkoyl8oEHu",
	"o2MdX6EOCirRxc01Ykvg95woqFS3jMOSsFwkqwCjNxnlIm8wyvZz3gLPLT1z1tt6XCqQ23VxuVyaDV8Y",
	"wf1NYIo4BCDqjsH0ujOOcsoBRwttd3MF6x6pt3MInQmtG6t2+hxEOMP6xSRS8VrViLCA6E4UT+JknCxJ",
	"AnOw8fJJggqeFmin0MPG7i0Q9XPGOERYSOC79p2lwO5AV4TOE0CJ2nhuukjNbsJR9dVq3iNtJz5KT8nS",
	"bp5VB/sUbazE076RAvhnFMN6DQuaFhCgqEqtdq4pF7BLZVE3SSMHbf1JNAUaLVLM7/bRsVHd9ryw4pwa",
	"T17GQQMf++XzwrqMmuLXEpgn1HbLWdpX+MShhyJMI0gg1gUSdXE7k0hn0tY15l3rXdDJL975qBXX8JTj",
	"eqvrka9Xx7KvihdImSqwRWJjhgkvFHFnzQnu0AY1n3BvDlk5V3urZOxtGAwuWJIEhmylfRasOq4vGAJh",
	"saJRuYJqOymJy6hWXlMl/Isyk0ithAhtF8xlbb9sX8OozbJWbv232rBDDSCeJB47xUS/vq2Wf2yuEYSj",
	"hKREIniIALqusseU6ay3yn53l9pt7HtzOe3d9lWZ3lAEwnw5YWmWK033fkGiBWKzWcJwrG5dC2ZjMmaA",
	"9csamlMLS6l5eXXP5svWmBYZ7Vw/x0hj1c0WQHGaFp4D0mYRJFnGEjZfoRg4Wbrq3royHeN3CZnJvUB0",
	"T0DtZsJj1wtMeENt2P4mqUyzesL6E8NKZVegCRig2rUZAi7Ig/DW7XNaLPL2UtZzaVimTW3p4vCC6doV",
	"XXfmlU2H8Zd9M9ZyqmVixbxRqf+RsghnlXnfHx8j8+SJV9u67wg9LZF5Dl4ppnNexn5mKTI7S0g77IB+",
	"fQQXmrCFQPQiyiH26TWEW7RgOvhCcQpfuxReo2UZlbcU6TU/kWZZm7Cxj64NNzkNQa0UoTkUWh8iM2TO",
	"CCMdlVQVkiSJNUn0qcRqY/e5MlUbkz+ChYOzVL71yVgY/oO+R1vr7TG+x/XO/Xo5VcLfh8vTjUfCvWZQ",
	"VMayqnmwjkHIoh4gVjHGIB3eLmWpHZTOy4PitJ8RSsTisRc7o+ZjJMzdOTOrP4TH1e2rVxYSGpMliXOc",
	"+CqLdPf9fWQinXSJfhNLZAryZ47DeiTZZd4fAmYjpfRt0R+6NcDQMsdT+sIHyc1C2bzM6TpCs8JIW6hG",
	"VBtvOHvoGIsu17Wx6VeWs281L/ON4yd6a/QHljWwVRUEnkOj2/1poG3b9WqoLVWtMN4RXF2sgWulRF7/",
	"Xo6MChXrWykRkkSu5EVVI/+L8IEwxdz30YV9mqnwkrj6IDdnSDIU2+dyisK5SJIUEAhJUixhiFFADD+2",
	"JENzkDVE+uXB9xEr47A2OAfkwPWCs3y+yHIfw1ZWPSdCW1QdnmWU8aM9NzIISAdPDkio/V2n+w9Lq/2R",
	"8/oj53XLOa/v6yV/thJfb5eoWcGjK/W1LWRooj1N3j55IoOEmccm761hjTjaLiu0Jwxal9t6MUrPseaG",
	"cggjCvc2h9A5k4csfCkpqynO3VpWlSE65eb2c5EHKVYuzdNTrfpXY8tZnVaPMkOuux/bQhy/Kel/5NL9",
	"yKX7L58G/rRCo54KvvY5rrTOpuQwL618e7m9fdXBYLa+6nD4XKpDrgHcuuqwZb4zZNxQgyjCa/pyC8qH",
	"00ZPWgHAgtPufC2a+GkLQbKXLXUY5lb8oiwrI5Iq+f3ub10aQB27no18Rs2bQrenp38ro1LtCrslaBHq",
	"xPS9jeO70FW1fLrw0/ezmlvJtCD1AdsWqSOsv8brTxTq4L+P+E1CHYYvzwa5HmiHMnR7LnTUneJgE35X",
	"xkHstoY3lDyx/ZiGGKDYwTrmnnEFZQuXVCTkwVJtps6qLLal2nVPH6CkZrkoPVqhPDlfcHSdTrphniUM",
	"x1sI1fZG692EeYCUF3mVlNvOqhlaU7GeO7Nh6syzr7i/kJ1bVbVu3YU3ZgFbcmVeHb1sdvmVJIAkYyjB",
	"fA5oJ8UP6KdX5ye7j9RvNCAaNYn5FCdJ53YdUD/JaNN+FaXvv6ZRU4l8irpGXjWjIdeXZl2j4lWjjoRp",
	"2+Qpd4qZQj+rFdom5rMfUNP6ANEy0NbL2LW4WOTXqOFkeHDNSk4/yiz9MA39KLP0vZRZeho3UL3M0iBB",
	"HK4cUC9sMcUyWuwZs8aefrLWyerwbehEtfcNULfnb4teT3M18qYsplrfOlR7JMQN9FQWncevvEbbgueF",
	"PxRrpCWF0XUTKN/s3AZTDK+65XigXnvrX6gS1tYXrr8S1jY3cH9NLLdGRWWsf5U6VU+zMt11qra/NAdf",
	"9P8He2I1gd4lTN1qequ56saVqMWqbV9P/d1EKDk0PQR7WQVxXa9gLQG9MYOY2ggIG8YwvKAYZmPpOsiH",
	"o/E0JqdvsdhP5cZxaD32rDZof7fn9HGsS0fxAOs8zencXwgvdJHsY64fteo67CrPXK9u00NokLT5jtji",
	"CWpSVMA1aD9W/tRI8HQu4CfhMusLro1dmsC3LZeG1kh0WukalRJ/lDHsZaHvpIDhMAFWe25NTaZnN2uf",
	"82T0ZnSAM3KwfDFSy2P7fel4Yl7nR+pSWymmeA4p6Hf6LU+Yh8VDT6RVXoTS9XpC/SeVt7wDG98ayr28",
	"w7KGSWMYXTTsS7/9H3Ewic7eEL6VvbXeJ7JbE/0zB9US4YgzYSp/WburN2TTKtaz/0x4SYhO71x0dSN7",
	"N/AYpufoKBeq+l5nI/Ok8W6hWXhr3z2obqNyWJ/hQsBBpnjX8wUnZAbRKkpAD2+cpwF8S49T4GnLRh2d",
	"MGv5VZTGYRYP+x3c8lm3w9dPX/9fAAAA///3m2GAYxsBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
