// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent status
	// (GET /agent)
	GetAgentStatus(c *gin.Context)
	// Change agent mode
	// (POST /agent)
	SetAgentMode(c *gin.Context)
	// List all collections
	// (GET /collections)
	ListCollections(c *gin.Context)
	// Compare two collections — returns aggregates and diffs
	// (GET /collections/compare/{aId}/{bId})
	CompareCollections(c *gin.Context, aId string, bId string)
	// Drill down — VM IDs that differ between two collections for a given dimension
	// (GET /collections/compare/{aId}/{bId}/{dimension})
	CompareCollectionsDiff(c *gin.Context, aId string, bId string, dimension CompareCollectionsDiffParamsDimension, params CompareCollectionsDiffParams)
	// List detected applications in a collection
	// (GET /collections/{id}/applications)
	ListApplications(c *gin.Context, id string)
	// Get latest cluster utilization by cluster ID
	// (GET /collections/{id}/clusters/{clusterId}/utilization)
	GetClusterUtilization(c *gin.Context, id string, clusterId string)
	// Export collection data as CSV ZIP archive
	// (GET /collections/{id}/export)
	ExportCollection(c *gin.Context, id string, params ExportCollectionParams)
	// List all groups in a collection
	// (GET /collections/{id}/groups)
	ListGroups(c *gin.Context, id string, params ListGroupsParams)
	// Get group by ID with its VirtualMachines
	// (GET /collections/{id}/groups/{groupId})
	GetGroup(c *gin.Context, id string, groupId string, params GetGroupParams)
	// Get collected inventory for a collection
	// (GET /collections/{id}/inventory)
	GetInventory(c *gin.Context, id string)
	// List VirtualMachines in a collection
	// (GET /collections/{id}/virtualmachines)
	ListVirtualMachines(c *gin.Context, id string, params ListVirtualMachinesParams)
	// Get available filter option values
	// (GET /collections/{id}/virtualmachines/filter-options)
	GetVMFilterOptions(c *gin.Context, id string)
	// Get all distinct labels with counts
	// (GET /collections/{id}/virtualmachines/labels)
	GetVMLabels(c *gin.Context, id string)
	// Get VirtualMachine details
	// (GET /collections/{id}/virtualmachines/{vmId})
	GetVirtualMachine(c *gin.Context, id string, vmId string)
	// Get utilization breakdown for a specific VM
	// (GET /collections/{id}/virtualmachines/{vmId}/utilization)
	GetVMUtilization(c *gin.Context, id string, vmId string)
	// Stop collector
	// (DELETE /collector)
	StopCollector(c *gin.Context)
	// Get collector status
	// (GET /collector)
	GetCollectorStatus(c *gin.Context)
	// Start a collection
	// (POST /collector)
	StartCollector(c *gin.Context)
	// Delete stored credentials
	// (DELETE /credentials)
	DeleteCredentials(c *gin.Context)
	// Get stored credential status
	// (GET /credentials)
	GetCredentials(c *gin.Context)
	// Store vCenter credentials
	// (PUT /credentials)
	PutCredentials(c *gin.Context)
	// Check vSphere operation capabilities
	// (GET /credentials/capabilities)
	GetCredentialCapabilities(c *gin.Context)
	// List groups from the latest collection
	// (GET /groups)
	ListLatestGroups(c *gin.Context, params ListLatestGroupsParams)
	// Create a new group in the latest collection
	// (POST /groups)
	CreateLatestGroup(c *gin.Context)
	// Delete group from the latest collection
	// (DELETE /groups/{groupId})
	DeleteLatestGroup(c *gin.Context, groupId string)
	// Get group by ID from the latest collection
	// (GET /groups/{groupId})
	GetLatestGroup(c *gin.Context, groupId string, params GetLatestGroupParams)
	// Update group in the latest collection
	// (PATCH /groups/{groupId})
	UpdateLatestGroup(c *gin.Context, groupId string)
	// Stop inspector
	// (DELETE /inspector)
	StopInspection(c *gin.Context)
	// Get inspector status
	// (GET /inspector)
	GetInspectorStatus(c *gin.Context, params GetInspectorStatusParams)
	// Start deep inspection for VMs
	// (POST /inspector)
	StartInspection(c *gin.Context)
	// Get VDDK upload status
	// (GET /inspector/vddk)
	GetInspectorVddkStatus(c *gin.Context)
	// Upload VDDK tarball
	// (PUT /inspector/vddk)
	PutInspectorVddk(c *gin.Context)
	// Get inventory from the latest collection
	// (GET /inventory)
	GetLatestInventory(c *gin.Context)
	// Get agent version information
	// (GET /version)
	GetVersion(c *gin.Context)
	// List VirtualMachines from the latest collection
	// (GET /virtualmachines)
	ListLatestVirtualMachines(c *gin.Context, params ListLatestVirtualMachinesParams)
	// Batch update migration exclusion for multiple VMs in the latest collection
	// (POST /virtualmachines/batch-update-exclusion)
	BatchUpdateLatestVMExclusion(c *gin.Context)
	// Get available filter option values from the latest collection
	// (GET /virtualmachines/filter-options)
	GetLatestVMFilterOptions(c *gin.Context)
	// Get all distinct labels with counts from the latest collection
	// (GET /virtualmachines/labels)
	GetLatestVMLabels(c *gin.Context)
	// Remove a label from all VMs in the latest collection
	// (DELETE /virtualmachines/labels/{label})
	DeleteLatestLabelGlobally(c *gin.Context, label string)
	// Add or remove a label from multiple VMs in the latest collection
	// (PATCH /virtualmachines/labels/{label})
	UpdateLatestLabelVMs(c *gin.Context, label string)
	// Get VirtualMachine details from the latest collection
	// (GET /virtualmachines/{vmId})
	GetLatestVirtualMachine(c *gin.Context, vmId string)
	// Update VirtualMachine properties in the latest collection
	// (PATCH /virtualmachines/{vmId})
	UpdateLatestVirtualMachine(c *gin.Context, vmId string)
	// Get utilization breakdown for a specific VM from the latest collection
	// (GET /virtualmachines/{vmId}/utilization)
	GetLatestVMUtilization(c *gin.Context, vmId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentStatus(c)
}

// SetAgentMode operation middleware
func (siw *ServerInterfaceWrapper) SetAgentMode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAgentMode(c)
}

// ListCollections operation middleware
func (siw *ServerInterfaceWrapper) ListCollections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCollections(c)
}

// CompareCollections operation middleware
func (siw *ServerInterfaceWrapper) CompareCollections(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollections(c, aId, bId)
}

// CompareCollectionsDiff operation middleware
func (siw *ServerInterfaceWrapper) CompareCollectionsDiff(c *gin.Context) {

	var err error

	// ------------- Path parameter "aId" -------------
	var aId string

	err = runtime.BindStyledParameterWithOptions("simple", "aId", c.Param("aId"), &aId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter aId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "bId" -------------
	var bId string

	err = runtime.BindStyledParameterWithOptions("simple", "bId", c.Param("bId"), &bId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter bId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "dimension" -------------
	var dimension CompareCollectionsDiffParamsDimension

	err = runtime.BindStyledParameterWithOptions("simple", "dimension", c.Param("dimension"), &dimension, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dimension: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompareCollectionsDiffParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompareCollectionsDiff(c, aId, bId, dimension, params)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplications(c, id)
}

// GetClusterUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetClusterUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", c.Param("clusterId"), &clusterId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clusterId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterUtilization(c, id, clusterId)
}

// ExportCollection operation middleware
func (siw *ServerInterfaceWrapper) ExportCollection(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportCollectionParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", c.Request.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportCollection(c, id, params)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGroups(c, id, params)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id, groupId, params)
}

// GetInventory operation middleware
func (siw *ServerInterfaceWrapper) GetInventory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInventory(c, id)
}

// ListVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListVirtualMachines(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListVirtualMachines(c, id, params)
}

// GetVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetVMFilterOptions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMFilterOptions(c, id)
}

// GetVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetVMLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMLabels(c, id)
}

// GetVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVirtualMachine(c, id, vmId)
}

// GetVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVMUtilization(c, id, vmId)
}

// StopCollector operation middleware
func (siw *ServerInterfaceWrapper) StopCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopCollector(c)
}

// GetCollectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetCollectorStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCollectorStatus(c)
}

// StartCollector operation middleware
func (siw *ServerInterfaceWrapper) StartCollector(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartCollector(c)
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCredentials(c)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentials(c)
}

// PutCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutCredentials(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutCredentials(c)
}

// GetCredentialCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialCapabilities(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCredentialCapabilities(c)
}

// ListLatestGroups operation middleware
func (siw *ServerInterfaceWrapper) ListLatestGroups(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestGroupsParams

	// ------------- Optional query parameter "byName" -------------

	err = runtime.BindQueryParameter("form", true, false, "byName", c.Request.URL.Query(), &params.ByName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestGroups(c, params)
}

// CreateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateLatestGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLatestGroup(c)
}

// DeleteLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestGroup(c, groupId)
}

// GetLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) GetLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestGroupParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestGroup(c, groupId, params)
}

// UpdateLatestGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", c.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter groupId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestGroup(c, groupId)
}

// StopInspection operation middleware
func (siw *ServerInterfaceWrapper) StopInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopInspection(c)
}

// GetInspectorStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInspectorStatusParams

	// ------------- Optional query parameter "includeVddk" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeVddk", c.Request.URL.Query(), &params.IncludeVddk)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter includeVddk: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorStatus(c, params)
}

// StartInspection operation middleware
func (siw *ServerInterfaceWrapper) StartInspection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartInspection(c)
}

// GetInspectorVddkStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInspectorVddkStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInspectorVddkStatus(c)
}

// PutInspectorVddk operation middleware
func (siw *ServerInterfaceWrapper) PutInspectorVddk(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInspectorVddk(c)
}

// GetLatestInventory operation middleware
func (siw *ServerInterfaceWrapper) GetLatestInventory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestInventory(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// ListLatestVirtualMachines operation middleware
func (siw *ServerInterfaceWrapper) ListLatestVirtualMachines(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLatestVirtualMachinesParams

	// ------------- Optional query parameter "byExpression" -------------

	err = runtime.BindQueryParameter("form", true, false, "byExpression", c.Request.URL.Query(), &params.ByExpression)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter byExpression: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLatestVirtualMachines(c, params)
}

// BatchUpdateLatestVMExclusion operation middleware
func (siw *ServerInterfaceWrapper) BatchUpdateLatestVMExclusion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchUpdateLatestVMExclusion(c)
}

// GetLatestVMFilterOptions operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMFilterOptions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMFilterOptions(c)
}

// GetLatestVMLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMLabels(c)
}

// DeleteLatestLabelGlobally operation middleware
func (siw *ServerInterfaceWrapper) DeleteLatestLabelGlobally(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLatestLabelGlobally(c, label)
}

// UpdateLatestLabelVMs operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestLabelVMs(c *gin.Context) {

	var err error

	// ------------- Path parameter "label" -------------
	var label string

	err = runtime.BindStyledParameterWithOptions("simple", "label", c.Param("label"), &label, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter label: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestLabelVMs(c, label)
}

// GetLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVirtualMachine(c, vmId)
}

// UpdateLatestVirtualMachine operation middleware
func (siw *ServerInterfaceWrapper) UpdateLatestVirtualMachine(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLatestVirtualMachine(c, vmId)
}

// GetLatestVMUtilization operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVMUtilization(c *gin.Context) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", c.Param("vmId"), &vmId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vmId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestVMUtilization(c, vmId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent", wrapper.GetAgentStatus)
	router.POST(options.BaseURL+"/agent", wrapper.SetAgentMode)
	router.GET(options.BaseURL+"/collections", wrapper.ListCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId", wrapper.CompareCollections)
	router.GET(options.BaseURL+"/collections/compare/:aId/:bId/:dimension", wrapper.CompareCollectionsDiff)
	router.GET(options.BaseURL+"/collections/:id/applications", wrapper.ListApplications)
	router.GET(options.BaseURL+"/collections/:id/clusters/:clusterId/utilization", wrapper.GetClusterUtilization)
	router.GET(options.BaseURL+"/collections/:id/export", wrapper.ExportCollection)
	router.GET(options.BaseURL+"/collections/:id/groups", wrapper.ListGroups)
	router.GET(options.BaseURL+"/collections/:id/groups/:groupId", wrapper.GetGroup)
	router.GET(options.BaseURL+"/collections/:id/inventory", wrapper.GetInventory)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines", wrapper.ListVirtualMachines)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/filter-options", wrapper.GetVMFilterOptions)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/labels", wrapper.GetVMLabels)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId", wrapper.GetVirtualMachine)
	router.GET(options.BaseURL+"/collections/:id/virtualmachines/:vmId/utilization", wrapper.GetVMUtilization)
	router.DELETE(options.BaseURL+"/collector", wrapper.StopCollector)
	router.GET(options.BaseURL+"/collector", wrapper.GetCollectorStatus)
	router.POST(options.BaseURL+"/collector", wrapper.StartCollector)
	router.DELETE(options.BaseURL+"/credentials", wrapper.DeleteCredentials)
	router.GET(options.BaseURL+"/credentials", wrapper.GetCredentials)
	router.PUT(options.BaseURL+"/credentials", wrapper.PutCredentials)
	router.GET(options.BaseURL+"/credentials/capabilities", wrapper.GetCredentialCapabilities)
	router.GET(options.BaseURL+"/groups", wrapper.ListLatestGroups)
	router.POST(options.BaseURL+"/groups", wrapper.CreateLatestGroup)
	router.DELETE(options.BaseURL+"/groups/:groupId", wrapper.DeleteLatestGroup)
	router.GET(options.BaseURL+"/groups/:groupId", wrapper.GetLatestGroup)
	router.PATCH(options.BaseURL+"/groups/:groupId", wrapper.UpdateLatestGroup)
	router.DELETE(options.BaseURL+"/inspector", wrapper.StopInspection)
	router.GET(options.BaseURL+"/inspector", wrapper.GetInspectorStatus)
	router.POST(options.BaseURL+"/inspector", wrapper.StartInspection)
	router.GET(options.BaseURL+"/inspector/vddk", wrapper.GetInspectorVddkStatus)
	router.PUT(options.BaseURL+"/inspector/vddk", wrapper.PutInspectorVddk)
	router.GET(options.BaseURL+"/inventory", wrapper.GetLatestInventory)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
	router.GET(options.BaseURL+"/virtualmachines", wrapper.ListLatestVirtualMachines)
	router.POST(options.BaseURL+"/virtualmachines/batch-update-exclusion", wrapper.BatchUpdateLatestVMExclusion)
	router.GET(options.BaseURL+"/virtualmachines/filter-options", wrapper.GetLatestVMFilterOptions)
	router.GET(options.BaseURL+"/virtualmachines/labels", wrapper.GetLatestVMLabels)
	router.DELETE(options.BaseURL+"/virtualmachines/labels/:label", wrapper.DeleteLatestLabelGlobally)
	router.PATCH(options.BaseURL+"/virtualmachines/labels/:label", wrapper.UpdateLatestLabelVMs)
	router.GET(options.BaseURL+"/virtualmachines/:vmId", wrapper.GetLatestVirtualMachine)
	router.PATCH(options.BaseURL+"/virtualmachines/:vmId", wrapper.UpdateLatestVirtualMachine)
	router.GET(options.BaseURL+"/virtualmachines/:vmId/utilization", wrapper.GetLatestVMUtilization)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbOLPgq6C0Z+vY9cnXJLNncio/bDmTcX1x4ooTz9ZOsimIbEk4JgEOAMrRZF21",
	"D7FPuE9yCjcSJMGLZNnJzMmfGcXEpbvRaDT6hq+jiKUZo0ClGD3/OhLRAlKsf57MgcoLFsM7+CMHIdXf",
	"Ms4y4JKAbpGyGNT/gebp6Pnvo4hRCpGEeDQexUSU//w0HslVBqPnIyE5ofPRePRlj+GM7EUshjnQPfgi",
	"Od6TeK4HnhIaq2bPRxz+yAmHeMwosNmLYkhUGf/u7m5cNFWQaMjKWdn0PyCSo7uxQepKYpmLJj4Ro4Il",
	"MDHjEkabTYBzxtWPGETESWZajcouSLdA/uc68nfjkSggqI2Tcw5UIgsJispxbZfxhtRWvfaWmFOcKkx+",
	"VyBXkTVUmXijtjQ5q0xWJ72FM0R8xy9VnN9jPgeJ1Ec0YxzJBSCslml7uHqrrhjax7H2qRs3jcA4wCdB",
	"VsuyhERYfX9NhHwHImNUQJOncNlQ/5tISPWPf+EwGz0f/beDco8e2A164I3+dgl8SeBWTWqhwJzj1agO",
	"fmWiHpCLQRvgVlavvpjeCH17QK1O9wC6RaDnMp2wnMpm5zd5OgWO2AxdXwjEc0oJnSO5IAJ5uJdDEiph",
	"DtyMuRHtry96qW6xqFLDoWAm7lmL64vmKpC4if71BTo/G07q64sWCtcQIGqf6JYhOE+xjBYfshhLePkl",
	"SnJBGG0/Mcica5R00xgCSBSDaIkHSDIkQGrJgJNELWwJ8JSxBDA163ceixaSCDVIrkEcjcslbpCpsozr",
	"H1EpoS+OxjFZwrggX+NkMnCOA5QIEXeCMzwlCZGr1jPLtbD/rp9oSQKRNEdWF0u/zcCAU86o5p8xDhEW",
	"EjYdgFCRbQ5AjXYlNv7AFSibRKyP4dMrSPIkVyP9AljmPETTmIuXFE8Tx7wznCdy9HyGEwHjGvv9tgC5",
	"AI7O3l2hnTOiWG2aK/XlHQiW8wjQVbSAOE+A7yIiEJiB7TlIBIoMNEGWj7k+sipQjN4wWpc2z0dqepxL",
	"lhq5WjlqyxncYftLniQrdGLa60PyEnNJcP2vF5jmOBmNzZyfgmoO43gOZxtQ7Mp01ZRbjzB37Yv6QZKE",
	"/InDql3E6IzEQKOAqDzDEqOILUHDVLZEGfAIqFR/3TncOzo83B2jCCdRnigiISzQcnL5Ye8WyHyh/uDG",
	"MFybYrVkMcunifpLir+QVK3B0eGhkhDU/OuwQIjq800hFGX5Z7ycB85PC+Pk8gPKS3QDgG4DhBR/aYJw",
	"YcZ4JBCyn581Qfj5mVy4+UjyGNRIIe1ekBRSxlePAEXnmjwaFIOW5RGgqYt/u29K3ikZuVzEEoWSpGNf",
	"QAQPDnM6hWULByUPTgI6628LoEYQF/3RLRbIdqlgjyXsSRJWikMKYQkSUoBLMiO+yOxTEL3uayqKYw/j",
	"blqdzOcc5kozaxLNCG3RpefHREhCI4mKxiHl/nsnv1EG1QnXhWvZSl9vdihDE04kiXCijqQIOBW7Qfwp",
	"oxeDpqCM7tWnwRIlgIVEjEJjwvB8kkmcKE29edlXXxCt3NNIfQECY4Y4rVxVb8YKMeuYj0ue6ubKCUsz",
	"zIlg9IzMZgEdkKRARfAG/H4BqPiMpqBuoJEeTnOTU7I0wAFoPfIHVSpGk9U5PelTp6sIXCqNo+h8uknn",
	"2gKUBChBKscfStyrPE0xX7XeW5xFpHaiOpEhtDo4ZXLhMY/YR+c0hi/oUOmNJ2hnigUkhMLuGBH94Uh9",
	"ON33r4Ld1GjKqjt9Ap2b7sf6ACr/UbUGjEexZaHGpgNOIqS+AlenikA7pyglNBfoZBfdErlAYpWmIFUz",
	"AXJPNUURy6kU6pws2Wy/EH9ogQWiDNk1ObAropBtF67DeeEllXzVlFgbDNAQSRuM4YuZtbvXGHoLAiR8",
	"W9U8bJmge190WwlrW2JN1u21UvnDd4DJeJshosUy/lKbw1MQQql0t+q0NRZifavTfTrt405ecsDxyihh",
	"2uiqTb0O6No/kNkziuwZ5qLy2QhhPe9QO3kFcfPfdxaa4MeJD2JLCw/uWosLA3tXE/PfywK1rjmsIT/Q",
	"4KUhwhr2+9A+CpiHE4kDN+hCzPlSbh9dMkEkWaq7AKYCnWoBljIO+0HNwjv+6rpWTqXTKASWRMxWhfG3",
	"PI8JRSdomktEmVT/OO2Y5fQ+s5z6s5z0azSGbP1U16dxg+iZ/WvYm6S+Wp0riK763mJRr+trqqlo1/mG",
	"KHzaIKt1PiJQQoRsscd32XOZ7a7A2Ucv00yukJZrRsJohOFLBBCbNhq7/eHG3+DpMDKUGvkEc4AGF07r",
	"p684y7NWg3jNmZLiL6+BzuVi9PzZ4eHGXlOWKjwzuRqn+MuLZ4eHGqEZSawhNyXUTXN0f9estnvrGdw1",
	"0kPD3c+3PZ/G7EhjFva3WGxbFkZfx3DSdpjlPMDKywlQCRx9ePfaXFiKYQSaQsKUHGCh0ywXwMM3bDdk",
	"0SLk7cJJ6HLpDKU+FJgDEpLxwlAKiIPMOYVYQb0ftpb6xFOIewC72UNUPMMS68lC1yNxcx4Ht9mMA0xw",
	"hiMiV69OvSbe3l9gHt9iDidRBAlwdcm7YEvwGntW8AUT8jxAn/Pixq3EjiKFaqnkAwcrrx0CShXBUuJo",
	"oU9LmieJ0UolzyF0XWcxJEHsMs4ki1jyXn/42moRP2cTRmdknvPCGN2lx12Fezmp20dP2QbNEmhslLZu",
	"w47+2pyssZrFiGPHAu2LWSOWo2qQ0yABCa/xFJJXCZviJFl1eNNnM6P29HiH5QJLtMCxZo1EjY04pGyp",
	"WaBJQ90ifNs3nfV4t1g0R2khqhlxXAIcQl2fHj32xGEGqk63/Vv9Aydorubr89yXB0l1lF/03xF8yTgI",
	"rQjtZDfzA9McnV293lW69xecZmpzjaz192N+ePgEXqB/e3WKMI3dVRa9QP+acRb/61Br2wdK/sjBYrCJ",
	"ufOVwZ2ILMGr1uAD40deg/QdRtKOM0oD030j1JgOvwwaVrpr2iec8tijGHaofD26rQV03K5GtVKgB/vB",
	"OBO6BCqZubB09TgvGj4IZdYLNLkmXOY4ucDRglDo1VINScwU6xJbqadvQN4yfhPSUpck5Ba1HZD5rrcM",
	"IlSQGLRUnWudN7R9s8B5fYlwHCvBEbSQ4yjg1DqZuD4ICyQAKJquuqemJY5hXDQSM87S7nEyDjNSaLlt",
	"g5lWKNHN0M7k/OxdxZ9FqHxyHL4cNpboVyIkm3OcmukyDpH2UFgtpbZi2FzC6/edhlZQioGU0Guc5C0M",
	"LyRkA7Z6MYjtMTaQhFjuVxa6EEVZPmEcOp0+k8sPKNKNWpU13/mT5VcsugHZO6awzYaM2nEClWdPGa6g",
	"dM8gX+sz8CJgalDkcQ5SQtHFaY1vfno6CM52XXWo8leodO0K2jmdcdzuwLsEri4Lkb7rrMmVUZa/XQKf",
	"sDQlMoWQjUItnWoTFW3QO6Ug76NJJRJDC0R0kiRMbxwdmSHQATImisvFSmjP1sRyVtPp3HB0FzeI4SK9",
	"vDUFkFVccsluQdvprDobx8ToZpcV2rZSrlwVNdpwwPR2bIFJraANoQkLn3XEjGbpvjV9d3LhmH+TpbVd",
	"3draf+IlJom14w9YXXtUDCehOz8DWJurU8WhXadhixZR7hzRoWv86tY6qHBsbflCZjEzdZN5PQJWdkpY",
	"gOhoviLE/L7uBej1LnSYS0kBjBnL89pmYKxR45ENLtaOBXWfMYb2CFN1y13Xx1BHX1Pwspgr+PldAUDw",
	"88SDKtygBDX4vcM9AF1r2O4haiF70a9BbefzcbRei5i+swOcvyb4zY2u9koc3/Qq5XF848nidQjk3UFq",
	"0dxDrycm0Nq7pNRvl8WXTgjOrHoYPK/90NdO72Kt+V3hHa3FWQ4YxO+hr2tWoei+qqlGatVKzaJz4Yyx",
	"1buEdba+aK6tuVgZ4IL0FSIHccoB38TsNhAHhuMlEXaZu4xT2vlfCbw5sT0RUXO0RDmZ2Jz1By+ietoH",
	"b5G/fSMb+dw+LKHmIA5apfoGPy87d0xxi7ne32sP/5vp2Dp03YPuyF9OWcVvXC5/83gomejCZQZobgrw",
	"kBAghFObGodb1G6VIGGTfGHaHGivLOd3s4XQaDcmLMUtkdEiCIuzzLW458p4ACExjTG3CWEurl79yw0/",
	"HuVU5FnGeDBRTEmBBNMWN8UyFa3mnbBxvDVBJpTZ0FRv/Pj4kJvHunV8b88CLwGJfDYjEdFuXk6WJIGK",
	"g9ZzlKRECELnl2WrxmRXGURkRiK0vMq0n6Qc0ti3MQdkx9ncmepwDRHrkrMIREB5CJts3+AUnHsns11D",
	"Cw08HKx3bT70DhFyMYbAf0fmCynIn4TO7cHWEdBTauRd51BzyNpZyUGx+Ofg5q7BXTYtjuqBaHRnTpg2",
	"n1vki/vcurermRcDbmZe9sPA1jYofmBrG7w+xAJAxM3Apl6GwMDWw4H2Iu4HtNbXts8ZZ0uiuB/iz1GW",
	"d90uK20Vyp9vphvPZS7jn9Np23X1czRQ8np8V+Myb5jxvWL+9fpWOLSVfN24dlEytAWvJOayvJi1BpC0",
	"x8lcsHcwc9mP9k77naQ/hhFu84w30rTmINS39wsOYsGSalbZk8N6StlrLIFGKyRde0QoSkmSEAERo7FA",
	"U1gxGqPbBYkW+iCwbnobU0SETsgnMegj2ACglY2WNJRnQfW8CXgzfc9l6UWNHL4Ll7RXjuNh5HLOjJ7p",
	"lCR/tNRk64X0INg0Oe/84C2aMCo5S4JJeoXVJ6iQ2FSft7NLwDfvF5zl80WWywoYPzdW89L00sFogG8U",
	"DVzHAWlBnR4Wc7muB2ylhPqm16Px3yeEy5vkcWK4ahNWg7ha1qPDbKLLRBgNvjiK8pzEQZ/jBh7gVuPK",
	"uJj6UyvcOl7l+kK0im4cB3P4tbzGsR+YosPKti24y7Woy2yFdWoDroLQmc8egDPO0kcFMcQuzr7TUiuh",
	"NywjtJTXFyaoxQTIiOFFPOrRzzZNLQZp6tfgWp0LscZ9atyRGndWS4jbZHCT2jXBEuaMh6ScN4tpi6Ky",
	"8QZT6a0yZJrENFxnirjqP2lbl6LV2gQLK6XO6eGmruMaIvO4v0LL9YXp35UnktNuV3dh7QIcLewG3hH6",
	"Js1j4AgLS2ej/uyO1vLvJX1raceOjLcl0d7tXMDmFE9KimrUw3RzFRc6rLMLP8Ki01daNOyO9dGffmG8",
	"muk0pN1vRC6s/VF093nDZPfwLaHsAdh6AWmbNUzxYD2SNEvgC5GrohiGVZva/Nxdy6DuT1fkT3hPgLtU",
	"wrtxgO/cRI77pytU1F9BJUwogSUkYwSUk2gBsdklxres5kKC/KlLPpiG++gqz4ALiEGg2JvmdDUpxvRi",
	"rkva+EEu3T6IJtdao0M5g8L+0SmII86ExvpmzyOgJMCF2s2xC8RSNxVrogc6J9Sm9b8np2N0dLh3bH4d",
	"H+49M7+eHf7jPTnd3f9IQ4QzmFvrwIaUe3V6j86OWFsmeBDR96usOwakbyI1QM8kQZ5dL+6kGU5wzw2I",
	"dg5ffChN92N09OIlFqsxOn5xATHJ0zF68uJXzOMxevritwWR8CphS9gd9aOY5X2LF8Jv4GaYXH7QGwBN",
	"cx1HhnZgf74/Rh9Hh3tPP47Uj2d7/2Z+/Lx39JP5dfQ/9p4cm59Pjv/xcTQAjQttVXpATMwE/ciEcHiy",
	"95P9/tOzvaNji+/R8c97x89s8+NnPw1D9A2Jit2+TTSnK/TmfGJSqT3ELKgWSIuP+d/TNoBJ0+Xbebms",
	"Nb/zKoH55/2geKOapzCgjFGPgBtIPOqf8u8Ai3WSj/uhY+K+kqaxHEyc0xnbVGja3iFZmW0tLI/jdOMj",
	"qE/XHKRorq1lqmZXC8whPiPiRgzMrFlC1Z0u9AjIWtTX0VKrCfhOd3KULE51Xz2oLlgLJ4f2XlCVNZe4",
	"Mm0wWIcvAh4IZLx8ebEHNGIxxGhyglQjMlNXPEDTnMaJsekugROXSQzIZQW+f33ld9hHF7nMdRk2MEUS",
	"l2DLRNyQ7H0i9kf3N8zplciwELeMVw1rxR/HD5Y/avFoq9KjtnydKIZ0zpJChKZFBrEiljAJ2FPQFSQl",
	"0yMgnDA61zkKZs3Q//+//8/wbMTSKaFmJJM3KdDTw8N9pKdXJJIQP0dk5noSgfBUAJW2gE1ZrPeGZEKD",
	"WgFvZ4qjm1vMY2FKwkhi4gF2/706qHYSKY6pDWsGAzNyLgy/KMA9eihsLB0RBYhLEpgM6KYdvi/Z1Y+W",
	"zTkZ3X/F1Yx3tcTYh+GpvvTWgqk/qX1ejexr7PHpykr/Rhx+IO4+DtQ/S+NnSOSpCzfIs4RhvcyYT3GS",
	"rBW68H4BKMUyWigucPEak0RHgrhO497QftdOgRsUfaaFO1RrKVhEmhjuQC4d0dspJRJd/XoSzKMjr9q7",
	"fzhH894RWkmjazpvQIQSnyp4QcJUU7O6ojtqUcaeXTaYp1nJlGiWofSslMHu9oLZVomhtGO0JpU0mbnM",
	"NGyG3wjFzaaBcfpdXxi+XNMUHCxoXCEyOj9TQFvJFPbxOH/5xBpX++pEe7HeroRakTqfKN1Bokzxh5AQ",
	"Iw4iT2RLHGMzgL3byVRr764S/RDrGwSasZx6ntYaO7ZmMAcW8YMAvhfDjFCInXG2HPfCX8Run2CGpQSu",
	"hvz48Sq0PFtxAtUdhy6jJJAeaG6x6zJ7VzG+90qBIEZ615iTCL9AnyLgxfvrlkC8YBHsIY53t8GIMCqg",
	"Ojx0rmIxZnDGlvrfVQTaJIoifhKM3O+mBkZFz6DWUUaUfR5QereouLu3h4TOIDfxPegAwZdM+9Q+V/7+",
	"BSn+GJToUwGlraptvYQslijFX9DOf9/9d6cE6vQTyirNdPrjRlAEK6gGoMh+fvZAULjgtoZB5aYy+MNM",
	"3l7Ktlk09kHXorWabRiQ7S6HPezOz4YUOHE6e+BEsAVqREuFGtvzKpyh48Y1mVXWXqbv1xC/peXP2WyM",
	"RC4yoDHEu8OiaMemIEKJZw2YMlC1ohp5ik5xAFRO0H6d7QwkJskWNbeo8k4KdL4SY0lZvDUyrjxoM0aM",
	"ZwtM1S9CcRSBEGSawG54Wg7iErhJcg6LDN1Ge66WhgY213lILro2uZzMZoRa10DNwFHkzV5+MNGGwdMg",
	"I1TpF9VIlgFzB/KBO0uVOfwmlx/EMOzuq3Dr2geb1nQ4M5UVQnELztS2yahKcAfG1CrGe5YAxzSCl305",
	"B7+o5qho74X4BU/0GeHpLeYQKgxjviDVCe1MCROIcQQzEuToGUvi0GoUkVnItEAcbE3B0Ci6dMN5MMRK",
	"w6K/o7dXPbVidLM34YIxboRZniStDDL3SmusUa3FL8jRkpYdSIe9+p/E1LnqJI1q0YWS+t6GzjqFD5qC",
	"YOD1bT1298Ok1Q3N3KayE1tOpAXJjJMU8xXqLjxirlsb7sNWz8ff/C4WqmdxUZSySGGOjSltkHzuuo+V",
	"96IGq0WYoinYi1GLxPpebmJnXs0pp8y13ej9UjZCQvzrda8cNw3d0eiU0B5pTkm0Kdu/OZ8E60wVHpmO",
	"UqWqjdOONlAxdXC2UpdCUYuviTBx465JGY7pCopW91gXyi5TLYCozR74IEKL4mLnI0ZFnoJORgjthhbr",
	"RPttvGMv9N/GJWOJsJnwVy2PE7oJ7Pn5XnVRQ5elEJpSRrVpG686DhUSJyaDoXzrsGk1Hp5Zfp16SWtG",
	"2derpQPEQ0fYErjQ3rW8cZxhIcicmqimjgPsUW5rHfXk/FuUt9uaVxNPj25cIDwh7rRQKw2G3KlcobDq",
	"neqG0ADNTWurFEYxZ+kYzRKWZasxysV0jARwgpMxyjDHSQJJ+E7ZB5O1YtR8OSGOPM2FhUZEgowVB4yR",
	"wBKPEV2mLdcvW/6yxVDiPq+5zWckCYbfn/0TqU8ow3LhHs4IZNmU4N3AqlVf076AG1hpJ7IdrHHsDDmh",
	"g+96avT1U2M7zoROpXmDQYtvKj+3/Z0yWn4KUp3HaZcEJMLIvHf4Flkuu8BZVpFSnvQzoQndIlUTiwgX",
	"xjAFeQtAUZonkmRJnXBi4MNkbYqs9V+E4gx0uPiqO5O/duQsGLdx106oFbEG1usRrk2mq+r05064huMS",
	"OgfLpzVwdsp7j6FaoLKLdcmI5vMW1pmzqeLeWIhQEHofZuH6Df4KukS9SVk74reidsR5pXbESVk74qUt",
	"bPRWMefAqjgB0GzmwcqbvKNVCVdHoyrIHQ09bDpaOUQ7mlga9BW4Nec/xH5pWxM7EzEq4YvUpWc5RCxN",
	"gcbYPduxwRYbXPjX2yz+YP1bprss7F/oLYDavi7CGZRgsqmOwbcBaqL2gcqpLpsSfZ2Sqs07UaDsUwwB",
	"D8eb84l9qqjrYA6cwz1FUjeqh9phSOoXgSYTsjUDch0zyA6HLMERqPu2TiWa2y+7D594SJmcJpjehAwe",
	"/S8aF1oEc6aCwnrQZzHYKH4vuCyhy1DPE6gPUojDBFX83St3rIXlQ5b6SFlLUZZh1T82r/uxXsWPltIw",
	"jef3ja8wdUU+AjU42qpvhDDpKw3i8WtfnRBv0UNFQz61pPjUU4EaO1KfOLrV6aCIrvenpb1YGo/GEC/z",
	"sAf13aM9kgQP5lAItwW9nOJTR7LTg1BBf7A1urZHipYYdz2Ztu8Q4SbtIZObcFzB8lNnbkMg47elardJ",
	"onKpQrVHH66Q/W4yfTLg6B3E6Fcs0T8nVwhzSaIE0NPjJ0+f/Xzk1RWx8cbacmzKQ38uK63piqhpTolc",
	"Vf6qblQEJ58XmMZJsJxnCTDE4cde8mzOcQzvKnp6oHqw+w4xenuFbC8XlIW8unDqswmhNu4C2zTWNRiQ",
	"36xXrXflhkI154onAm3JQ40dkfoZjBNhwwuLhBlkAlhPLs9HXpTraHmsuSADijMyej56sn+4/0SroXKh",
	"GeFAF6XQkbkmEIC50nPn8ej56BVIPfCVs65ye4fQnY8PD60KIO0gXjL6wX8IQ2ejSvcp2v40GudQfK4o",
	"Ah+fmanrzl4JnOIECeBL4Laar84ScGJCYYSwP9h4ZFSj380c+l6YWU9plRhXlhi6BI9ZSBDylMWr7VJB",
	"je/031o4uuQ53H27VdAFhaIFpnOI1So8Da+CfgAKcYeCavdzMLRllhAjpzZezokGxq5oahamvp5349FB",
	"7SnMILOrO/Kk8gLng9G55QXPAMmdA8pH4D4E0+PhJEHVt0YdzXz8G5Q7sI8SH3zF5/HdwdfpeXzXSk3z",
	"BiFUCZphjlMwhTV+b5jS7au7/rva2i9BqM4lkgvntng+wvqhqOrGGHvEb8jdJve5JxKRxHwOcsis0zVn",
	"/fQoLNR8HDnARx6+lhmMLSsDvudhjsuHkjGN9UvDwuzgp4HQEWKek/PefGfShJnfb1Mb1kHylvlsqvOU",
	"XJJVENB78PHB1+ItznV4Wr/1/V+Or8fBzCLz6rRk7u3y8Fz+M+DtM97vzfMmgJelDRPtHO1NsYB4dx+d",
	"qO2nHeqFJylZKRTso7Gat7wHsTU+f+SgLbAWIWvZK2EvokGOvHpyRyGtvuvCoAMjlX6tza/qhyAxdMBg",
	"I1tLODrnfmzRpDdKQC5d4jmh+gEOi7JWrc0L54XHTC6awsCFi83JEmj5kG6vWlI+ubvUrw49tnA74yRJ",
	"UMxuqZZnXVgHMMYNfIfKvK8kvjuolxxr1YNO/IY98m3SL2DI93NuepgN1b1CFdjaT8XJtjlGgxGEARGK",
	"sMcjvvJbKQsW5gZXd+zgq/2lzsFauEzbtTBQ5PnR2aQhP11Oq6ljq7MO0MdRzFJM6F50dPzk42gXMY7m",
	"QM2zokXJuzaICsJ0AlaGTv7vHTfbx4/xP/6P7b73++Hez3hv9unr0U93u/8SsAs8JMd3VBgPKYqWIvXk",
	"k/KBO5vkWDxig3g5ATL1wnulcFmHGVkL2zrbaYwo8+fXc47VyhYlDLey816BLLANkGW6qvKP23sewdu2",
	"HnzRZGrbYC/154m/sb/13pqwNMV7AhQciugGAyQiloFX6octgS8J3I6XqRibHN+Po919dGaUIl0LtGz1",
	"cdSmVelxR9s7JP40D0iWwxWG3SmhWM9cn6CxNf7X+SXCPFqQpQ6CkZjoxz4mV9c6wkr0cr1B6tEODsNF",
	"vgqjNzIWGmQPm/WUiDK1u1V9eOWeb/3WXGvfF7bJ5lMbL70TYQF7hAqlQ0mi38SYmkFMRMFuC1dOV2+M",
	"G2kNEGpXD+2lN4HIj3absOi728Q6l4hi+uPD1lrZj32/aD503KG8WW7t25qz+kPUj6zf4SRxy9Su1Nlt",
	"1bkvD77q/3eZ5l6B2aDfwf40D2i3jW4xud8UV0oGzggksa1hGxNusSpOLTXfcywiU7nNHurP1Tj68Lq2",
	"LKLHwNwkvo+Rn3U6dqqATsvUXtqxfURybAswjFGU5R8EnoNpY39ynNpfUZafLOe628lyvu+/fF4UCVZQ",
	"WgJp+EafVKss0fG09mnG0HGqtA2fbMOrbAi50k4ndWCOusWbuqFm5kJvGPfRJJxGZyMB922lWJcEs4/L",
	"m8gbw7r1iOEBMorZ02+LKrEZb7pC52cGLCJFKJh5kNSqFNlvE1fnXhn9v5Etwn83IGCx16ho66T3wPyA",
	"9S7ab3HNoyY01iAVPKkcZgRaF97GSqZeSGarPtlkru9EsZyufJWhTWl86Tf5cXT9OLr+4kdXR2x5hyYe",
	"PLz6AwiQt9UfVyevB5u3K+Z11IaJvANz6dhjWbdB/hXI2qMif69jsO3FlAAvWbHrKPZo/KDDhtxb8O6y",
	"aKAwfiRxf24oQ9vbuaB4CuRvtfy1B0pCMsRE9Nv0G/1mx+OufaLjRSvPkfjA3Hvxvy7Tnit7I5vjW6tA",
	"jVKL4WkUYt8Pr4XqOQX4rYZbXOaCD9C/61XytsaFLVBtifmGuv6uL74vr1+NKu4Ry78CNwbrDQS48aLq",
	"jhvOjQXvKb4MlJSrlIq5L3tWfGOuBr29JQr3TrQulzGIX93j8QmY2hW1aFzJsknRsLFI7WRh+mXsLIP7",
	"7Uc1P4o8AGoeFGZSTFv9567Vw4dW16dqtzUwvq0Q66g+YBt9WkKtJeayY3WPvwFxbJURHaZ//9jnMuIy",
	"4YBjXewh42zObYGYe/Al5rLtnuLTXu+06vsE5V6rJ0ekbAlCa0H2VXlXisR/Xb6IEFCSZYoF7I/GtYU9",
	"0zP4zyIM2rneJAbGe8Zg6TECD+T7pPL+6m3kOmFMNGpjJJSCxFrA7nx491qHEO7uozewND4mJkC/ecVN",
	"+SZ19TdF5ffR+4WushRnjFCJYgZCC3EOmrOwhArJ8RwTKqSr5t4kuBI1XdTeopgppunYSiWBSkETPMPe",
	"sAqehsD3FkvNdWqKp9q6F88LVw5kuxaiazHGCGjEV5ksjHfixkSeohtYjXVsqQZIuLIsCYtwUuwehE1l",
	"TBxpF7UPNMh9dKKd1krQUIkuP7xHbAn8lhMFleqWcVgSlotkFWD0JqNc5g1G2X5+S+BZlEfOcFmPSwVy",
	"uy4ul0uz4fHh0TeDKeIQgKg73srrzjjKKQccLbQxwxWnuqcyxCF0JrRurNrpcxDhDOuXTUjFFVAjwgKi",
	"G1E8XZFxsiQJzMHGxiYJKnhaoJ1CBxm7mv3q54xxiLCQwHfteyiB3YGuCJ0ngBK18dx0kZrdhJ5pfXXe",
	"I20nPkoPydJunlUH+xRtrMTTBucC+EcUw3oNC5oWEKCoSq12rhkQfvRax+wNC0L6ESH0I0JoyxFCb+px",
	"+1vxRtglaobhdgUKtV2wJvoI8fbJAx34Zh4b6rBGSuvRdlmhPbzCnqXr3egeY80N5RBGFG5txIXTEocs",
	"fCkpqwFhbeYUcyWqMkSn3Nx+5NanIVdBFxRTXAKHrMaWY2Ds9dEMue5+bDMIfVPS/4g8+BF58F8+aO5h",
	"hUY9cG7tc1xpnU3JYcqlfXu5vX3VwWC2vupw+FiqQ64B3LrqsGW+M2TcUIMo7s19npiy+unoQeMlLTjt",
	"F92iie/kCZK9bKntq7Yi+b1dQiXJ/GhI97cuDaCOXc9GPqemMOD12dk/S3OzXWG3BC1CnZi+13F8E7qq",
	"lvWHP30/q7kVvxSpD9i2SB1+qRqvb1/y1WZZS/odf4Pl2cAzhnYoQ9cXQpvTFAcbu1pp7Nlt9Z2VPOFc",
	"Z9vZu5hLFANk/gOfSje7vmjjkoqEPFiqzdQZw25bql338F7f2svEoagCX3B0nU66oXt5+P5BLOVovZsw",
	"D5DyMq+SsnMTmlrrmMsDpYnvaUwrJKzWxXM19PuTQ6uF3HS/cO22x1NXBq64v5CdW1W1bt2FH8wCtniv",
	"nx49CT3plQCSjKEE8zmgnRR/QT89vTjdvad+owHRqHmPYrdu1wHZJkab9nNOvv8MkKYS+RBZIF7ux5Dr",
	"SzMLxHuAuzW8rHhc++F2ivdEeWibmM+IeKXp26oILgNtvfgmi4tFfo2MF8ODa+a9/EhK+WEa+pGU8r0k",
	"pTyMG6ielDJIEIfjLOthwFMso8WeMWvs6brzTlaHb0Onqr1vgLq+eFn0epirkTdlMdX61qFapS830ENZ",
	"dO6/8hptC15Z/B8Va6QlRfmu0IUYYukZxhTDc5QcD9Qzlf5CeUNbX7j+vKFtbuD+DCK3RkUe0V8lq+dh",
	"VqY7q2f7S3PwVf9/sCdWE+hVwtStpjf3XTd2bwoHbPvuEaHvI/fBoekh2MsqiOtA5LUE9MYMYoKeEbav",
	"oGleUAyzsXQd5MPReBqT07dY7Idy4zi07ntWG7S/23P6JNaJNjzAOg9zOvenDYYukn3M9SOzr8Ou8sjZ",
	"fZseQoOkzXfEFg8QbN7xrtim8qdGgodzAT8Il1lfcG3s0gS+bbk0NKPUaaVr5JX+SPrsZaHvJN1zmACr",
	"1UxVk+nZzdrnPBk9Hx3gjBwsj0dqeWy/rx3vxOj8CP2acIopnkMK+rEdyxPmdZBQndNKtUydiBPqP6k8",
	"yBHY+NZQ7lXfLJMTGsMoAreBUqm5xEGwnEfgDeFb2Vuzo5HdmuiPHFRLhCPOhEnps3ZXb8imVaxn/5nw",
	"khCdXrno6sD7qo2K1p6jo1yoatHtRgpeo/iwWXhr3z2obqNyWJ/hQsBBpnjX8wUnZAbRKkpAD2+cpwF8",
	"S49ToD51I0EmzFp+etQ4zOJhv4NbPut2uPt0958BAAD//8BoPCqu8QAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://raw.githubusercontent.com/kubev2v/migration-planner/main/api/v1alpha1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
